/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package servix;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import servix.Login_CRUD.Clientes.JDialogInterfazClientes;
import servix.Login_CRUD.Usuario.JDialogCambiarContrasena;
import servix.Login_CRUD.Empleado.JTableInterfazEmpleado;
import servix.Login_CRUD.Encargado.JDialogInterfazEncargado;
import servix.Login_CRUD.Usuario.JDialogAltaUsuario;

/**
 *
 * @author DAM2Alu15
 */
public class JFrameServix extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameServix.class.getName());

    /**
     * Creates new form JFrameServix
     */
    ConexionBBDD nueva;
    Connection conexion;
    int id;
    String rol;
    
    public JFrameServix(){
        try {
            initComponents();
            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());
            ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
            this.setIconImage(icon.getImage());
            nueva = new ConexionBBDD();
            conexion=nueva.getConnection();
            this.setTitle("Servix");
        } catch (UnsupportedLookAndFeelException ex) {
            System.getLogger(JFrameServix.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFielduser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldContransena = new javax.swing.JPasswordField();
        jButtonCrearCuenta = new javax.swing.JButton();
        jButtonIniciarSesion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 174, 188));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoSinFondo.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new java.awt.GridBagConstraints());

        jPanel3.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        jLabel3.setText("Usuario");
        jPanel3.add(jLabel3);
        jPanel3.add(jTextFielduser);

        jLabel4.setText("Contraseña");
        jPanel3.add(jLabel4);
        jPanel3.add(jPasswordFieldContransena);

        jButtonCrearCuenta.setBackground(new java.awt.Color(19, 118, 148));
        jButtonCrearCuenta.setForeground(new java.awt.Color(219, 219, 255));
        jButtonCrearCuenta.setText("Crear cuenta");
        jButtonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCuentaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCrearCuenta);

        jButtonIniciarSesion.setBackground(new java.awt.Color(19, 118, 148));
        jButtonIniciarSesion.setForeground(new java.awt.Color(219, 219, 255));
        jButtonIniciarSesion.setText("Iniciar sesion");
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonIniciarSesion);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INICIAR SESION");

        jLabel1.setText("Héctor Valdes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCuentaActionPerformed
        JDialogAltaUsuario jdac= new JDialogAltaUsuario("cliente", 0, this, true, false);
        jdac.setVisible(true);
    }//GEN-LAST:event_jButtonCrearCuentaActionPerformed

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        char[] contrasena = jPasswordFieldContransena.getPassword();
        String stringContrasena = new String(contrasena);
        if(comprobarDatos(jTextFielduser.getText(), stringContrasena)){
            if(rol.toLowerCase().equals("cliente")){
                this.setVisible(false);
                JDialogInterfazClientes jdic  = new JDialogInterfazClientes(this, true, id);
                jdic.setVisible(true);
                
            }else{
                if(comprobarInicioSesion(jTextFielduser.getText())==false){
                    JDialogCambiarContrasena jdcc = new JDialogCambiarContrasena(jTextFielduser.getText(), this, true);
                    jdcc.setVisible(true);
                }else{
                    if(rol.toLowerCase().equals("empleado")){
                        this.setVisible(false);
                        JTableInterfazEmpleado jdie = new JTableInterfazEmpleado("empleado", this, true);
                        jdie.setVisible(true);
                        this.dispose();
                    }else{
                        if(rol.toLowerCase().equals("encargado")){
                            this.setVisible(false);
                            JDialogInterfazEncargado jdie  = new JDialogInterfazEncargado(this, true);
                            jdie.setVisible(true);
                        }
                    }
                } 
               
            }
        }
    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    private boolean comprobarDatos(String user, String contrasena) {
        boolean correcto=false;
        try {
            if(user.isEmpty() || user.equals("")|| contrasena.isEmpty() || contrasena.equals("")){
                JOptionPane.showConfirmDialog(rootPane,
                                            "Porfavor rellene todos los campos", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
            }else{   
            
                nueva.conectar();
                String sql = "SELECT * FROM Usuario WHERE usuario_login = ?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setString(1, user);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    id = rs.getInt("id");
                    rol = rs.getString("rol");
                    String contrasenaHash = rs.getString("contrasenya_login");
                    if (id != 0 && Seguridad.checkPassword(contrasena, contrasenaHash)) {
                        correcto= true;
                    }
                }else{
                     JOptionPane.showConfirmDialog(rootPane,
                                            "Usuario o contraseña incorrectos", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
                      correcto =  false;
                }

                rs.close();
                ps.close();
            }
        } catch (SQLException ex) {
             System.getLogger(JFrameServix.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
           return correcto;
    } //comprobar datos
    
     public boolean comprobarInicioSesion(String user){
        try {
            nueva.conectar();
            String sql = "SELECT haIniciadoSesion FROM Usuario WHERE usuario_login = ?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, user);
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                if(rs.getBoolean("haIniciadoSesion")==false){
                    return false;
                }
                return true;
            }
        } catch (SQLException ex) {
            System.getLogger(JTableInterfazEmpleado.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        return true;
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameServix().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearCuenta;
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldContransena;
    private javax.swing.JTextField jTextFielduser;
    // End of variables declaration//GEN-END:variables
}
