/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Encargado;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import servix.ConexionBBDD;
import servix.FormatoTablas;
import servix.JFrameServix;
import servix.Reserva;
import servix.mesas.AsignarMesa;


/**
 *
 * @author DAM2ALU11
 */
public class JDialogGestionarReservas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogGestionarReservas.class.getName());

    /**
     * Creates new form JDialogGestionarReservas
     */
    ConexionBBDD nueva;
    Connection conexion;
    DefaultTableModel dtmPendientes;
    DefaultTableModel dtmConfirmadas;
    DefaultTableModel dtmCanceladas;
    ArrayList<Reserva> lista = new ArrayList<>();
    JFrameServix padre;
    
    public JDialogGestionarReservas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        this.setTitle("Servix");
        this.padre = (JFrameServix) parent;
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        dtmPendientes = new DefaultTableModel();
        dtmConfirmadas = new DefaultTableModel();
        dtmCanceladas = new DefaultTableModel();

        dtmPendientes.setColumnIdentifiers(Reserva.getColumnas());
        dtmConfirmadas.setColumnIdentifiers(Reserva.getColumnas());
        dtmCanceladas.setColumnIdentifiers(Reserva.getColumnas());

        jTablePendientes.setModel(dtmPendientes);
        jTableConfirmadas.setModel(dtmConfirmadas);
        jTableCanceladas.setModel(dtmCanceladas);
        cargarDatos();
        aplicarFormato();
        
        if (JFrameServix.hb != null) {
            JFrameServix.hb.enableHelpKey(this.getContentPane(), "ayuda_gestion_reservas", JFrameServix.hs);
        }
    }

    public void cargarDatos(){
        try {
            lista.clear();
            nueva.conectar();

            String sql = "SELECT * FROM Reserva ORDER BY fecha_hora";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            dtmPendientes.setRowCount(0);
            dtmConfirmadas.setRowCount(0);
            dtmCanceladas.setRowCount(0);

            while(rs.next()){
                Reserva r = new Reserva(
                    rs.getInt("id_reserva"),
                    rs.getString("estado_reserva"),
                    rs.getInt("n_comensales"),
                    rs.getObject("fecha_hora", LocalDateTime.class),
                    rs.getInt("id_cliente"),
                    rs.getInt("id_mesa")
                );

                String estado = r.getEstado_reserva().toLowerCase();

                if(estado.equals("pendiente"))
                    dtmPendientes.addRow(r.devuelveFila());
                else if(estado.equals("confirmada"))
                    dtmConfirmadas.addRow(r.devuelveFila());
                else if(estado.equals("cancelada"))
                    dtmCanceladas.addRow(r.devuelveFila());
            }
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelPendientes = new javax.swing.JPanel();
        jButtonConfirmar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePendientes = new javax.swing.JTable();
        jPanelAceptadas = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableConfirmadas = new javax.swing.JTable();
        jButtonInformeConfirmadas = new javax.swing.JButton();
        jPanelRechazadas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCanceladas = new javax.swing.JTable();
        jButtonInformeCanceladas = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButtonConfirmar.setBackground(new java.awt.Color(19, 118, 148));
        jButtonConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonConfirmar.setForeground(new java.awt.Color(219, 219, 255));
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jTablePendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTablePendientes);

        javax.swing.GroupLayout jPanelPendientesLayout = new javax.swing.GroupLayout(jPanelPendientes);
        jPanelPendientes.setLayout(jPanelPendientesLayout);
        jPanelPendientesLayout.setHorizontalGroup(
            jPanelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPendientesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelPendientesLayout.setVerticalGroup(
            jPanelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPendientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConfirmar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Reservas pendientes", jPanelPendientes);

        jTableConfirmadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableConfirmadas);

        jButtonInformeConfirmadas.setBackground(new java.awt.Color(19, 118, 148));
        jButtonInformeConfirmadas.setForeground(new java.awt.Color(219, 219, 255));
        jButtonInformeConfirmadas.setText("Informe");
        jButtonInformeConfirmadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformeConfirmadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAceptadasLayout = new javax.swing.GroupLayout(jPanelAceptadas);
        jPanelAceptadas.setLayout(jPanelAceptadasLayout);
        jPanelAceptadasLayout.setHorizontalGroup(
            jPanelAceptadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAceptadasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelAceptadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInformeConfirmadas, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelAceptadasLayout.setVerticalGroup(
            jPanelAceptadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAceptadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInformeConfirmadas)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Reservas confirmadas", jPanelAceptadas);

        jTableCanceladas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableCanceladas);

        jButtonInformeCanceladas.setBackground(new java.awt.Color(19, 118, 148));
        jButtonInformeCanceladas.setForeground(new java.awt.Color(219, 219, 255));
        jButtonInformeCanceladas.setText("Informe");
        jButtonInformeCanceladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformeCanceladasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRechazadasLayout = new javax.swing.GroupLayout(jPanelRechazadas);
        jPanelRechazadas.setLayout(jPanelRechazadasLayout);
        jPanelRechazadasLayout.setHorizontalGroup(
            jPanelRechazadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRechazadasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelRechazadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonInformeCanceladas, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelRechazadasLayout.setVerticalGroup(
            jPanelRechazadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRechazadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInformeCanceladas)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Reservas rechazadas", jPanelRechazadas);

        jPanel1.add(jTabbedPane, java.awt.BorderLayout.PAGE_START);

        jButtonVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestiona las reservas");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Alba Pallás");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jButtonVolver))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        int fila = jTablePendientes.getSelectedRow();
        
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione la reserva que quiere confirmar.");
            return;
        }
       
        int idReserva = (int) jTablePendientes.getValueAt(fila, 0);
        int n_comensales = (int) jTablePendientes.getValueAt(fila, 2);
        java.time.LocalDateTime ldt = (java.time.LocalDateTime) jTablePendientes.getValueAt(fila, 3);
//      java.sql.Date fecha = (java.sql.Date) jTablePendientes.getValueAt(fila, 4);
//      Time hora = (Time) jTablePendientes.getValueAt(fila, 3);
        
        AsignarMesa am = new AsignarMesa();
        if(am.buscarMesa(idReserva, n_comensales, ldt)){
            try {
                String sql = "UPDATE Reserva SET estado_reserva = 'confirmada' WHERE id_reserva = ?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setInt(1, idReserva);
                ps.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Reserva confirmada.");
                cargarDatos();

            } catch (SQLException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
                javax.swing.JOptionPane.showMessageDialog(this, "Error al confirmar la reserva.");
            }
        } else{
            JOptionPane.showMessageDialog(rootPane, "No hay mesa disponible");
        }
        
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.setVisible(false);
        this.dispose();
        JDialogInterfazEncargado jdie = new JDialogInterfazEncargado(padre, true);
        jdie.setVisible(true);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonInformeCanceladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformeCanceladasActionPerformed
         try{
            String fileJasper = "informes/ReservasCanceladas.jasper";
            Map parameters = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(fileJasper, parameters, nueva.getConnection());
            javax.swing.JDialog visor = new javax.swing.JDialog(this, false); // false hace que no sea modal
            visor.getContentPane().add(new net.sf.jasperreports.swing.JRViewer(print));
            visor.setSize(900, 700);
            visor.setLocationRelativeTo(null);
            visor.setTitle("Visor de Informe");
            visor.setVisible(true);          
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"Se produjo un error al leer el archivo .jasper");
        } 
    }//GEN-LAST:event_jButtonInformeCanceladasActionPerformed

    private void jButtonInformeConfirmadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformeConfirmadasActionPerformed
        // TODO add your handling code here:
        try{
            String fileJasper = "informes/ReservasConfirmadas.jasper";
            Map parameters = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(fileJasper, parameters, nueva.getConnection());
            javax.swing.JDialog visor = new javax.swing.JDialog(this, false); // false hace que no sea modal
            visor.getContentPane().add(new net.sf.jasperreports.swing.JRViewer(print));
            visor.setSize(900, 700);
            visor.setLocationRelativeTo(null);
            visor.setTitle("Visor de Informe");
            visor.setVisible(true);          
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"Se produjo un error al leer el archivo .jasper");
        } 
    }//GEN-LAST:event_jButtonInformeConfirmadasActionPerformed

    public void aplicarFormato(){
        FormatoTablas.FormatoInteger formatoInt = new FormatoTablas.FormatoInteger();
        FormatoTablas.FormatoFecha formatoFecha = new FormatoTablas.FormatoFecha();
        
        jTablePendientes.getColumnModel().getColumn(0).setCellRenderer(formatoInt);
        jTablePendientes.getColumnModel().getColumn(2).setCellRenderer(formatoInt);
        jTablePendientes.getColumnModel().getColumn(3).setCellRenderer(formatoFecha);
        jTablePendientes.getColumnModel().getColumn(4).setCellRenderer(formatoInt);
        jTablePendientes.getColumnModel().getColumn(5).setCellRenderer(formatoInt);
        
        jTableConfirmadas.getColumnModel().getColumn(0).setCellRenderer(formatoInt);
        jTableConfirmadas.getColumnModel().getColumn(2).setCellRenderer(formatoInt);
        jTableConfirmadas.getColumnModel().getColumn(3).setCellRenderer(formatoFecha);
        jTableConfirmadas.getColumnModel().getColumn(4).setCellRenderer(formatoInt);
        jTableConfirmadas.getColumnModel().getColumn(5).setCellRenderer(formatoInt);
        
        jTableCanceladas.getColumnModel().getColumn(0).setCellRenderer(formatoInt);
        jTableCanceladas.getColumnModel().getColumn(2).setCellRenderer(formatoInt);
        jTableCanceladas.getColumnModel().getColumn(3).setCellRenderer(formatoFecha);
        jTableCanceladas.getColumnModel().getColumn(4).setCellRenderer(formatoInt);
        jTableCanceladas.getColumnModel().getColumn(5).setCellRenderer(formatoInt);
        
    }
    public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonInformeCanceladas;
    private javax.swing.JButton jButtonInformeConfirmadas;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAceptadas;
    private javax.swing.JPanel jPanelPendientes;
    private javax.swing.JPanel jPanelRechazadas;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableCanceladas;
    private javax.swing.JTable jTableConfirmadas;
    private javax.swing.JTable jTablePendientes;
    // End of variables declaration//GEN-END:variables
}
