/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Encargado;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import servix.ConexionBBDD;
import servix.JFrameServix;
import servix.Login_CRUD.Empleado.JTableInterfazEmpleado;
import servix.mesas.JTableAdministrarMesas;

/**
 *
 * @author DAM2Alu11
 */
public class JDialogInterfazEncargado extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogInterfazEncargado.class.getName());
    /**
     * Creates new form JDialogInterfazEncargado
     */
    JFrameServix padre;
    ConexionBBDD nueva;
    Connection conexion;
    public JDialogInterfazEncargado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Servix");
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        this.padre = (JFrameServix) parent;
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdministrarEmpleados = new javax.swing.JButton();
        jButtonAdministrarReservas = new javax.swing.JButton();
        jButtonAdministrarMenu = new javax.swing.JButton();
        jButtonVerReservas = new javax.swing.JButton();
        jButtonAdministrarMesas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonCerrarSesion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonInformeClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido/a!!\n");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("¿Qué deseas hacer?");

        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 30, 30));

        jButtonAdministrarEmpleados.setText("Administrar empleados");
        jButtonAdministrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarEmpleadosActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdministrarEmpleados);
        jButtonAdministrarEmpleados.getAccessibleContext().setAccessibleName("jButtonAdministrarEmpleados");

        jButtonAdministrarReservas.setText("Administrar reservas");
        jButtonAdministrarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarReservasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdministrarReservas);
        jButtonAdministrarReservas.getAccessibleContext().setAccessibleName("jButtonAdministrarReservas");

        jButtonAdministrarMenu.setText("Administrar menu");
        jButtonAdministrarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarMenuActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdministrarMenu);

        jButtonVerReservas.setText("Ver reservas del dia");
        jButtonVerReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerReservasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVerReservas);

        jButtonAdministrarMesas.setText("Administrar mesas");
        jButtonAdministrarMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarMesasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdministrarMesas);

        jButtonCerrarSesion.setText("Cerrar Sesion");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jLabel9.setText("Alba Pallas");

        jButtonInformeClientes.setBackground(new java.awt.Color(19, 118, 148));
        jButtonInformeClientes.setForeground(new java.awt.Color(219, 219, 255));
        jButtonInformeClientes.setText("Informe de clientes");
        jButtonInformeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformeClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonInformeClientes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInformeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdministrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarEmpleadosActionPerformed
        this.setVisible(false);
        this.dispose();
        JTableEmpleados jtee = new JTableEmpleados(padre, true);
        jtee.setVisible(true);
    }//GEN-LAST:event_jButtonAdministrarEmpleadosActionPerformed

    private void jButtonVerReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerReservasActionPerformed
        this.setVisible(false);
        this.dispose();
        JTableInterfazEmpleado jtie = new JTableInterfazEmpleado("encargado", padre, true);
        jtie.setVisible(true);
    }//GEN-LAST:event_jButtonVerReservasActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        this.setVisible(false);
        this.dispose();
        JFrameServix jfs = new JFrameServix();
        jfs.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed
                                                  
    private void jButtonAdministrarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarReservasActionPerformed
        this.setVisible(false);
        this.dispose();
        JDialogGestionarReservas jdgr= new JDialogGestionarReservas(padre, true);
        jdgr.setVisible(true);
    }//GEN-LAST:event_jButtonAdministrarReservasActionPerformed

    private void jButtonAdministrarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarMenuActionPerformed
        this.setVisible(false);
        this.dispose();
        JDialogAdministrarMenu jdam = new JDialogAdministrarMenu(padre, true);
        jdam.setVisible(true); 
    }//GEN-LAST:event_jButtonAdministrarMenuActionPerformed

    private void jButtonAdministrarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarMesasActionPerformed
        this.setVisible(false);
        this.dispose();
        JTableAdministrarMesas jtam = new JTableAdministrarMesas(padre, true);
        jtam.setVisible(true);
    }//GEN-LAST:event_jButtonAdministrarMesasActionPerformed

    private void jButtonInformeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformeClientesActionPerformed
        // TODO add your handling code here:
        try{
            String fileJasper = "informes/Clientes.jasper";
            Map parameters = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(fileJasper, parameters, nueva.getConnection());
            javax.swing.JDialog visor = new javax.swing.JDialog(this, false); // false hace que NO sea modal
            visor.getContentPane().add(new net.sf.jasperreports.swing.JRViewer(print));
            visor.setSize(900, 700);
            visor.setLocationRelativeTo(null);
            visor.setTitle("Visor de Informe");
            visor.setVisible(true);
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"Se produjo un error al leer el archivo .jasper");
        } 
    }//GEN-LAST:event_jButtonInformeClientesActionPerformed
    
   public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdministrarEmpleados;
    private javax.swing.JButton jButtonAdministrarMenu;
    private javax.swing.JButton jButtonAdministrarMesas;
    private javax.swing.JButton jButtonAdministrarReservas;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonInformeClientes;
    private javax.swing.JButton jButtonVerReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
