/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Encargado;

import java.awt.Frame;

/**
 *
 * @author DAM2Alu11
 */
public class JDialogInterfazEncargado extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogInterfazEncargado.class.getName());
    Frame padre;
    String user;
    /**
     * Creates new form JDialogInterfazEncargado
     */
    public JDialogInterfazEncargado(java.awt.Dialog parent, boolean modal, String user) {
        super(parent, modal);
        initComponents();
        this.user = user;
    }
    public JDialogInterfazEncargado(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdministrarEmpleados = new javax.swing.JButton();
        jButtonAdministrarReservas = new javax.swing.JButton();
        jButtonAdministrarMenu = new javax.swing.JButton();
        jButtonInterfazEmpleados = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido/a!!\n");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("¿Qué deseas hacer?");

        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 30, 30));

        jButtonAdministrarEmpleados.setText("Administrar empleados");
        jButtonAdministrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarEmpleadosActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdministrarEmpleados);
        jButtonAdministrarEmpleados.getAccessibleContext().setAccessibleName("jButtonAdministrarEmpleados");

        jButtonAdministrarReservas.setText("Administrar reservas");
        jPanel2.add(jButtonAdministrarReservas);
        jButtonAdministrarReservas.getAccessibleContext().setAccessibleName("jButtonAdministrarReservas");

        jButtonAdministrarMenu.setText("Administrar menu");
        jButtonAdministrarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarMenuActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdministrarMenu);

        jButtonInterfazEmpleados.setText("Ver interfaz empleados");
        jButtonInterfazEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInterfazEmpleadosActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonInterfazEmpleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdministrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarEmpleadosActionPerformed
        JTableEmpleados jtee= new JTableEmpleados(padre, true);
        jtee.setVisible(true);
    }//GEN-LAST:event_jButtonAdministrarEmpleadosActionPerformed

    private void jButtonInterfazEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInterfazEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInterfazEmpleadosActionPerformed

    private void jButtonAdministrarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarMenuActionPerformed
        // TODO add your handling code here:
        JDialogAdministrarMenu jdam = new JDialogAdministrarMenu(padre, rootPaneCheckingEnabled);
        jdam.setVisible(true);
    }//GEN-LAST:event_jButtonAdministrarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdministrarEmpleados;
    private javax.swing.JButton jButtonAdministrarMenu;
    private javax.swing.JButton jButtonAdministrarReservas;
    private javax.swing.JButton jButtonInterfazEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
