/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Encargado;

import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.sql.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.parsers.*;
import org.json.*;
import org.w3c.dom.*;
import org.xml.sax.SAXException;
import servix.ConexionBBDD;

/**
 *
 * @author albap
 */
public class JDialogDatosDePrueba extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogDatosDePrueba.class.getName());

    JFileChooser jfc;
    ConexionBBDD nueva;
    Connection conexion;
    public JDialogDatosDePrueba(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); 
        jfc = new JFileChooser();
        
        jFileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos .xml y .json", "xml", "json");
        jFileChooser.addChoosableFileFilter(filtro);
    
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
        if(!JFileChooser.APPROVE_SELECTION.equals(evt.getActionCommand())){this.setVisible(false);}
        // Solo se pueden seleccionar archivos XML y JSON
        File archivo = jFileChooser.getSelectedFile();
        if (archivo == null) return;

        String nombre = archivo.getName().toLowerCase();
        if (nombre.endsWith(".xml")) {
            try {
                importarXML(archivo);
            } catch (ParserConfigurationException | IOException | SAXException | SQLException ex) {
                logger.log(java.util.logging.Level.SEVERE, "Error importando XML", ex);
            }
        } else if (nombre.endsWith(".json")) {
            importarJSON(archivo);
        }
        
    }//GEN-LAST:event_jFileChooserActionPerformed

    private void importarXML(File archivo) throws ParserConfigurationException, IOException, SAXException, SQLException{
        DocumentBuilder db = DocumentBuilderFactory.newInstance().newDocumentBuilder();
        Document d = db.parse(archivo);
        d.getDocumentElement().normalize();
        
        try {
            conexion.setAutoCommit(false);
            NodeList tablas = d.getElementsByTagName("table");

            for (int i = 0; i < tablas.getLength(); i++) {
                Element t = (Element) tablas.item(i);
                String nombreTabla = t.getAttribute("name");

                switch (nombreTabla) {
                    case "Restaurante": {
                        NodeList f = t.getElementsByTagName("Restaurante");
                        try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO Restaurante "
                                + "(id_restaurante, nombre, direccion, telefono, correo, capacidad, apertura, cierre) VALUES (?,?,?,?,?,?,?,?)")) {
                            for (int j = 0; j < f.getLength(); j++) {
                                Element e = (Element) f.item(j);
                                ps.setInt(1, Integer.parseInt(txt(e, "id_restaurante")));
                                ps.setString(2, txt(e, "nombre"));
                                ps.setString(3, txt(e, "direccion"));
                                ps.setString(4, txtOpc(e, "telefono"));
                                ps.setString(5, txtOpc(e, "correo"));
                                ps.setInt(6, Integer.parseInt(txt(e, "capacidad")));
                                ps.setInt(7, Integer.parseInt(txt(e, "apertura")));
                                ps.setInt(8, Integer.parseInt(txt(e, "cierre")));
                                ps.addBatch();
                            }
                            ps.executeBatch();
                        }
                        break;
                    }

                    case "Ingrediente": {
                        NodeList f = t.getElementsByTagName("Ingrediente");
                        try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO Ingrediente (nombre_ingrediente) VALUES (?)")) {
                            for (int j = 0; j < f.getLength(); j++) {
                                Element e = (Element) f.item(j);
                                ps.setString(1, txt(e, "nombre_ingrediente"));
                                ps.addBatch();
                            }
                            ps.executeBatch();
                        }
                        break;
                    }

                    case "Plato": {
                        NodeList f = t.getElementsByTagName("Plato");
                        try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO Plato (id_plato, nombre, precio, categoria, id_restaurante) VALUES (?,?,?,?,?)")) {
                            for (int j = 0; j < f.getLength(); j++) {
                                Element e = (Element) f.item(j);
                                ps.setInt(1, Integer.parseInt(txt(e, "id_plato")));
                                ps.setString(2, txt(e, "nombre"));
                                ps.setBigDecimal(3, new BigDecimal(txt(e, "precio")));
                                ps.setString(4, txt(e, "categoria"));
                                ps.setInt(5, Integer.parseInt(txt(e, "id_restaurante")));
                                ps.addBatch();
                            }
                            ps.executeBatch();
                        }
                        break;
                    }

                    case "ingrediente_plato": {
                        NodeList f = t.getElementsByTagName("ingrediente_plato");
                        try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO ingrediente_plato (id_plato, nombre_ingrediente) VALUES (?,?)")) {
                            for (int j = 0; j < f.getLength(); j++) {
                                Element e = (Element) f.item(j);
                                ps.setInt(1, Integer.parseInt(txt(e, "id_plato")));
                                ps.setString(2, txt(e, "nombre_ingrediente"));
                                ps.addBatch();
                            }
                            ps.executeBatch();
                        }
                        break;
                    }

                    case "Usuario": {
                        NodeList f = t.getElementsByTagName("Usuario");
                        try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO Usuario "
                                + "(id, nombre, apellido1, apellido2, telefono, correo, usuario_login, contrasenya_login, rol) VALUES (?,?,?,?,?,?,?,?,?)")) {
                            for (int j = 0; j < f.getLength(); j++) {
                                Element e = (Element) f.item(j);
                                ps.setInt(1, Integer.parseInt(txt(e, "id")));
                                ps.setString(2, txt(e, "nombre"));
                                ps.setString(3, txt(e, "apellido1"));
                                ps.setString(4, txtOpc(e, "apellido2"));
                                ps.setString(5, txt(e, "telefono"));
                                ps.setString(6, txt(e, "correo"));
                                ps.setString(7, txt(e, "usuario_login"));
                                ps.setString(8, txt(e, "contrasenya_login"));
                                ps.setString(9, txt(e, "rol"));
                                ps.addBatch();
                            }
                            ps.executeBatch();
                        }
                        break;
                    }

                    case "usuario_restaurante": {
                        NodeList f = t.getElementsByTagName("usuario_restaurante");
                        try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO usuario_restaurante (id_usuario, id_restaurante) VALUES (?,?)")) {
                            for (int j = 0; j < f.getLength(); j++) {
                                Element e = (Element) f.item(j);
                                ps.setInt(1, Integer.parseInt(txt(e, "id_usuario")));
                                ps.setInt(2, Integer.parseInt(txt(e, "id_restaurante")));
                                ps.addBatch();
                            }
                            ps.executeBatch();
                        }
                        break;
                    }

                    case "Mesa": {
                        NodeList f = t.getElementsByTagName("Mesa");
                        try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO Mesa (id_mesa, capacidad, estado, id_restaurante) VALUES (?,?,?,?)")) {
                            for (int j = 0; j < f.getLength(); j++) {
                                Element e = (Element) f.item(j);
                                ps.setInt(1, Integer.parseInt(txt(e, "id_mesa")));
                                ps.setInt(2, Integer.parseInt(txt(e, "capacidad")));
                                ps.setBoolean(3, Boolean.parseBoolean(txt(e, "estado")));
                                ps.setInt(4, Integer.parseInt(txt(e, "id_restaurante")));
                                ps.addBatch();
                            }
                            ps.executeBatch();
                        }
                        break;
                    }

                    case "Reserva": {
                        NodeList f = t.getElementsByTagName("Reserva");
                        try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO Reserva "
                                + "(id_reserva, estado_reserva, n_comensales, fecha_hora, id_cliente, id_mesa, id_restaurante) VALUES (?,?,?,?,?,?,?)")) {
                            for (int j = 0; j < f.getLength(); j++) {
                                Element e = (Element) f.item(j);
                                ps.setInt(1, Integer.parseInt(txt(e, "id_reserva")));
                                ps.setString(2, txt(e, "estado_reserva"));
                                ps.setInt(3, Integer.parseInt(txt(e, "n_comensales")));
                                ps.setTimestamp(4, Timestamp.valueOf(txt(e, "fecha_hora")));
                                ps.setInt(5, Integer.parseInt(txt(e, "id_cliente")));
                                String idMesa = txt(e, "id_mesa");
                                if (idMesa == null || idMesa.equalsIgnoreCase("null")) {
                                    ps.setNull(6, Types.INTEGER);
                                } else {
                                    ps.setInt(6, Integer.parseInt(idMesa));
                                }
                                ps.setInt(7, Integer.parseInt(txt(e, "id_restaurante")));
                                ps.addBatch();
                            }
                            ps.executeBatch();
                        }
                        break;
                    }

                    default:
                        logger.warning("Tabla no reconocida en el XML: " + nombreTabla);
                        break;
                }
            }
            conexion.commit();
            this.setVisible(false);

        } catch (SQLException ex) {
            try { conexion.rollback(); } catch (SQLException rb) { logger.severe("Error en rollback: " + rb.getMessage()); }
            throw new IOException("Error SQL durante la importación XML: " + ex.getMessage(), ex);
        } finally {
            try { conexion.setAutoCommit(true); } catch (SQLException ignored) {}
        } 
    }
    
    private void importarJSON(File archivo) {
        try {
            String con = new String(Files.readAllBytes(archivo.toPath()), "UTF-8");
            JSONObject r  = new JSONObject(con);

            conexion.setAutoCommit(false);

            if (r.has("restaurantes")) {
                JSONArray a = r.getJSONArray("restaurantes");
                try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO Restaurante "
                        + "(id_restaurante, nombre, direccion, telefono, correo, capacidad, apertura, cierre) VALUES (?,?,?,?,?,?,?,?)")) {
                    for (int i = 0; i < a.length(); i++) {
                        JSONObject o = a.getJSONObject(i);
                        ps.setInt(1, o.getInt("id_restaurante"));
                        ps.setString(2, o.getString("nombre"));
                        ps.setString(3, o.getString("direccion"));
                        ps.setString(4, o.optString("telefono", null));
                        ps.setString(5, o.optString("correo", null));
                        ps.setInt(6, o.getInt("capacidad"));
                        ps.setInt(7, o.getInt("apertura"));
                        ps.setInt(8, o.getInt("cierre"));
                        ps.addBatch();
                    }
                    ps.executeBatch();
                }
            }

            if (r.has("ingredientes")) {
                JSONArray a = r.getJSONArray("ingredientes");
                try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO Ingrediente (nombre_ingrediente) VALUES (?)")) {
                    for (int i = 0; i < a.length(); i++) {
                        ps.setString(1, a.getJSONObject(i).getString("nombre_ingrediente"));
                        ps.addBatch();
                    }
                    ps.executeBatch();
                }
            }

            if (r.has("platos")) {
                JSONArray a = r.getJSONArray("platos");
                try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO Plato (id_plato, nombre, precio, categoria, id_restaurante) VALUES (?,?,?,?,?)")) {
                    for (int i = 0; i < a.length(); i++) {
                        JSONObject o = a.getJSONObject(i);
                        ps.setInt(1, o.getInt("id_plato"));
                        ps.setString(2, o.getString("nombre"));
                        ps.setBigDecimal(3, BigDecimal.valueOf(o.getDouble("precio")));
                        ps.setString(4, o.getString("categoria"));
                        ps.setInt(5, o.getInt("id_restaurante"));
                        ps.addBatch();
                    }
                    ps.executeBatch();
                }
            }

            if (r.has("ingredientes_platos")) {
                JSONArray a = r.getJSONArray("ingredientes_platos");
                try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO ingrediente_plato (id_plato, nombre_ingrediente) VALUES (?,?)")) {
                    for (int i = 0; i < a.length(); i++) {
                        JSONObject o = a.getJSONObject(i);
                        ps.setInt(1, o.getInt("id_plato"));
                        ps.setString(2, o.getString("nombre_ingrediente"));
                        ps.addBatch();
                    }
                    ps.executeBatch();
                }
            }

            if (r.has("usuarios")) {
                JSONArray a = r.getJSONArray("usuarios");
                try (PreparedStatement ps = conexion.prepareStatement( "INSERT IGNORE INTO Usuario "
                        + "(id, nombre, apellido1, apellido2, telefono, correo, usuario_login, contrasenya_login, rol) VALUES (?,?,?,?,?,?,?,?,?)")) {
                    for (int i = 0; i < a.length(); i++) {
                        JSONObject o = a.getJSONObject(i);
                        ps.setInt(1, o.getInt("id"));
                        ps.setString(2, o.getString("nombre"));
                        ps.setString(3, o.getString("apellido1"));
                        String ap2 = o.optString("apellido2", null);
                        ps.setString(4, (ap2 != null && !ap2.isEmpty()) ? ap2 : null);
                        ps.setString(5, o.getString("telefono"));
                        ps.setString(6, o.getString("correo"));
                        ps.setString(7, o.getString("usuario_login"));
                        ps.setString(8, o.getString("contrasenya_login"));
                        ps.setString(9, o.getString("rol"));
                        ps.addBatch();
                    }
                    ps.executeBatch();
                }
            }

            if (r.has("usuarios_restaurantes")) {
                JSONArray a = r.getJSONArray("usuarios_restaurantes");
                try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO usuario_restaurante (id_usuario, id_restaurante) VALUES (?,?)")) {
                    for (int i = 0; i < a.length(); i++) {
                        JSONObject o = a.getJSONObject(i);
                        ps.setInt(1, o.getInt("id_usuario"));
                        ps.setInt(2, o.getInt("id_restaurante"));
                        ps.addBatch();
                    }
                    ps.executeBatch();
                }
            }

            if (r.has("mesas")) {
                JSONArray arr = r.getJSONArray("mesas");
                try (PreparedStatement ps = conexion.prepareStatement("INSERT IGNORE INTO Mesa (id_mesa, capacidad, estado, id_restaurante) VALUES (?,?,?,?)")) {
                    for (int i = 0; i < arr.length(); i++) {
                        JSONObject o = arr.getJSONObject(i);
                        ps.setInt(1, o.getInt("id_mesa"));
                        ps.setInt(2, o.getInt("capacidad"));
                        ps.setBoolean(3, o.getBoolean("estado"));
                        ps.setInt(4, o.getInt("id_restaurante"));
                        ps.addBatch();
                    }
                    ps.executeBatch();
                }
            }

            if (r.has("reservas")) {
                JSONArray arr = r.getJSONArray("reservas");
                try (PreparedStatement ps = conexion.prepareStatement( "INSERT IGNORE INTO Reserva "
                        + "(id_reserva, estado_reserva, n_comensales, fecha_hora, id_cliente, id_mesa, id_restaurante) VALUES (?,?,?,?,?,?,?)")) {
                    for (int i = 0; i < arr.length(); i++) {
                        JSONObject o = arr.getJSONObject(i);
                        ps.setInt(1, o.getInt("id_reserva"));
                        ps.setString(2, o.getString("estado_reserva"));
                        ps.setInt(3, o.getInt("n_comensales"));
                        ps.setTimestamp(4, Timestamp.valueOf(o.getString("fecha_hora")));
                        ps.setInt(5, o.getInt("id_cliente"));
                        if (o.isNull("id_mesa")) {
                            ps.setNull(6, Types.INTEGER);
                        } else {
                            ps.setInt(6, o.getInt("id_mesa"));
                        }
                        ps.setInt(7, o.getInt("id_restaurante"));
                        ps.addBatch();
                    }
                    ps.executeBatch();
                }
            }

            conexion.commit();
            this.setVisible(false);

        } catch (Exception ex) {
            try { conexion.rollback(); } 
            catch (SQLException rb) { System.out.println("Error al hacer rollback"); }
            System.getLogger(JDialogDatosDePrueba.class.getName())
                    .log(System.Logger.Level.ERROR, (String) null, ex);
        } finally {
            try { conexion.setAutoCommit(true); } catch (SQLException ignored) {}
        }
    }    
    
    private String txt(Element e, String tag) {
        NodeList nl = e.getElementsByTagName(tag);
        if (nl.getLength() == 0) return null;
        return nl.item(0).getTextContent().trim();
    }

    private String txtOpc(Element e, String tag) {
        String v = txt(e, tag);
        if (v == null || v.equalsIgnoreCase("null") || v.isEmpty()) return null;
        return v;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogDatosDePrueba dialog = new JDialogDatosDePrueba(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser;
    // End of variables declaration//GEN-END:variables
}
