/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Encargado;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servix.ConexionBBDD;
import servix.JFrameServix;
import servix.Reserva;
import servix.mesas.AsignarMesa;

/**
 *
 * @author DAM2ALU11
 */
public class JDialogGestionarReservas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogGestionarReservas.class.getName());

    /**
     * Creates new form JDialogGestionarReservas
     */
    JFrameServix padre;
    ConexionBBDD nueva;
    Connection conexion;
    DefaultTableModel dtmPendientes;
    DefaultTableModel dtmConfirmadas;
    DefaultTableModel dtmCanceladas;
    ArrayList<Reserva> lista = new ArrayList<>();
    String user;
    public JDialogGestionarReservas(java.awt.Frame parent, boolean modal, String user) {
        super(parent, modal);
        initComponents();
        this.user= user;
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        dtmPendientes = new DefaultTableModel();
        dtmConfirmadas = new DefaultTableModel();
        dtmCanceladas = new DefaultTableModel();

        dtmPendientes.setColumnIdentifiers(Reserva.getColumnas());
        dtmConfirmadas.setColumnIdentifiers(Reserva.getColumnas());
        dtmCanceladas.setColumnIdentifiers(Reserva.getColumnas());

        jTablePendientes.setModel(dtmPendientes);
        jTableConfirmadas.setModel(dtmConfirmadas);
        jTableCanceladas.setModel(dtmCanceladas);
        cargarDatos();
    }

    public void cargarDatos(){
        try {
            lista.clear();
            nueva.conectar();

            String sql = "SELECT * FROM Reserva";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            dtmPendientes.setRowCount(0);
            dtmConfirmadas.setRowCount(0);
            dtmCanceladas.setRowCount(0);

            while(rs.next()){
                Reserva r = new Reserva(
                    rs.getInt("id_reserva"),
                    rs.getString("estado_reserva"),
                    rs.getInt("n_comensales"),
                    rs.getTime("hora"),
                    rs.getDate("fecha"),
                    rs.getInt("id_cliente"),
                    rs.getInt("id_mesa")
                );

                String estado = r.getEstado_reserva().toLowerCase();

                if(estado.equals("pendiente"))
                    dtmPendientes.addRow(r.devuelveFila());
                else if(estado.equals("confirmada"))
                    dtmConfirmadas.addRow(r.devuelveFila());
                else if(estado.equals("cancelada"))
                    dtmCanceladas.addRow(r.devuelveFila());
            }
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelPendientes = new javax.swing.JPanel();
        jButtonConfirmar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePendientes = new javax.swing.JTable();
        jPanelAceptadas = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableConfirmadas = new javax.swing.JTable();
        jPanelRechazadas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCanceladas = new javax.swing.JTable();
        jButtonVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jTablePendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTablePendientes);

        javax.swing.GroupLayout jPanelPendientesLayout = new javax.swing.GroupLayout(jPanelPendientes);
        jPanelPendientes.setLayout(jPanelPendientesLayout);
        jPanelPendientesLayout.setHorizontalGroup(
            jPanelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPendientesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelPendientesLayout.setVerticalGroup(
            jPanelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPendientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConfirmar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Reservas pendientes", jPanelPendientes);

        jTableConfirmadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableConfirmadas);

        javax.swing.GroupLayout jPanelAceptadasLayout = new javax.swing.GroupLayout(jPanelAceptadas);
        jPanelAceptadas.setLayout(jPanelAceptadasLayout);
        jPanelAceptadasLayout.setHorizontalGroup(
            jPanelAceptadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAceptadasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelAceptadasLayout.setVerticalGroup(
            jPanelAceptadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAceptadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Reservas confirmadas", jPanelAceptadas);

        jTableCanceladas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableCanceladas);

        javax.swing.GroupLayout jPanelRechazadasLayout = new javax.swing.GroupLayout(jPanelRechazadas);
        jPanelRechazadas.setLayout(jPanelRechazadasLayout);
        jPanelRechazadasLayout.setHorizontalGroup(
            jPanelRechazadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRechazadasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelRechazadasLayout.setVerticalGroup(
            jPanelRechazadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRechazadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Reservas rechazadas", jPanelRechazadas);

        jPanel1.add(jTabbedPane, java.awt.BorderLayout.PAGE_START);

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestiona las reservas");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolver)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVolver)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        int fila = jTablePendientes.getSelectedRow();
        
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione la reserva que quiere confirmar.");
            return;
        }
       
        int idReserva = (int) jTablePendientes.getValueAt(fila, 0);
        int n_comensales = (int) jTablePendientes.getValueAt(fila, 2);
        java.sql.Date fecha = (java.sql.Date) jTablePendientes.getValueAt(fila, 4);
        Time hora = (Time) jTablePendientes.getValueAt(fila, 3);
        
        AsignarMesa am = new AsignarMesa();
        if(am.buscarMesa(idReserva, n_comensales, fecha, hora)){
            try {
                String sql = "UPDATE Reserva SET estado_reserva = 'confirmada' WHERE id_reserva = ?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setInt(1, idReserva);
                ps.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Reserva confirmada.");
                cargarDatos();

            } catch (SQLException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
                javax.swing.JOptionPane.showMessageDialog(this, "Error al confirmar la reserva.");
            }
        } else{
            JOptionPane.showMessageDialog(rootPane, "No ha mesa disponible");
        }
        
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.setVisible(false);
        this.dispose();
        JDialogInterfazEncargado jdie = new JDialogInterfazEncargado(this, true, user);
        jdie.setVisible(true);
    }//GEN-LAST:event_jButtonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAceptadas;
    private javax.swing.JPanel jPanelPendientes;
    private javax.swing.JPanel jPanelRechazadas;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableCanceladas;
    private javax.swing.JTable jTableConfirmadas;
    private javax.swing.JTable jTablePendientes;
    // End of variables declaration//GEN-END:variables
}
