 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Encargado;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import servix.ConexionBBDD;
import servix.JFrameServix;
import servix.Login_CRUD.Clientes.JDialogInterfazClientes;
import servix.Login_CRUD.Usuario.JDialogAltaUsuario;

/**
 *
 * @author valde
 */
public class JDialogAdministrarMenu extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAdministrarMenu.class.getName());

    /**
     * Creates new form JDialogAdministrarMenu
     */
    
    DefaultTableModel dtm;
    ConexionBBDD nueva = null;
    Connection conexion = null;
    JFrameServix padre;
    int restaurante, id;
    
    public JDialogAdministrarMenu(java.awt.Frame parent, boolean modal, int restaurante, int id) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); //Hace que la ventana este centrada en la pantalla
        this.setTitle("Servix");
        
        this.padre = (JFrameServix) parent;
        this.restaurante = restaurante;
        this.id = id;
        
        //Añade el logo a la ventana
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        
        //Conexion a base de datos
        this.nueva = new ConexionBBDD();
        this.conexion = nueva.getConnection();
        
        this.dtm = new DefaultTableModel();
        jTableMenu.setModel(dtm);
        jTableMenu.setDefaultEditor(Object.class, null);// Desactiva edicion de las tablas
        cargaTablaMenu();
        
        // Mover el JFrame fuera de la pantalla para que no sea visible aunque se restaure
        padre.setLocation(-10000, -10000);
        padre.setSize(0, 0);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                JFrameServix.cerrarYReiniciar(JDialogAdministrarMenu.this, padre);
            }
        });
        
        atajosTeclado();
        
    }
    private void atajosTeclado(){
        //Ayuda
        if (JFrameServix.hb != null) {
            // Referencia para que al pulsar F1 salga en la pagina correspondiente de ayuda
            JFrameServix.hb.enableHelpKey(this.getContentPane(), "ayuda_admin_menu", JFrameServix.hs);
        }
        
        // Escape - Cerrar
        getRootPane().registerKeyboardAction(
            e -> jButtonVolver.doClick(),
            KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0),
            javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
        );
        
        // Ctrl+G - Guardar/Validar
        getRootPane().registerKeyboardAction(
            e -> jButtonValidar.doClick(),
            KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK),
            javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
        );
        
        // Supr - Eliminar
        getRootPane().registerKeyboardAction(
            e -> jButtonEliminarPlato.doClick(),
            KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0),
            javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
        );
        
        // Ctrl+E - Editar
        getRootPane().registerKeyboardAction(
            e -> jButtonEditarPlato.doClick(),
            KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK),
            javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
        );
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelVerPlatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMenu = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonEditarPlato = new javax.swing.JButton();
        jButtonEliminarPlato = new javax.swing.JButton();
        jButtonVolver1 = new javax.swing.JButton();
        jPanelNuevoPlato = new javax.swing.JPanel();
        jPanelNuevoPlato1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombrePlato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerPrecio = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jButtonValidar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Héctor Valdés");

        jTableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMenu);

        jButtonEditarPlato.setText("Editar");
        jButtonEditarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarPlatoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditarPlato);

        jButtonEliminarPlato.setText("Eliminar");
        jButtonEliminarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPlatoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminarPlato);

        jButtonVolver1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVolver1.setText("Volver");
        jButtonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVerPlatosLayout = new javax.swing.GroupLayout(jPanelVerPlatos);
        jPanelVerPlatos.setLayout(jPanelVerPlatosLayout);
        jPanelVerPlatosLayout.setHorizontalGroup(
            jPanelVerPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerPlatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVerPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelVerPlatosLayout.createSequentialGroup()
                        .addComponent(jButtonVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 205, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelVerPlatosLayout.setVerticalGroup(
            jPanelVerPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerPlatosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVerPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVolver1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Platos", jPanelVerPlatos);

        jPanelNuevoPlato1.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        jLabel1.setText("Nombre");
        jPanelNuevoPlato1.add(jLabel1);
        jPanelNuevoPlato1.add(jTextFieldNombrePlato);

        jLabel2.setText("Precio");
        jPanelNuevoPlato1.add(jLabel2);

        jSpinnerPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        jSpinnerPrecio.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerPrecio, "0.00"));
        jPanelNuevoPlato1.add(jSpinnerPrecio);

        jLabel3.setText("Categoria");
        jPanelNuevoPlato1.add(jLabel3);

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bebida", "entrante", "primer_plato", "segundo_plato", "postre" }));
        jPanelNuevoPlato1.add(jComboBoxCategoria);

        jButtonValidar.setBackground(new java.awt.Color(19, 118, 148));
        jButtonValidar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonValidar.setForeground(new java.awt.Color(219, 219, 255));
        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        jButtonVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNuevoPlatoLayout = new javax.swing.GroupLayout(jPanelNuevoPlato);
        jPanelNuevoPlato.setLayout(jPanelNuevoPlatoLayout);
        jPanelNuevoPlatoLayout.setHorizontalGroup(
            jPanelNuevoPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNuevoPlatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNuevoPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelNuevoPlato1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addGroup(jPanelNuevoPlatoLayout.createSequentialGroup()
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelNuevoPlatoLayout.setVerticalGroup(
            jPanelNuevoPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNuevoPlatoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanelNuevoPlato1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanelNuevoPlatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nuevo", jPanelNuevoPlato);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarPlatoActionPerformed
        // TODO add your handling code here:
        if(jTableMenu.getSelectedRowCount() == 1){

            int fila = jTableMenu.getSelectedRow();

            String nombre = jTableMenu.getValueAt(fila, 0).toString();
            double precio = Double.parseDouble(jTableMenu.getValueAt(fila, 1).toString());
            String cadenaCategoria = jTableMenu.getValueAt(fila, 2).toString();

            this.dispose();
            JDialogEditarPlato jdep = new JDialogEditarPlato(nombre, precio, cadenaCategoria, padre, true, restaurante, id);
            jdep.setVisible(true);

            recargarTabla();
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione un plato para editar.");
        }

    }//GEN-LAST:event_jButtonEditarPlatoActionPerformed

    private void jButtonEliminarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPlatoActionPerformed
        // TODO add your handling code here:
        if(jTableMenu.getSelectedRowCount()==1){
            int fila = jTableMenu.getSelectedRow();
            String nombre_plato = (String) jTableMenu.getValueAt(fila, 0);
            try {
                conexion.setAutoCommit(false);
                String sql = "DELETE FROM plato WHERE nombre=? AND id_restaurante = ?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setString(1, nombre_plato);
                ps.setInt(2, restaurante);
                int opcion = JOptionPane.showConfirmDialog(
                    null,
                    "¿Estas seguro de eliminar el plato seleccionado?",
                    "Confirmación",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE
                );
                if (opcion == JOptionPane.OK_OPTION) {
                    int resultado=ps.executeUpdate();
                    if(resultado==1){
                        conexion.commit();
                        dtm.removeRow(fila);
                    }
                }
            } catch (SQLException ex) {
                try {
                    conexion.rollback();
                } catch (SQLException ex1) {
                    java.util.logging.Logger.getLogger(JDialogAdministrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex1);
                }
                java.util.logging.Logger.getLogger(JDialogAdministrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione un plato para eliminar.");
        }

    }//GEN-LAST:event_jButtonEliminarPlatoActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        String categoria = (String) jComboBoxCategoria.getSelectedItem();
        String nombrePlato = jTextFieldNombrePlato.getText();
        double precio = (Double) jSpinnerPrecio.getValue();

        if(categoria.isEmpty() || nombrePlato.isEmpty() || precio<=0){
            JOptionPane.showConfirmDialog(rootPane,
                "Rellena todos los campos",
                "Error",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.ERROR_MESSAGE);
        }
        else if(precio<=0){
            JOptionPane.showConfirmDialog(rootPane,
                "El precio no puede ser 0",
                "Error",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                /*
                if      (categoria.equalsIgnoreCase("bebida"))        categoria = "Bebida";
                else if (categoria.equalsIgnoreCase("entrante"))      categoria = "Entrante";
                else if (categoria.equalsIgnoreCase("primer_plato"))  categoria = "Plato principal";
                else if (categoria.equalsIgnoreCase("segundo_plato")) categoria = "Segundo Plato";
                else if (categoria.equalsIgnoreCase("postre"))        categoria = "Postre";
                */
                if(existePlato(nombrePlato, restaurante)){
                    JOptionPane.showConfirmDialog(rootPane,
                        "Ya existe un plato con el nombre \"" + nombrePlato + "\"",
                        "Error",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.ERROR_MESSAGE);
                }
                else{
                    PreparedStatement ps = conexion.prepareStatement("INSERT INTO plato"
                        + "(nombre, precio, categoria, id_restaurante)"
                        + " VALUES (?, ?, ?, ?)");

                    ps.setString(1, nombrePlato);
                    ps.setDouble(2, precio);
                    ps.setString(3, categoria);
                    ps.setInt(4, restaurante);

                    int filas = ps.executeUpdate();
                    if(filas==1){
                        JOptionPane.showConfirmDialog(rootPane,
                            "Plato registrado",
                            "",
                            JOptionPane.OK_CANCEL_OPTION,
                            JOptionPane.INFORMATION_MESSAGE);
                        recargarTabla();
                        jTextFieldNombrePlato.setText("");
                        jSpinnerPrecio.setValue(0);
                    }
                    else{
                        JOptionPane.showConfirmDialog(rootPane,
                            "Ha habido un error",
                            "Error",
                            JOptionPane.OK_CANCEL_OPTION,
                            JOptionPane.ERROR_MESSAGE);
                    }
                }

            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(JDialogAdministrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        JDialogInterfazEncargado jdie = new JDialogInterfazEncargado(padre, true, id);
        jdie.setVisible(true); 
    }//GEN-LAST:event_jButtonVolverActionPerformed
    
    public boolean existePlato(String nombrePlato, int id_restaurante){
        // Comprobar si ya existe un plato con el mismo nombre en este restaurante
        boolean existe= false;
        
        try {    
            PreparedStatement ps = conexion.prepareStatement(
                "SELECT COUNT(*) FROM plato WHERE nombre = ? AND id_restaurante = ?"
            );
            ps.setString(1, nombrePlato);
            ps.setInt(2, restaurante);
            ResultSet rs = ps.executeQuery();

            if (rs.next() && rs.getInt(1) > 0) {
                // Ya existe un plato con ese nombre
                existe=true;
            }
            rs.close();
            ps.close();
                        
            
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(JDialogAdministrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return existe;
    }
    public void recargarTabla() {
        dtm.setRowCount(0);
        dtm.setColumnCount(0);
        cargaTablaMenu();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarPlato;
    private javax.swing.JButton jButtonEliminarPlato;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JButton jButtonVolver1;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelNuevoPlato;
    private javax.swing.JPanel jPanelNuevoPlato1;
    private javax.swing.JPanel jPanelVerPlatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerPrecio;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableMenu;
    private javax.swing.JTextField jTextFieldNombrePlato;
    // End of variables declaration//GEN-END:variables
    public void cargaTablaMenu(){
        try {
            PreparedStatement ps = conexion.prepareStatement(
                    "SELECT nombre AS Nombre, precio AS Precio, categoria AS Categoria FROM plato WHERE id_restaurante = ? ORDER BY categoria"
            );
            System.out.println(restaurante);
            System.out.println(id);
            ps.setInt(1, restaurante);
            nueva.selectSQL(ps, dtm);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(JDialogAdministrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }
}

