/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Encargado;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servix.ConexionBBDD;
import servix.Login_CRUD.Clientes.JDialogInterfazClientes;

/**
 *
 * @author valde
 */
public class JDialogAdministrarMenu extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAdministrarMenu.class.getName());

    /**
     * Creates new form JDialogAdministrarMenu
     */
    
    DefaultTableModel dtm;
    ConexionBBDD nueva = null;
    Connection conexion = null;
    
    public JDialogAdministrarMenu() {
        initComponents();
        this.setTitle("Servix");
        this.nueva = new ConexionBBDD();
        this.conexion = nueva.getConnection();
        this.dtm = new DefaultTableModel();
        jTableMenu.setModel(dtm);
        cargaTablaMenu();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPadre = new javax.swing.JPanel();
        jPanelNuevoPlato = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombrePlato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerPrecio = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonValidar = new javax.swing.JButton();
        jPanelVerPlatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMenu = new javax.swing.JTable();
        jPanelModificar = new javax.swing.JPanel();
        jButtonEditarPlato = new javax.swing.JButton();
        jButtonEliminarPlato = new javax.swing.JButton();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonNuevoPlato = new javax.swing.JButton();
        jButtonVerPlatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPadre.setLayout(new java.awt.CardLayout());

        jPanelNuevoPlato.setLayout(new java.awt.GridLayout(5, 0));

        jLabel1.setText("Nombre");
        jPanelNuevoPlato.add(jLabel1);
        jPanelNuevoPlato.add(jTextFieldNombrePlato);

        jLabel2.setText("Precio");
        jPanelNuevoPlato.add(jLabel2);
        jPanelNuevoPlato.add(jSpinnerPrecio);

        jLabel3.setText("Categoria");
        jPanelNuevoPlato.add(jLabel3);

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bebida", "entrante", "primer_plato", "segundo_plato", "postre" }));
        jPanelNuevoPlato.add(jComboBoxCategoria);
        jPanelNuevoPlato.add(jLabel4);
        jPanelNuevoPlato.add(jLabel5);
        jPanelNuevoPlato.add(jLabel6);

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });
        jPanelNuevoPlato.add(jButtonValidar);

        jPanelPadre.add(jPanelNuevoPlato, "card2");

        jTableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMenu);

        jButtonEditarPlato.setText("Editar");
        jButtonEditarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarPlatoActionPerformed(evt);
            }
        });
        jPanelModificar.add(jButtonEditarPlato);

        jButtonEliminarPlato.setText("Eliminar");
        jButtonEliminarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPlatoActionPerformed(evt);
            }
        });
        jPanelModificar.add(jButtonEliminarPlato);

        javax.swing.GroupLayout jPanelVerPlatosLayout = new javax.swing.GroupLayout(jPanelVerPlatos);
        jPanelVerPlatos.setLayout(jPanelVerPlatosLayout);
        jPanelVerPlatosLayout.setHorizontalGroup(
            jPanelVerPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerPlatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelVerPlatosLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanelVerPlatosLayout.setVerticalGroup(
            jPanelVerPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerPlatosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        jPanelPadre.add(jPanelVerPlatos, "card3");

        jButtonNuevoPlato.setText("Nuevo plato");
        jButtonNuevoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPanel(evt);
            }
        });
        jPanelOpciones.add(jButtonNuevoPlato);

        jButtonVerPlatos.setText("Ver platos");
        jButtonVerPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPanel(evt);
            }
        });
        jPanelOpciones.add(jButtonVerPlatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPadre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPanel
        // TODO add your handling code here:
        JButton jbutton = (JButton) evt.getSource();
        jPanelPadre.removeAll();
        if (jbutton == jButtonVerPlatos) {
            jPanelPadre.add(jPanelVerPlatos);
        } else if (jbutton == jButtonNuevoPlato) {
            jPanelPadre.add(jPanelNuevoPlato);
        }
        
        jPanelPadre.repaint();
        jPanelPadre.revalidate();
    }//GEN-LAST:event_actualizarPanel

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        String categoria = (String) jComboBoxCategoria.getSelectedItem();
        String nombrePlato = jTextFieldNombrePlato.getText();
        int precio = (int) jSpinnerPrecio.getValue();

        if(categoria.isEmpty() || nombrePlato.isEmpty() || precio<=0){
            JOptionPane.showConfirmDialog(rootPane,
                                            "Rellena todos los campos", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                PreparedStatement ps = conexion.prepareStatement("INSERT INTO plato"
                        + "(nombre, precio, categoria)"
                        + " VALUES (?, ?, ?)");
                
                ps.setString(1, nombrePlato);
                ps.setDouble(2, precio);
                ps.setString(3, categoria);

                int filas = ps.executeUpdate();
                if(filas==1){
                   JOptionPane.showConfirmDialog(rootPane,
                                                "Plato registrado", 
                                                "", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.INFORMATION_MESSAGE);
                   recargarTabla();
                }
                else{
                    JOptionPane.showConfirmDialog(rootPane,
                                                "Ha habido un error", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonEditarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarPlatoActionPerformed
        // TODO add your handling code here:
        if(jTableMenu.getSelectedRowCount() == 1){
            
            int fila = jTableMenu.getSelectedRow();

           
            String nombre = jTableMenu.getValueAt(fila, 0).toString();

            JDialogEditarPlato jdep = new JDialogEditarPlato(nombre);
            jdep.setVisible(true);

            recargarTabla();
        
        }
        
    }//GEN-LAST:event_jButtonEditarPlatoActionPerformed

    private void jButtonEliminarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPlatoActionPerformed
        // TODO add your handling code here:
         if(jTableMenu.getSelectedRowCount()==1){
            int fila = jTableMenu.getSelectedRow();
            String nombre_plato = (String) jTableMenu.getValueAt(fila, 0);
             try {
                conexion.setAutoCommit(false);
                String sql = "DELETE FROM plato WHERE nombre=?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setString(1, nombre_plato);
                int opcion = JOptionPane.showConfirmDialog(
                                                null,
                                                "¿Estas seguro de anular la reserva seleccionada?",
                                                "Confirmación",
                                                JOptionPane.OK_CANCEL_OPTION,
                                                JOptionPane.QUESTION_MESSAGE
                );
                if (opcion == JOptionPane.OK_OPTION) {
                    int resultado=ps.executeUpdate();
                    if(resultado==1){
                        conexion.commit();
                        dtm.removeRow(fila);
                    }
                }
            } catch (SQLException ex) {
                try {
                    conexion.rollback();
                } catch (SQLException ex1) {
                    System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex1);
                }
                System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        
    }//GEN-LAST:event_jButtonEliminarPlatoActionPerformed
    
    public void recargarTabla() {
        dtm.setRowCount(0);
        dtm.setColumnCount(0);
        cargaTablaMenu();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarPlato;
    private javax.swing.JButton jButtonEliminarPlato;
    private javax.swing.JButton jButtonNuevoPlato;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JButton jButtonVerPlatos;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelModificar;
    private javax.swing.JPanel jPanelNuevoPlato;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPadre;
    private javax.swing.JPanel jPanelVerPlatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerPrecio;
    private javax.swing.JTable jTableMenu;
    private javax.swing.JTextField jTextFieldNombrePlato;
    // End of variables declaration//GEN-END:variables
    public void cargaTablaMenu(){
        try {
            PreparedStatement ps = conexion.prepareStatement(
                    "SELECT nombre AS Nombre, precio AS Precio, categoria AS Categoria FROM plato ORDER BY categoria"
            );
            nueva.selectSQL(ps, dtm);
        } catch (SQLException ex) {
            System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JDialogAdministrarMenu().setVisible(true));
    }
}

