/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Encargado;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servix.ConexionBBDD;
import servix.Empleado;
import servix.Login_CRUD.empleados.JDialogAltaEmpleados;
import servix.Login_CRUD.empleados.JDialogBajaEmpleados;
import servix.Login_CRUD.empleados.JDialogEditarEmpleados;

/**
 *
 * @author DAM2Alu11
 */
public class JTableEmpleados extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JTableEmpleados.class.getName());

    /**
     * Creates new form JDialogEditarEmpleados
     */
    
    Frame padre;
    ConexionBBDD nueva;
    Connection conexion;
    DefaultTableModel dtm;
    ArrayList<Empleado> lista = new ArrayList<>();
    ArrayList<Empleado> seleccionados = new ArrayList<>();
    
    public JTableEmpleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        dtm= new DefaultTableModel();
        jTableEmpleados.setModel(dtm);
        dtm.setColumnIdentifiers(Empleado.getColumnas());
        cargarEmpleados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonAltaEmpleado = new javax.swing.JButton();
        jButtonBajaEmpleado = new javax.swing.JButton();
        jButtonEditarEmpleado = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);

        jButtonAltaEmpleado.setText("Añadir");
        jButtonAltaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAltaEmpleado);

        jButtonBajaEmpleado.setText("Eliminar");
        jButtonBajaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBajaEmpleado);

        jButtonEditarEmpleado.setText("Editar");
        jButtonEditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditarEmpleado);

        jButtonCancelar.setText("Cancelar");
        jPanel1.add(jButtonCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarEmpleadoActionPerformed
        JDialogEditarEmpleados jdee= new JDialogEditarEmpleados(padre, true);
        jdee.setVisible(true);
        recargarTabla();
    }//GEN-LAST:event_jButtonEditarEmpleadoActionPerformed

    private void jButtonAltaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaEmpleadoActionPerformed
        JDialogAltaEmpleados jdae = new JDialogAltaEmpleados(padre, true);
        jdae.setVisible(true);
        recargarTabla();
    }//GEN-LAST:event_jButtonAltaEmpleadoActionPerformed

    private void jButtonBajaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaEmpleadoActionPerformed
        int fila = jTableEmpleados.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showConfirmDialog(rootPane,
                                            "Debe seleccionar una linea para eliminar" , 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.QUESTION_MESSAGE);
            return;
        }

        // Obtener ID de la fila seleccionada
        int id = (int) dtm.getValueAt(fila, 0);

        JDialogBajaEmpleados jdbe = new JDialogBajaEmpleados(padre, true, id);
        jdbe.setVisible(true);
        recargarTabla();
    }//GEN-LAST:event_jButtonBajaEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JTableEmpleados dialog = new JTableEmpleados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void cargarEmpleados(){
        try{
           
            nueva.conectar();
            String sql = "SELECT * FROM Camarero";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                // Crea un empleado con los datos del ResultSet
                Empleado emp = new Empleado(
                    rs.getInt("id_camarero"),
                    rs.getString("nombre"),
                    rs.getString("apellido1"),
                    rs.getString("apellido2"),
                    rs.getString("telefono"),
                    rs.getString("usuario_login"),
                    rs.getString("contrasenya_login")
                );

                lista.add(emp);
            }

            for (int i = 0; i < lista.size(); i++) {
                    dtm.addRow(lista.get(i).devuelveFila());
                }
        } catch (SQLException ex) {
            System.getLogger(JTableEmpleados.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
                   
    }
    
    public void empleadosSeleccionados(){
         if(jTableEmpleados.getSelectedRowCount()>0){
            int[] seleccionados = jTableEmpleados.getSelectedRows();
            for (int i = jTableEmpleados.getSelectedRowCount()-1; i >= 0; i--) {
                dtm.removeRow(seleccionados[i]);
            }
        }
    }
    public void recargarTabla() {
    dtm.setRowCount(0); // limpia la tabla
    cargarEmpleados();        // vuelve a cargar empleados
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltaEmpleado;
    private javax.swing.JButton jButtonBajaEmpleado;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditarEmpleado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
}
