/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Encargado;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.awt.KeyboardFocusManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import servix.ConexionBBDD;
import servix.FormatoTablas;
import servix.JFrameServix;
import servix.Login_CRUD.Usuario.EliminarEmpleados;
import servix.Login_CRUD.Usuario.JDialogAltaUsuario;
import servix.Login_CRUD.Usuario.Usuario;

/**
 *
 * @author DAM2Alu11
 */
public class JTableEmpleados extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JTableEmpleados.class.getName());

    /**
     * Creates new form JDialogEditarEmpleados
     */
    
    ConexionBBDD nueva;
    Connection conexion;
    DefaultTableModel dtm;
    ArrayList<Usuario> lista = new ArrayList<>();
    EliminarEmpleados eliminar = new EliminarEmpleados();
    JFrameServix padre;
    
    public JTableEmpleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        this.setTitle("Servix");
        this.padre = (JFrameServix) parent;
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        dtm= new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"ID", "Nombre", "Apellido1", "Apellido2", "Teléfono", "Correo", "Usuario"});
        jTableEmpleados.setModel(dtm);
        cargarEmpleados();
        aplicarFormato();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonAltaEmpleado = new javax.swing.JButton();
        jButtonBajaEmpleado = new javax.swing.JButton();
        jButtonEditarEmpleado = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);

        jButtonAltaEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAltaEmpleado.setText("Añadir");
        jButtonAltaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAltaEmpleado);

        jButtonBajaEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBajaEmpleado.setText("Eliminar");
        jButtonBajaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBajaEmpleado);

        jButtonEditarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEditarEmpleado.setText("Editar");
        jButtonEditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditarEmpleado);

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCancelar.setText("Volver");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar);

        jLabel1.setText("Alba Pallas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarEmpleadoActionPerformed
        int fila = jTableEmpleados.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado para editar.");
            return;
        }

        int id = Integer.parseInt(dtm.getValueAt(fila, 0).toString());

        JDialogAltaUsuario jdau = new JDialogAltaUsuario("empleado", id, padre, true, true);
        jdau.setVisible(true);
        recargarTabla();
        
        if (JFrameServix.hb != null) {
            JFrameServix.hb.enableHelpKey(this.getContentPane(), "ayuda_tabla_empleados", JFrameServix.hs);
        }
    }//GEN-LAST:event_jButtonEditarEmpleadoActionPerformed

    private void jButtonAltaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaEmpleadoActionPerformed
        JDialogAltaUsuario jdau = new JDialogAltaUsuario("empleado", 0, padre, true, false);
        jdau.setVisible(true);
        recargarTabla();
    }//GEN-LAST:event_jButtonAltaEmpleadoActionPerformed

    private void jButtonBajaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaEmpleadoActionPerformed
        int fila = jTableEmpleados.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showConfirmDialog(rootPane,
                                            "Debe seleccionar una linea para eliminar" , 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.QUESTION_MESSAGE);
        }else{    
            eliminar.eliminarEmpleados((String) dtm.getValueAt(fila, 0));
           recargarTabla();
        }

    }//GEN-LAST:event_jButtonBajaEmpleadoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.setVisible(false);
        JDialogInterfazEncargado jdie = new JDialogInterfazEncargado(padre, true);
        jdie.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    public void cargarEmpleados(){
        try{
            lista.clear();
            nueva.conectar();
            String sql = "SELECT * FROM Usuario WHERE rol = ?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, "empleado");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Usuario usr = new Usuario(
                    rs.getInt("id"),
                    rs.getString("nombre"),
                    rs.getString("apellido1"),
                    rs.getString("apellido2"),
                    rs.getString("telefono"),
                    rs.getString("correo"),
                    rs.getString("usuario_login"),
                    rs.getString("contrasenya_login")
                );

                lista.add(usr);
            }

            for(int i=0; i<lista.size(); i++) {
                    dtm.addRow(lista.get(i).devuelveFila());
            }
        } catch (SQLException ex) {
            System.getLogger(JTableEmpleados.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    public void empleadosSeleccionados(){
         if(jTableEmpleados.getSelectedRowCount()>0){
            int[] seleccionados = jTableEmpleados.getSelectedRows();
            for (int i = jTableEmpleados.getSelectedRowCount()-1; i >= 0; i--) {
                dtm.removeRow(seleccionados[i]);
            }
        }
    }
    public void recargarTabla() {
        dtm.setRowCount(0);
        cargarEmpleados();// vuelve a cargar empleados
    }
    
     public void aplicarFormato(){
        FormatoTablas.FormatoInteger formatoInt = new FormatoTablas.FormatoInteger();
      
        jTableEmpleados.getColumnModel().getColumn(0).setCellRenderer(formatoInt);
        jTableEmpleados.getColumnModel().getColumn(4).setCellRenderer(formatoInt);
    }
    
    public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltaEmpleado;
    private javax.swing.JButton jButtonBajaEmpleado;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditarEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
}
