/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.empleados;

import java.sql.Connection;
import javax.swing.JOptionPane;
import servix.ConexionBBDD;
import servix.Seguridad;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import servix.JFrameServix;

/**
 *
 * @author albap
 */
public class JDialogCambiarContrasena extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogCambiarContrasena.class.getName());

    /**
     * Creates new form JDialogCambiarContrasena
     */
    JFrameServix padre;
    ConexionBBDD nueva;
    Connection conexion;
    String user;
    
    public JDialogCambiarContrasena(java.awt.Frame parent, boolean modal, String user) {
        super(parent, modal);
        initComponents();
        this.user=user;
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        jLabel1.setText("Hola " + user + " cambia tu contraseña por favor");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordFieldCtn1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldCtn2 = new javax.swing.JPasswordField();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jLabel2.setText("Introduzca la nueva contraseña");
        jPanel2.add(jLabel2);
        jPanel2.add(jPasswordFieldCtn1);

        jLabel3.setText("Repita la contraseña");
        jPanel2.add(jLabel3);
        jPanel2.add(jPasswordFieldCtn2);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAceptar)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAceptar)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        char[] contrasena = jPasswordFieldCtn1.getPassword();
        char[] contrasena2 = jPasswordFieldCtn2.getPassword();

        String stringContrasena1 = new String(contrasena);
        String stringContrasena2 = new String(contrasena2);
        if (stringContrasena1.isEmpty() ||stringContrasena2.isEmpty()) {
            JOptionPane.showConfirmDialog(rootPane,
                                        "Debes rellenar los dos campos", 
                                        "Error", 
                                        JOptionPane.OK_CANCEL_OPTION, 
                                        JOptionPane.ERROR_MESSAGE);
        }else{
           if(stringContrasena1.equals(stringContrasena2)){ // Se comprueba que las contraseñas sean iguales
             String contrasenaEncriptada = Seguridad.hashPassword(stringContrasena1); 
              try {
                String sql = "UPDATE camarero SET contrasenya_login = ?, haIniciadoSesion= true WHERE usuario_login = ?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setString(1, contrasenaEncriptada);
                ps.setString(2, user);

                ps.executeUpdate();
                JDialogLoginEmpleados jdle= new JDialogLoginEmpleados(padre, true);
                jdle.setVisible(true);
                dispose();
            } catch (SQLException ex) {
                 System.getLogger(JDialogCambiarContrasena.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            }else{
                JOptionPane.showConfirmDialog(rootPane,
                                                     "Las contraseñas no coinciden", 
                                                     "Error", 
                                                     JOptionPane.OK_CANCEL_OPTION, 
                                                     JOptionPane.ERROR_MESSAGE);
            } 
        }
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldCtn1;
    private javax.swing.JPasswordField jPasswordFieldCtn2;
    // End of variables declaration//GEN-END:variables
}
