/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Clientes;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import servix.ConexionBBDD;
import servix.FormatoTablas;
import servix.JFrameServix;
import servix.Login_CRUD.Gerente.CargaCombos;

/**
 *
 * @author DAM2Alu15
 */
public class JDialogInterfazClientes extends javax.swing.JDialog{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogInterfazClientes.class.getName());

    /**
     * Creates new form JDialogInterfazClientes
     */
    //Declaracion de variables
    DefaultTableModel dtm;
    DefaultTableModel dtm2;
    ConexionBBDD nueva;
    Connection conexion;
    int id;
    JFrameServix padre;
    CargaCombos cc;
   
    public JDialogInterfazClientes(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        cc = new CargaCombos();
        cc.cargaComboRestaurantes(jComboBoxRestaurantes);
        this.dtm = new DefaultTableModel();
        this.dtm2 = new DefaultTableModel();
        jTableReservas.setModel(dtm);
        jTableMenu.setModel(dtm2);
        this.id = id;
        this.padre = (JFrameServix) parent;
        
        cargaTablaReservas();
        cargaTablaMenu();
        formatoTabla();
        
        if (JFrameServix.hb != null) {
            JFrameServix.hb.enableHelpKey(this.getContentPane(), "ayuda_clientes", JFrameServix.hs);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPadre = new javax.swing.JPanel();
        jPanelVerReservas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReservas = new javax.swing.JTable();
        jPanelBotonesDeleteUpdate = new javax.swing.JPanel();
        jButtonAnularReserva = new javax.swing.JButton();
        jButtonEditarReserva = new javax.swing.JButton();
        jPanelNuevaReserva = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxRestaurantes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerHora = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNumeroComensales = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonValidar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMenu = new javax.swing.JTable();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonNuevaReserva = new javax.swing.JButton();
        jButtonVerReservas = new javax.swing.JButton();
        jButtonVerMenu = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonBajaCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPadre.setLayout(new java.awt.CardLayout());

        jTableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableReservas);

        jButtonAnularReserva.setText("Anular reserva");
        jButtonAnularReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnularReservaActionPerformed(evt);
            }
        });
        jPanelBotonesDeleteUpdate.add(jButtonAnularReserva);

        jButtonEditarReserva.setText("Editar reserva");
        jButtonEditarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarReservaActionPerformed(evt);
            }
        });
        jPanelBotonesDeleteUpdate.add(jButtonEditarReserva);

        javax.swing.GroupLayout jPanelVerReservasLayout = new javax.swing.GroupLayout(jPanelVerReservas);
        jPanelVerReservas.setLayout(jPanelVerReservasLayout);
        jPanelVerReservasLayout.setHorizontalGroup(
            jPanelVerReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerReservasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelVerReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerReservasLayout.createSequentialGroup()
                        .addComponent(jPanelBotonesDeleteUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerReservasLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelVerReservasLayout.setVerticalGroup(
            jPanelVerReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerReservasLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelBotonesDeleteUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        jPanelPadre.add(jPanelVerReservas, "card2");

        jPanelNuevaReserva.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        jLabel7.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel7.setText("Restaurante");
        jPanelNuevaReserva.add(jLabel7);

        jComboBoxRestaurantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelNuevaReserva.add(jComboBoxRestaurantes);

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel3.setText("Fecha");
        jPanelNuevaReserva.add(jLabel3);

        jDateChooser.setMinSelectableDate(new java.util.Date());
        jPanelNuevaReserva.add(jDateChooser);

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel4.setText("Hora");
        jPanelNuevaReserva.add(jLabel4);

        jSpinnerHora.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerHora.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerHora, "HH:mm"));
        jPanelNuevaReserva.add(jSpinnerHora);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel5.setText("Numero de comensales");
        jPanelNuevaReserva.add(jLabel5);
        jPanelNuevaReserva.add(jTextFieldNumeroComensales);
        jPanelNuevaReserva.add(jLabel1);

        jButtonValidar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonValidar.setText("VALIDAR");
        jButtonValidar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });
        jPanelNuevaReserva.add(jButtonValidar);
        jPanelNuevaReserva.add(jLabel6);

        jPanelPadre.add(jPanelNuevaReserva, "card3");

        jTableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMenu);

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
            .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMenuLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
            .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMenuLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanelPadre.add(jPanelMenu, "card4");

        jButtonNuevaReserva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNuevaReserva.setText("Nueva reserva");
        jButtonNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPanel(evt);
            }
        });
        jPanelOpciones.add(jButtonNuevaReserva);

        jButtonVerReservas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVerReservas.setText("Ver reservas");
        jButtonVerReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPanel(evt);
            }
        });
        jPanelOpciones.add(jButtonVerReservas);

        jButtonVerMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVerMenu.setText("Ver menu");
        jButtonVerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPanel(evt);
            }
        });
        jPanelOpciones.add(jButtonVerMenu);

        jButtonCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCerrarSesion.setText("Cerrar sesion");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jButtonBajaCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBajaCliente.setText("Eliminar cuenta");
        jButtonBajaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Héctor Valdés");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBajaCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCerrarSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanelPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(62, 62, 62))
            .addComponent(jPanelOpciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jPanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanelPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCerrarSesion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonBajaCliente)
                            .addGap(17, 17, 17)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Metodo que actualiza el panel del card layout segun el boton que pulses
    private void actualizarPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPanel
        // TODO add your handling code here:
        JButton jbutton = (JButton) evt.getSource();
        jPanelPadre.removeAll();
        if (jbutton == jButtonVerReservas) {
            jPanelPadre.add(jPanelVerReservas);
        } else if (jbutton == jButtonNuevaReserva) {
            jPanelPadre.add(jPanelNuevaReserva);
        } else if(jbutton == jButtonVerMenu){
            jPanelPadre.add(jPanelMenu);
        }
        
        jPanelPadre.repaint();
        jPanelPadre.revalidate();
    }//GEN-LAST:event_actualizarPanel
    //Este metodo se utiliza para que tras un insert o un update se actualiza el JTable sin que se dupliquen las columnas,
    //por eso los counts a 0
    public void recargarTabla() {
        dtm.setRowCount(0);
        dtm.setColumnCount(0);
        cargaTablaReservas();
    }
    //Este metodo sirve para controlar si la hora introducida por el usuario entra dentro del horario en el que el restaurante
    //admite reservas utilizando LocalTime para cada margen y devolviendo true o false si esta dentro del horario o no
    private boolean validarHorario(Object valorHora){
        SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm");
        String horaSQL = formatoHora.format(valorHora);
        
        //declaracion de margenes
        LocalTime horaReserva = LocalTime.parse(horaSQL);
        LocalTime inicioComida = LocalTime.of(12, 0);
        LocalTime finComida = LocalTime.of(16, 0);
        LocalTime inicioCena = LocalTime.of(21, 0);
        LocalTime finCena = LocalTime.of(23, 59);
        
        //true si entra en elhorario, false si no entra
        return (horaReserva.compareTo(inicioComida) >= 0 && horaReserva.compareTo(finComida) <= 0) || 
                (horaReserva.compareTo(inicioCena) >= 0 && horaReserva.compareTo(finCena) <= 0);
    }
    private int comboBoxIdRestaurante(){        
        try {
            
            String contenido = jComboBoxRestaurantes.getItemAt(jComboBoxRestaurantes.getSelectedIndex());
            PreparedStatement ps = conexion.prepareStatement("SELECT id_restaurante FROM restaurante "
                    + "WHERE CONCAT(nombre, ' | ', direccion)=?");
            ps.setString(1, contenido);
            
            ResultSet r = ps.executeQuery();
            
            int id_restaurante=0;
            while(r.next()){
                id_restaurante = r.getInt(1);
            }
            
            return id_restaurante;
            
        } catch (SQLException ex) {
            System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            return 0;
        }
        
    }
    //Este boton valida la insercion de la reserva. Primero comprueba que ningun campo este vacio, despues que la fecha introducida
    //sea vigente, es decir, que el usuario no introduzca una fecha y hora que ya ha pasado, tras eso comprueba con el metodo anterior
    //que la hora sea valida. Si alguno de estas comprobaciones no es satisfactoria mostrara un JOptionPane indicando el error
    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        String comensales = jTextFieldNumeroComensales.getText();
        java.util.Date mfecha = jDateChooser.getDate();
        Object valorHora = jSpinnerHora.getValue();
        
        //Para la comprobacion exacta de fecha y hora
        Calendar calHoy = Calendar.getInstance();
        Calendar calElegida = Calendar.getInstance();
        calElegida.setTime(mfecha);
        
        SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
        String horaStr = formatoHora.format(valorHora);
        String[] partesHora = horaStr.split(":");
        
        calElegida.set(Calendar.HOUR_OF_DAY, Integer.parseInt(partesHora[0]));
        calElegida.set(Calendar.MINUTE, Integer.parseInt(partesHora[1]));
        calElegida.set(Calendar.SECOND, 0);
        
        //Comprobacion de si algun campo esta vacio
        if(comensales.isEmpty() || mfecha==null || valorHora==null){
            JOptionPane.showConfirmDialog(rootPane,
                                            "Rellena todos los campos", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
        }
        //Comprobacion de fecha no pasada
        else if(calElegida.before(calHoy)){
            JOptionPane.showMessageDialog(rootPane,
                                            "La hora no puede ser anterior a la actual", 
                                            "Error", 
                                            JOptionPane.ERROR_MESSAGE);
        }
        //Comprobacion de horario valido
        else if(!validarHorario(valorHora)){
            JOptionPane.showMessageDialog(rootPane,
                                            "La hora debe estar entre 12:00-16:00 o 21:00-23:59", 
                                            "Error", 
                                            JOptionPane.ERROR_MESSAGE);
        }
        //Si las comprobaciones son correctas realiza la insercion
        else{
            try {
                PreparedStatement ps = conexion.prepareStatement("INSERT INTO reserva"
                        + "(estado_reserva, n_comensales, fecha_hora, id_cliente, id_restaurante)"
                        + " VALUES (?, ?, ?, ?, ?)");
                
                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                String fechaStr = formatoFecha.format(mfecha);

                //SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
                //String horaStr = formatoHora.format(valorHora);

                // Crear el datetime combinado
                String fechaHoraCompleta = fechaStr + " " + horaStr;
                Timestamp fechaHoraSQL = Timestamp.valueOf(fechaHoraCompleta);
                
                ps.setString(1, "pendiente");
                ps.setInt(2, Integer.parseInt(jTextFieldNumeroComensales.getText()));
                ps.setTimestamp(3, fechaHoraSQL);
                ps.setInt(4, id);
                ps.setInt(5, comboBoxIdRestaurante());

                int filas = ps.executeUpdate();
                if(filas==1){
                   JOptionPane.showConfirmDialog(rootPane,
                                                "Reserva registrada", 
                                                "", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.INFORMATION_MESSAGE);
                   recargarTabla(); //Metodo para que la nueva reserva aparezca en el JTable de reservas
                }
                else{
                    JOptionPane.showConfirmDialog(rootPane,
                                                "Ha habido un error", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        
        
    }//GEN-LAST:event_jButtonValidarActionPerformed
    //Este metodo hace que al pulsar el boton de eliminar elimine la reserva seleccionada tanto del JTable como de la base de datos
    private void jButtonAnularReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnularReservaActionPerformed
        // TODO add your handling code here:
      
        if(jTableReservas.getSelectedRowCount()==1){//Si el usuario no ha seleccionado ninguna reserva en el JTable muestra un mensaje
            int fila = jTableReservas.getSelectedRow();
            Object id_reserva_objeto = jTableReservas.getValueAt(fila, 0);
            int id_reserva = Integer.parseInt(id_reserva_objeto.toString());
             try {
                conexion.setAutoCommit(false);
                String sql = "UPDATE reserva SET estado_reserva=? WHERE id_reserva=? AND id_cliente=?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setString(1, "cancelada");
                ps.setInt(2, id_reserva);
                ps.setInt(3, id);
                int opcion = JOptionPane.showConfirmDialog(
                                                null,
                                                "¿Estas seguro de que quieres anular la reserva seleccionada?",
                                                "Confirmación",
                                                JOptionPane.OK_CANCEL_OPTION,
                                                JOptionPane.QUESTION_MESSAGE
                );
                if (opcion == JOptionPane.OK_OPTION) {
                    int resultado=ps.executeUpdate();
                    if(resultado==1){
                        System.out.println("entra");
                        conexion.commit();
                        dtm.removeRow(fila);
                    }
                }
                
                
            } catch (SQLException ex) {
                try {
                    conexion.rollback();
                } catch (SQLException ex1) {
                    System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex1);
                }
                System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione una reserva para anular.");
        }
    }//GEN-LAST:event_jButtonAnularReservaActionPerformed
    //Este metodo abre el JDialog para editar la reserva seleccionada, si no ha seleccionado ninguna muestra un mensaje
    private void jButtonEditarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarReservaActionPerformed
        if(jTableReservas.getSelectedRowCount() == 1){

            int fila = jTableReservas.getSelectedRow();
            int id_reserva = Integer.parseInt(jTableReservas.getValueAt(fila, 0).toString());
            Object fechaHoraObj = jTableReservas.getValueAt(fila, 1);
            Timestamp fechaHora;

            // Convertir a Timestamp dependiendo del tipo de dato que venga
            if (fechaHoraObj instanceof Timestamp) {
                fechaHora = (Timestamp) fechaHoraObj;
            } else if (fechaHoraObj instanceof java.util.Date) {
                fechaHora = new Timestamp(((java.util.Date) fechaHoraObj).getTime());
            } else {
                // Si viene como String, parsearlo
                try {
                    String fechaStr = fechaHoraObj.toString();
                    SimpleDateFormat sdf;

                    // Detectar formato
                    if (fechaStr.contains("/")) {
                        sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
                    } else {
                        sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    }

                    java.util.Date fecha = sdf.parse(fechaStr);
                    fechaHora = new Timestamp(fecha.getTime());

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, 
                        "Error al procesar la fecha: " + e.getMessage(), 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            int n_comensales = Integer.parseInt(jTableReservas.getValueAt(fila, 2).toString());
            
            this.dispose();
            JDialogEditarReserva jdic = new JDialogEditarReserva(padre, true, id_reserva, fechaHora, n_comensales, id);
            jdic.setVisible(true);
            recargarTabla();
        }
        else{
            JOptionPane.showMessageDialog(this, "Selecciona una reserva para editar.");
        }
    }//GEN-LAST:event_jButtonEditarReservaActionPerformed
    //Este metodo abre el JDialog para borrar la cuenta de cliente
    private void jButtonBajaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaClienteActionPerformed
        this.setVisible(false);
        this.dispose();
        JDialogBajaCliente jdbc = new JDialogBajaCliente(padre, true, id);
        jdbc.setVisible(true);
    }//GEN-LAST:event_jButtonBajaClienteActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        JFrameServix jfs = new JFrameServix();
        jfs.setVisible(true);
        
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnularReserva;
    private javax.swing.JButton jButtonBajaCliente;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonEditarReserva;
    private javax.swing.JButton jButtonNuevaReserva;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JButton jButtonVerMenu;
    private javax.swing.JButton jButtonVerReservas;
    private javax.swing.JComboBox<String> jComboBoxRestaurantes;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelBotonesDeleteUpdate;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelNuevaReserva;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPadre;
    private javax.swing.JPanel jPanelVerReservas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerHora;
    private javax.swing.JTable jTableMenu;
    private javax.swing.JTable jTableReservas;
    private javax.swing.JTextField jTextFieldNumeroComensales;
    // End of variables declaration//GEN-END:variables
    
    //Este metodo es el que se encarga de rellenar la tabla con la informacion de las reservas de la base de datos
    public void cargaTablaReservas(){
        
        try {
            PreparedStatement ps = conexion.prepareStatement(
                    "SELECT CONCAT(restaurante.nombre, ' | ', restaurante.direccion) as Restaurante_direccion, id_reserva as Nº, fecha_hora AS Fecha, n_comensales AS Comensales "
                   + "FROM reserva INNER JOIN restaurante "
                   + "ON reserva.id_restaurante = restaurante.id_restaurante "
                   + "WHERE id_cliente=? AND NOT estado_reserva=?"
            );
            ps.setInt(1, id);
            ps.setString(2, "cancelada");
            nueva.selectSQL(ps, dtm);
        } catch (SQLException ex) {
            System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    //Este metodo es el que se encarga de rellenar la tabla con la informacion del menu de la base de datos
    public void cargaTablaMenu(){
        try {
            PreparedStatement ps = conexion.prepareStatement(
                    "SELECT nombre AS Nombre, precio AS Precio, categoria AS Categoria FROM plato ORDER BY categoria"
            );
            nueva.selectSQL(ps, dtm2);
        } catch (SQLException ex) {
            System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    public void formatoTabla(){
        FormatoTablas.FormatoInteger formatoInt = new FormatoTablas.FormatoInteger();
        FormatoTablas.FormatoFecha formatoFecha = new FormatoTablas.FormatoFecha();
        
        // Ajuste de anchos de columna
        // Columnas estrechas (numeros)
        jTableReservas.getColumnModel().getColumn(1).setPreferredWidth(10);  
        jTableReservas.getColumnModel().getColumn(3).setPreferredWidth(10);   

        // Columnas anchas (lo demas)
        jTableReservas.getColumnModel().getColumn(0).setPreferredWidth(300); 
        jTableReservas.getColumnModel().getColumn(2).setPreferredWidth(200); 
        
        jTableReservas.getColumnModel().getColumn(0).setCellRenderer(formatoInt);
        jTableReservas.getColumnModel().getColumn(1).setCellRenderer(formatoFecha);
        jTableReservas.getColumnModel().getColumn(2).setCellRenderer(formatoInt);
        
        jTableReservas.getColumnModel().getColumn(0).setPreferredWidth(150); // Fecha y Hora (más ancho)
        jTableReservas.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableReservas.getColumnModel().getColumn(2).setPreferredWidth(100);// Comensales
    }
    
}
