/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Clientes;

import java.sql.Connection;
import java.sql.SQLException;
import servix.ConexionBBDD;
import servix.JFrameServix;
import java.sql.*;
import javax.swing.JOptionPane;
import servix.Seguridad;

/**
 *
 * @author DAM2Alu11
 */
public class JDialogAltaCliente extends javax.swing.JDialog {
    
    ConexionBBDD nueva;
    Connection conexion;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAltaCliente.class.getName());

    /**
     * Creates new form JDialogAltaCliente
     */
    
    JFrameServix padre;
    public JDialogAltaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        padre= (JFrameServix) parent;
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        Provincia = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldContrasena1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFieldContrasena2 = new javax.swing.JPasswordField();
        jButtonAlta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR CUENTA");

        jPanel1.setLayout(new java.awt.GridLayout(8, 2, 10, 10));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldNombre);

        jLabel3.setText("Primer apellido");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldApellido1);

        Provincia.setText("Segundo apellido");
        jPanel1.add(Provincia);
        jPanel1.add(jTextFieldApellido2);

        jLabel5.setText("Telefono");
        jPanel1.add(jLabel5);
        jPanel1.add(jTextFieldTelefono);

        jLabel6.setText("Correo");
        jPanel1.add(jLabel6);
        jPanel1.add(jTextFieldCorreo);

        jLabel7.setText("Usuario");
        jPanel1.add(jLabel7);
        jPanel1.add(jTextFieldUser);

        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4);
        jPanel1.add(jPasswordFieldContrasena1);

        jLabel8.setText("Introduzca de nuevo la contraseña");
        jPanel1.add(jLabel8);
        jPanel1.add(jPasswordFieldContrasena2);

        jButtonAlta.setText("Alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        String nombre = jTextFieldNombre.getText();
        String apellido1 = jTextFieldApellido1.getText();
        String apellido2 = jTextFieldApellido2.getText();
        String telefono = jTextFieldTelefono.getText();
        String correo = jTextFieldCorreo.getText();
        String user =  jTextFieldUser.getText();
        char[] contrasena = jPasswordFieldContrasena1.getPassword();
        char[] contrasena2 = jPasswordFieldContrasena2.getPassword();
        
        String stringContrasena1 = new String(contrasena);
        String stringContrasena2 = new String(contrasena2);
       
        if(!existeUsuario(user)){
            if(nombre.isEmpty() || apellido1.isEmpty() || telefono.isEmpty() || correo.isEmpty() || user.isEmpty() || contrasena.length == 0 || contrasena2.length == 0){
                JOptionPane.showConfirmDialog(rootPane,
                                            "Porfavor rellene todos los campos", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
           }else{
                if(nombre.length() > 30 || apellido1.length() > 30 || apellido2.length() > 30 ||  telefono.length() > 30 || correo.length() > 40 || user.length() > 30){
                 JOptionPane.showConfirmDialog(rootPane,
                                            "Ningun campo puede exceder los 30 caracteres", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
                }else{
                    if(stringContrasena1.equals(stringContrasena2)){ // Se comprueba que las contraseñas sean iguales
                         String contrasenaEncriptada = Seguridad.hashPassword(stringContrasena1); // contraseña ya encriptada
                         this.setVisible(false);

                         try {
                             nueva.conectar();
                             String sql= "INSERT INTO Cliente(nombre, apellido1, apellido2, telefono, correo, usuario_login, contrasenya_login) VALUES (?,?,?,?,?,?,?)";
                             PreparedStatement ps= conexion.prepareStatement(sql);
                             ps.setString(1, jTextFieldNombre.getText());
                             ps.setString(2, jTextFieldApellido1.getText());
                             ps.setString(3, jTextFieldApellido2.getText());
                             ps.setString(4, jTextFieldTelefono.getText());
                             ps.setString(5, jTextFieldCorreo.getText());
                             ps.setString(6, jTextFieldUser.getText());
                             ps.setString(7, contrasenaEncriptada);

                             ps.executeUpdate();
                             ps.close();
                             conexion.close();
                         } catch (SQLException ex) {
                             System.getLogger(JDialogAltaCliente.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                         }
                    }else{
                         JOptionPane.showConfirmDialog(rootPane,
                                                 "Las contraseñas no coinciden", 
                                                 "Error", 
                                                 JOptionPane.OK_CANCEL_OPTION, 
                                                 JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }else{
             JOptionPane.showConfirmDialog(rootPane,
                                                 "El usuario " + user + " ya existe", 
                                                 "Error", 
                                                 JOptionPane.OK_CANCEL_OPTION, 
                                                 JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAltaActionPerformed

    public boolean existeUsuario(String usuario){
        boolean existe= false;
        try {    
            nueva.conectar();
            String sql = "SELECT * FROM Cliente WHERE usuario_login = ?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, usuario);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) 
                existe = true;
                        
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            System.getLogger(JDialogAltaCliente.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        return existe;
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Provincia;
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContrasena1;
    private javax.swing.JPasswordField jPasswordFieldContrasena2;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
