/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Clientes;

import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import servix.ConexionBBDD;
import servix.JFrameServix;

/**
 *
 * @author DAM2Alu15
 */
public class JDialogInterfazClientes extends javax.swing.JDialog{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogInterfazClientes.class.getName());

    /**
     * Creates new form JDialogInterfazClientes
     */
    JFrameServix padre;
    DefaultTableModel dtm;
    DefaultTableModel dtm2;
    ConexionBBDD nueva = null;
    Connection conexion = null;
    int id;
    
    public JDialogInterfazClientes() {
        
    }
    public JDialogInterfazClientes(java.awt.Dialog parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        this.nueva = new ConexionBBDD();
        this.conexion = nueva.getConnection();
        this.dtm = new DefaultTableModel();
        this.dtm2 = new DefaultTableModel();
        jTableReservas.setModel(dtm);
        jTableMenu.setModel(dtm2);
        this.id = id;
        cargaTablaReservas();
        cargaTablaMenu();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPadre = new javax.swing.JPanel();
        jPanelVerReservas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReservas = new javax.swing.JTable();
        jPanelBotonesDeleteUpdate = new javax.swing.JPanel();
        jButtonAnularReserva = new javax.swing.JButton();
        jButtonEditarReserva = new javax.swing.JButton();
        jPanelNuevaReserva = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerHora = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNumeroComensales = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonValidar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMenu = new javax.swing.JTable();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonNuevaReserva = new javax.swing.JButton();
        jButtonVerReservas = new javax.swing.JButton();
        jButtonVerMenu = new javax.swing.JButton();
        jButtonBajaCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPadre.setLayout(new java.awt.CardLayout());

        jTableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableReservas);

        jButtonAnularReserva.setText("Anular reserva");
        jButtonAnularReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnularReservaActionPerformed(evt);
            }
        });
        jPanelBotonesDeleteUpdate.add(jButtonAnularReserva);

        jButtonEditarReserva.setText("Editar reserva");
        jButtonEditarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarReservaActionPerformed(evt);
            }
        });
        jPanelBotonesDeleteUpdate.add(jButtonEditarReserva);

        javax.swing.GroupLayout jPanelVerReservasLayout = new javax.swing.GroupLayout(jPanelVerReservas);
        jPanelVerReservas.setLayout(jPanelVerReservasLayout);
        jPanelVerReservasLayout.setHorizontalGroup(
            jPanelVerReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerReservasLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBotonesDeleteUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVerReservasLayout.setVerticalGroup(
            jPanelVerReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerReservasLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelBotonesDeleteUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        jPanelPadre.add(jPanelVerReservas, "card2");

        jPanelNuevaReserva.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        jLabel3.setText("Fecha");
        jPanelNuevaReserva.add(jLabel3);
        jPanelNuevaReserva.add(jDateChooser);

        jLabel4.setText("Hora");
        jPanelNuevaReserva.add(jLabel4);

        jSpinnerHora.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerHora.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerHora, "HH:mm"));
        jPanelNuevaReserva.add(jSpinnerHora);

        jLabel5.setText("Numero de comensales");
        jPanelNuevaReserva.add(jLabel5);
        jPanelNuevaReserva.add(jTextFieldNumeroComensales);
        jPanelNuevaReserva.add(jLabel1);

        jButtonValidar.setText("VALIDAR");
        jButtonValidar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });
        jPanelNuevaReserva.add(jButtonValidar);
        jPanelNuevaReserva.add(jLabel6);

        jPanelPadre.add(jPanelNuevaReserva, "card3");

        jTableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMenu);

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
            .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMenuLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
            .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanelPadre.add(jPanelMenu, "card4");

        jButtonNuevaReserva.setText("Nueva reserva");
        jButtonNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPanel(evt);
            }
        });
        jPanelOpciones.add(jButtonNuevaReserva);

        jButtonVerReservas.setText("Ver reservas");
        jButtonVerReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPanel(evt);
            }
        });
        jPanelOpciones.add(jButtonVerReservas);

        jButtonVerMenu.setText("Ver menu");
        jButtonVerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPanel(evt);
            }
        });
        jPanelOpciones.add(jButtonVerMenu);

        jButtonBajaCliente.setText("Eliminar cuenta");
        jButtonBajaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaClienteActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jButtonBajaCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPanel
        // TODO add your handling code here:
        JButton jbutton = (JButton) evt.getSource();
        jPanelPadre.removeAll();
        if (jbutton == jButtonVerReservas) {
            jPanelPadre.add(jPanelVerReservas);
        } else if (jbutton == jButtonNuevaReserva) {
            jPanelPadre.add(jPanelNuevaReserva);
        } else if(jbutton == jButtonVerMenu){
            jPanelPadre.add(jPanelMenu);
        }
        
        jPanelPadre.repaint();
        jPanelPadre.revalidate();
    }//GEN-LAST:event_actualizarPanel
    public void recargarTabla() {
        dtm.setRowCount(0);
        dtm.setColumnCount(0);
        cargaTablaReservas();
    }
    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        String comensales = jTextFieldNumeroComensales.getText();
        java.util.Date mfecha = jDateChooser.getDate();
        Object valorHora = jSpinnerHora.getValue();

        if(comensales.isEmpty() || mfecha==null || valorHora==null){
            JOptionPane.showConfirmDialog(rootPane,
                                            "Rellena todos los campos", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
        }
        else if(mfecha.before(new java.util.Date())){
            JOptionPane.showMessageDialog(rootPane,
                                            "La fecha no puede ser anterior a hoy", 
                                            "Error", 
                                            JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                PreparedStatement ps = conexion.prepareStatement("INSERT INTO reserva"
                        + "(estado_reserva, n_comensales, hora, fecha, id_cliente)"
                        + " VALUES (?, ?, ?, ?, ?)");
                
                long lfecha = mfecha.getTime();
                Date fecha = new Date(lfecha);
                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                String fechaSQL = formatoFecha.format(fecha);
                
                SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm");
                String horaSQL = formatoHora.format(jSpinnerHora.getValue());
                
                ps.setString(1, "pendiente");
                ps.setInt(2, Integer.parseInt(jTextFieldNumeroComensales.getText()));
                ps.setString(3, horaSQL);
                ps.setString(4, fechaSQL);
                ps.setInt(5, id);

                int filas = ps.executeUpdate();
                if(filas==1){
                   JOptionPane.showConfirmDialog(rootPane,
                                                "Reserva registrada", 
                                                "", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.INFORMATION_MESSAGE);
                   recargarTabla();
                }
                else{
                    JOptionPane.showConfirmDialog(rootPane,
                                                "Ha habido un error", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        
        
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonAnularReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnularReservaActionPerformed
        // TODO add your handling code here:
      
        if(jTableReservas.getSelectedRowCount()==1){
            int fila = jTableReservas.getSelectedRow();
            Object id_reserva_objeto = jTableReservas.getValueAt(fila, 0);
            int id_reserva = Integer.parseInt(id_reserva_objeto.toString());
             try {
                conexion.setAutoCommit(false);
                String sql = "DELETE FROM reserva WHERE id_reserva=? AND id_cliente=?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setInt(1, id_reserva);
                ps.setInt(2, id);
                int opcion = JOptionPane.showConfirmDialog(
                                                null,
                                                "¿Estas seguro de anular la reserva seleccionada?",
                                                "Confirmación",
                                                JOptionPane.OK_CANCEL_OPTION,
                                                JOptionPane.QUESTION_MESSAGE
                );
                if (opcion == JOptionPane.OK_OPTION) {
                    int resultado=ps.executeUpdate();
                    if(resultado==1){
                        conexion.commit();
                        dtm.removeRow(fila);
                    }
                }
                
                
            } catch (SQLException ex) {
                try {
                    conexion.rollback();
                } catch (SQLException ex1) {
                    System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex1);
                }
                System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_jButtonAnularReservaActionPerformed

    private void jButtonEditarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarReservaActionPerformed
        if(jTableReservas.getSelectedRowCount() == 1){
            
            int fila = jTableReservas.getSelectedRow();

            int id_reserva = Integer.parseInt(jTableReservas.getValueAt(fila, 0).toString());
            String fecha = jTableReservas.getValueAt(fila, 1).toString();
            String hora = jTableReservas.getValueAt(fila, 2).toString();
            int n_comensales = Integer.parseInt(jTableReservas.getValueAt(fila, 3).toString());

            JDialogEditarReserva jdic = new JDialogEditarReserva(this, true, id_reserva, fecha, hora, n_comensales);
            jdic.setVisible(true);

            recargarTabla();
        
        }      
    }//GEN-LAST:event_jButtonEditarReservaActionPerformed

    private void jButtonBajaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaClienteActionPerformed
        this.setVisible(false);
        this.dispose();
        JDialogBajaCliente jdbc = new JDialogBajaCliente(this, true, id);
        jdbc.setVisible(true);
    }//GEN-LAST:event_jButtonBajaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnularReserva;
    private javax.swing.JButton jButtonBajaCliente;
    private javax.swing.JButton jButtonEditarReserva;
    private javax.swing.JButton jButtonNuevaReserva;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JButton jButtonVerMenu;
    private javax.swing.JButton jButtonVerReservas;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelBotonesDeleteUpdate;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelNuevaReserva;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPadre;
    private javax.swing.JPanel jPanelVerReservas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerHora;
    private javax.swing.JTable jTableMenu;
    private javax.swing.JTable jTableReservas;
    private javax.swing.JTextField jTextFieldNumeroComensales;
    // End of variables declaration//GEN-END:variables
    
    public void cargaTablaReservas(){
        //int id = Integer.parseInt(cliente.getId_cliente()); //RECOGER DE JDIALOG ANTERIOR
        try {
            PreparedStatement ps = conexion.prepareStatement(
                    "SELECT id_reserva AS Numero, fecha AS Fecha, hora AS Hora, n_comensales AS Comensales FROM reserva WHERE id_cliente=?"
            );
            ps.setInt(1, id);
            nueva.selectSQL(ps, dtm);
        } catch (SQLException ex) {
            System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    public void cargaTablaMenu(){
        try {
            PreparedStatement ps = conexion.prepareStatement(
                    "SELECT nombre AS Nombre, precio AS Precio, categoria AS Categoria FROM plato ORDER BY categoria"
            );
            nueva.selectSQL(ps, dtm2);
        } catch (SQLException ex) {
            System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
}
