/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Clientes;


import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import servix.ConexionBBDD;

/**
 *
 * @author DAM2Alu15
 */
public class JDialogInterfazClientes extends javax.swing.JDialog{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogInterfazClientes.class.getName());

    /**
     * Creates new form JDialogInterfazClientes
     */
    DefaultTableModel dtm;
    ConexionBBDD nueva = null;
    Connection conexion = null;
    
    public JDialogInterfazClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.nueva = new ConexionBBDD();
        this.conexion = nueva.getConnection();
        this.dtm = new DefaultTableModel();
        jTableReservas.setModel(dtm);
        cargaTabla();
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPadre = new javax.swing.JPanel();
        jPanelVerReservas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReservas = new javax.swing.JTable();
        jPanelNuevaReserva = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerFecha = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerHora = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNumeroComensales = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonValidar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonNuevaReserva = new javax.swing.JButton();
        jButtonVerReservas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPadre.setLayout(new java.awt.CardLayout());

        jTableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableReservas);

        javax.swing.GroupLayout jPanelVerReservasLayout = new javax.swing.GroupLayout(jPanelVerReservas);
        jPanelVerReservas.setLayout(jPanelVerReservasLayout);
        jPanelVerReservasLayout.setHorizontalGroup(
            jPanelVerReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerReservasLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        jPanelVerReservasLayout.setVerticalGroup(
            jPanelVerReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerReservasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );

        jPanelPadre.add(jPanelVerReservas, "card2");

        jPanelNuevaReserva.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        jLabel3.setText("Fecha");
        jPanelNuevaReserva.add(jLabel3);

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1763381041563L), null, java.util.Calendar.DAY_OF_MONTH));
        jSpinnerFecha.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerFecha, "dd/MM/yyyy"));
        jPanelNuevaReserva.add(jSpinnerFecha);

        jLabel4.setText("Hora");
        jPanelNuevaReserva.add(jLabel4);

        jSpinnerHora.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerHora.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerHora, "HH:mm"));
        jPanelNuevaReserva.add(jSpinnerHora);

        jLabel5.setText("Numero de comensales");
        jPanelNuevaReserva.add(jLabel5);
        jPanelNuevaReserva.add(jTextFieldNumeroComensales);
        jPanelNuevaReserva.add(jLabel1);

        jButtonValidar.setText("VALIDAR");
        jButtonValidar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });
        jPanelNuevaReserva.add(jButtonValidar);
        jPanelNuevaReserva.add(jLabel6);

        jPanelPadre.add(jPanelNuevaReserva, "card3");

        jButtonNuevaReserva.setText("Nueva reserva");
        jButtonNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPanel(evt);
            }
        });
        jPanelOpciones.add(jButtonNuevaReserva);

        jButtonVerReservas.setText("Ver reservas");
        jButtonVerReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPanel(evt);
            }
        });
        jPanelOpciones.add(jButtonVerReservas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPanel
        // TODO add your handling code here:
        JButton jbutton = (JButton) evt.getSource();
        jPanelPadre.removeAll();
        if (jbutton == jButtonVerReservas) {
            jPanelPadre.add(jPanelVerReservas);
        } else if (jbutton == jButtonNuevaReserva) {
            jPanelPadre.add(jPanelNuevaReserva);
        }
        jPanelPadre.repaint();
        jPanelPadre.revalidate();
    }//GEN-LAST:event_actualizarPanel

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        String usuario="hector"; // Esto tendra que ser recogido de el JDialog anterior
        try {
            System.out.println(String.valueOf(jSpinnerHora.getValue()));
            System.out.println(String.valueOf(jSpinnerFecha.getValue()));
            PreparedStatement ps = conexion.prepareStatement("INSERT INTO reserva"
                    + "(estado_reserva, n_comensales, hora, fecha, id_cliente)"
                    + " SELECT ?, ?, ?, ?, id_cliente"
                    + " FROM cliente "
                    + " WHERE usuario_login=?");
            ps.setString(1, "confirmada");
            ps.setInt(2, Integer.parseInt(jTextFieldNumeroComensales.getText()));
            
            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            String fechaSQL = formatoFecha.format(jSpinnerFecha.getValue());

            SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm");
            String horaSQL = formatoHora.format(jSpinnerHora.getValue());
            
            ps.setString(3, horaSQL);
            ps.setString(4, fechaSQL);
            
            ps.setString(5, usuario);
            
            
            
            System.out.println(jSpinnerHora.getValue().toString());
            System.out.println(jSpinnerFecha.getValue().toString());
            int filas = ps.executeUpdate();
            if(filas==1){
               JOptionPane.showConfirmDialog(rootPane,
                                            "Reserva registrada", 
                                            "", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showConfirmDialog(rootPane,
                                            "Ha habido un error", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButtonValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogInterfazClientes dialog = new JDialogInterfazClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNuevaReserva;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JButton jButtonVerReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelNuevaReserva;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPadre;
    private javax.swing.JPanel jPanelVerReservas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JSpinner jSpinnerHora;
    private javax.swing.JTable jTableReservas;
    private javax.swing.JTextField jTextFieldNumeroComensales;
    // End of variables declaration//GEN-END:variables
    
    public void cargaTabla(){
        try {
            PreparedStatement ps = conexion.prepareStatement(
                    "SELECT * FROM reserva"
            );
            nueva.selectSQL(ps, dtm);
        } catch (SQLException ex) {
            System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
}
