/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Clientes;
import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import servix.ConexionBBDD;
import servix.JFrameServix;
/**
 *
 * @author valde
 */
public class JDialogEditarReserva extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEditarReserva.class.getName());

    /**
     * Creates new form JDialogEditarReserva
     */
    private int idReserva;
    private Timestamp fechaHora;
    private int nComensales;
    private Connection conexion;
    private JFrameServix padre;
    private int id;
    
    public JDialogEditarReserva(java.awt.Frame parent, boolean modal, int idReserva, Timestamp fecha, int nComensales, int id) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        this.setTitle("Servix");
        this.idReserva = idReserva;
        this.fechaHora = fecha;
        this.nComensales = nComensales;
        this.padre = (JFrameServix) parent;
        this.id = id;
        
        ConexionBBDD nuevaConexion = new ConexionBBDD();
        this.conexion = nuevaConexion.getConnection();
        cargarDatosReserva();
        
        if (JFrameServix.hb != null) {
            JFrameServix.hb.enableHelpKey(this.getContentPane(), "ayuda_editar_reserva", JFrameServix.hs);
        }
    }
    
    private void cargarDatosReserva() {
        try {
            java.util.Date fecha = new java.util.Date(fechaHora.getTime());
            jDateChooserFecha.setDate(fechaHora);
            jSpinnerHora.setValue(fechaHora);

            jSpinnerComensales.setValue(this.nComensales);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerHora = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerComensales = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonValidar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel2.setText("Fecha");
        jPanel1.add(jLabel2);

        jDateChooserFecha.setMinSelectableDate(new java.util.Date());
        jPanel1.add(jDateChooserFecha);

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel4.setText("Hora");
        jPanel1.add(jLabel4);

        jSpinnerHora.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerHora.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerHora, "HH:mm"));
        jPanel1.add(jSpinnerHora);

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel3.setText("Comensales");
        jPanel1.add(jLabel3);
        jPanel1.add(jSpinnerComensales);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Editar reserva");
        jPanel2.add(jLabel1);

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCancelar);

        jButtonValidar.setBackground(new java.awt.Color(19, 118, 148));
        jButtonValidar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonValidar.setForeground(new java.awt.Color(219, 219, 255));
        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonValidar);

        jLabel5.setText("Héctor Valdés");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean validarHorario(Object valorHora){
        SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm");
        String horaSQL = formatoHora.format(valorHora);
        
        //declaracion de margenes
        LocalTime horaReserva = LocalTime.parse(horaSQL);
        LocalTime inicioComida = LocalTime.of(12, 0);
        LocalTime finComida = LocalTime.of(16, 0);
        LocalTime inicioCena = LocalTime.of(21, 0);
        LocalTime finCena = LocalTime.of(23, 59);
        
        //true si entra en elhorario, false si no entra
        return (horaReserva.compareTo(inicioComida) >= 0 && horaReserva.compareTo(finComida) <= 0) || 
                (horaReserva.compareTo(inicioCena) >= 0 && horaReserva.compareTo(finCena) <= 0);
    } 
    
    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        java.util.Date mfecha = jDateChooserFecha.getDate();
        Object valorHora = jSpinnerHora.getValue();
        Object valorComensales = jSpinnerComensales.getValue();

        if(valorComensales == null || valorHora == null || mfecha == null){
            JOptionPane.showMessageDialog(rootPane, "Rellena todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(mfecha.before(new java.util.Date())){
            JOptionPane.showMessageDialog(rootPane,
                                            "La fecha no puede ser anterior a hoy", 
                                            "Error", 
                                            JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(!validarHorario(valorHora)){
            JOptionPane.showMessageDialog(rootPane,
                                            "La hora debe estar entre 12:00-16:00 o 21:00-23:59", 
                                            "Error", 
                                            JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            String fechaSQL = formatoFecha.format(mfecha);

            SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
            String horaSQL = formatoHora.format(valorHora);

            //Datetime combinado
            String fechaHoraCompleta = fechaSQL + " " + horaSQL;
            Timestamp fechaHoraSQL = Timestamp.valueOf(fechaHoraCompleta);
            
            PreparedStatement ps = conexion.prepareStatement(
                "UPDATE reserva SET fecha_hora=?, n_comensales=? WHERE id_reserva=?");

            ps.setTimestamp(1, fechaHoraSQL);
            ps.setInt(2, Integer.parseInt(valorComensales.toString()));
            ps.setInt(3, idReserva);

            if(ps.executeUpdate() == 1){
                JOptionPane.showMessageDialog(rootPane, "Reserva actualizada", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                JDialogInterfazClientes jdic = new JDialogInterfazClientes(padre, true, id);
                jdic.recargarTabla();
                jdic.setVisible(true);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        JDialogInterfazClientes jdic = new JDialogInterfazClientes(padre, true, id);
        jdic.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonValidar;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinnerComensales;
    private javax.swing.JSpinner jSpinnerHora;
    // End of variables declaration//GEN-END:variables
}
