/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Gerente;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servix.ConexionBBDD;
import servix.FormatoTablas;
import servix.JFrameServix;
import servix.Login_CRUD.Clientes.JDialogEditarReserva;
import servix.Login_CRUD.Clientes.JDialogInterfazClientes;

/**
 *
 * @author usuario
 */
public class JDialogInterfazGerente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogInterfazGerente.class.getName());

    /**
     * Creates new form JDialogAdministrarRestaurantes
     */
    
    DefaultTableModel dtm;
    DefaultTableModel dtm2;
    DefaultTableModel dtm3;
    ConexionBBDD nueva;
    Connection conexion;
    JFrameServix padre;
    CargaCombos cc;
    
    public JDialogInterfazGerente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        this.dtm = new DefaultTableModel();
        jTableRestaurantes.setModel(dtm);
        this.dtm2 = new DefaultTableModel();
        jTableEncargados.setModel(dtm2);
        this.dtm3 = new DefaultTableModel();
        jTableAsignaciones.setModel(dtm3);
        this.padre = (JFrameServix) parent;
        this.cc = new CargaCombos();
        cc.cargaCombos(jComboBoxRestaurantes, jComboBoxEncargados);
        
        cargaTablaRestaurantes();
        cargaTablaEncargados();
        cargaTablaAsignaciones();
        formatoTabla();
        
        /*if (JFrameServix.hb != null) {
            JFrameServix.hb.enableHelpKey(this.getContentPane(), "ayuda_clientes", JFrameServix.hs);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelNuevo = new javax.swing.JPanel();
        jPanelRestaurantes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreRestaurante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTelefonoRestaurante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCorreoRestaurante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerCapacidad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerApertura = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerCierre = new javax.swing.JSpinner();
        jButtonValidarRestaurante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRestaurantes = new javax.swing.JTable();
        jButtonEliminarRestaurante = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonEditarRestaurante = new javax.swing.JButton();
        jPanelEncargados = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEncargados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNombreEncargado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTelefonoEncargado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCorreoEncargado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldContrasena = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldConfirmacionContrasena = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonValidarEncargado = new javax.swing.JButton();
        jButtonEditarEncargado = new javax.swing.JButton();
        jButtonEliminarEncargado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAsignaciones = new javax.swing.JTable();
        jButtonEliminarAsignacion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxRestaurantes = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxEncargados = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButtonAsignar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jButtonCerrarSesion1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelRestaurantes.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        jLabel1.setText("Nombre");
        jPanelRestaurantes.add(jLabel1);
        jPanelRestaurantes.add(jTextFieldNombreRestaurante);

        jLabel2.setText("Direccion");
        jPanelRestaurantes.add(jLabel2);
        jPanelRestaurantes.add(jTextFieldDireccion);

        jLabel3.setText("Telefono");
        jPanelRestaurantes.add(jLabel3);
        jPanelRestaurantes.add(jTextFieldTelefonoRestaurante);

        jLabel4.setText("Correo");
        jPanelRestaurantes.add(jLabel4);
        jPanelRestaurantes.add(jTextFieldCorreoRestaurante);

        jLabel5.setText("Capacidad");
        jPanelRestaurantes.add(jLabel5);
        jPanelRestaurantes.add(jSpinnerCapacidad);

        jLabel6.setText("Apertura");
        jPanelRestaurantes.add(jLabel6);
        jPanelRestaurantes.add(jSpinnerApertura);

        jLabel7.setText("Cierre");
        jPanelRestaurantes.add(jLabel7);
        jPanelRestaurantes.add(jSpinnerCierre);

        jButtonValidarRestaurante.setText("Validar");
        jButtonValidarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarRestauranteActionPerformed(evt);
            }
        });

        jTableRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRestaurantes);

        jButtonEliminarRestaurante.setText("Eliminar");
        jButtonEliminarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarRestauranteActionPerformed(evt);
            }
        });

        jButtonCerrarSesion.setText("Cerrar sesion");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jButtonEditarRestaurante.setText("Editar");
        jButtonEditarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarRestauranteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNuevoLayout = new javax.swing.GroupLayout(jPanelNuevo);
        jPanelNuevo.setLayout(jPanelNuevoLayout);
        jPanelNuevoLayout.setHorizontalGroup(
            jPanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNuevoLayout.createSequentialGroup()
                .addGroup(jPanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNuevoLayout.createSequentialGroup()
                        .addComponent(jButtonCerrarSesion)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonValidarRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jPanelRestaurantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNuevoLayout.createSequentialGroup()
                        .addComponent(jButtonEditarRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEliminarRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelNuevoLayout.setVerticalGroup(
            jPanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNuevoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRestaurantes, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonValidarRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEliminarRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonEditarRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane.addTab("Restaurantes", jPanelNuevo);

        jTableEncargados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableEncargados);

        jPanel1.setLayout(new java.awt.GridLayout(8, 2, 10, 10));

        jLabel8.setText("Nombre");
        jPanel1.add(jLabel8);
        jPanel1.add(jTextFieldNombreEncargado);

        jLabel9.setText("Primer apellido");
        jPanel1.add(jLabel9);
        jPanel1.add(jTextFieldApellido1);

        jLabel10.setText("Segundo apellido");
        jPanel1.add(jLabel10);
        jPanel1.add(jTextFieldApellido2);

        jLabel11.setText("Telefono");
        jPanel1.add(jLabel11);
        jPanel1.add(jTextFieldTelefonoEncargado);

        jLabel12.setText("Correo");
        jPanel1.add(jLabel12);
        jPanel1.add(jTextFieldCorreoEncargado);

        jLabel13.setText("Usuario");
        jPanel1.add(jLabel13);
        jPanel1.add(jTextFieldUsuario);

        jLabel14.setText("Contraseña");
        jPanel1.add(jLabel14);
        jPanel1.add(jTextFieldContrasena);

        jLabel15.setText("Confirmar contraseña");
        jPanel1.add(jLabel15);
        jPanel1.add(jTextFieldConfirmacionContrasena);

        jButton1.setText("Cerrar sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jButtonValidarEncargado.setText("Validar");
        jButtonValidarEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarEncargadoActionPerformed(evt);
            }
        });

        jButtonEditarEncargado.setText("Editar");
        jButtonEditarEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarEncargadoActionPerformed(evt);
            }
        });

        jButtonEliminarEncargado.setText("Eliminar");
        jButtonEliminarEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarEncargadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEncargadosLayout = new javax.swing.GroupLayout(jPanelEncargados);
        jPanelEncargados.setLayout(jPanelEncargadosLayout);
        jPanelEncargadosLayout.setHorizontalGroup(
            jPanelEncargadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncargadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEncargadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEncargadosLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonValidarEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEncargadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                    .addGroup(jPanelEncargadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEditarEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelEncargadosLayout.setVerticalGroup(
            jPanelEncargadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncargadosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelEncargadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEncargadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButtonEliminarEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditarEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonValidarEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Encargados", jPanelEncargados);

        jTableAsignaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableAsignaciones);

        jButtonEliminarAsignacion.setText("Eliminar");
        jButtonEliminarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAsignacionActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridLayout(5, 2, 10, 10));

        jLabel16.setText("Restaurantes sin asignar");
        jPanel3.add(jLabel16);

        jComboBoxRestaurantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBoxRestaurantes);
        jPanel3.add(jLabel17);
        jPanel3.add(jLabel18);

        jLabel19.setText("Encargados sin asignar");
        jPanel3.add(jLabel19);

        jComboBoxEncargados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBoxEncargados);
        jPanel3.add(jLabel21);
        jPanel3.add(jLabel22);
        jPanel3.add(jLabel20);

        jButtonAsignar.setText("Asignar");
        jButtonAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAsignar);

        jLabel23.setText("Restaurantes con sus encargados asignados");

        jButtonCerrarSesion1.setText("Cerrar sesion");
        jButtonCerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCerrarSesion1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonEliminarAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(152, 152, 152))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCerrarSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane.addTab("Asignaciones", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        JFrameServix jfs = new JFrameServix();
        jfs.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jButtonValidarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarRestauranteActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldNombreRestaurante.getText();
        String direccion = jTextFieldDireccion.getText();
        String telefono = jTextFieldTelefonoRestaurante.getText();
        String correo = jTextFieldCorreoRestaurante.getText();
        int capacidad = (int) jSpinnerCapacidad.getValue();
        int apertura = (int) jSpinnerApertura.getValue();
        int cierre = (int) jSpinnerCierre.getValue();
        
        if(nombre.isEmpty() || direccion.isEmpty() || telefono.isEmpty() || correo.isEmpty()
                || capacidad<=0 || apertura <=0 || cierre<=0){
            JOptionPane.showConfirmDialog(rootPane,
                                                "No puede haber campos vacios o que sean menor o igual a 0", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                PreparedStatement ps = conexion.prepareStatement("INSERT INTO restaurante (nombre, direccion, telefono, correo, capacidad, apertura, cierre)"
                                                                + " VALUES (?,?,?,?,?,?,?)");
                ps.setString(1, nombre);
                ps.setString(2, direccion);
                ps.setString(3, telefono);
                ps.setString(4, correo);
                ps.setInt(5, capacidad);
                ps.setInt(6, apertura);
                ps.setInt(7, cierre);
                
                int filas = ps.executeUpdate();
                if(filas==1){
                   JOptionPane.showConfirmDialog(rootPane,
                                                "Restaurante registrado", 
                                                "", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.INFORMATION_MESSAGE);
                   recargarTablaRestaurantes();
                   cc.cargaCombos(jComboBoxRestaurantes, jComboBoxEncargados);
                   
                   jTextFieldCorreoRestaurante.setText("");
                   jTextFieldDireccion.setText("");
                   jTextFieldNombreRestaurante.setText("");
                   jTextFieldTelefonoRestaurante.setText("");
                   jSpinnerApertura.setValue(0);
                   jSpinnerCapacidad.setValue(0);
                   jSpinnerCierre.setValue(0);

                }
                else{
                    JOptionPane.showConfirmDialog(rootPane,
                                                "Ha habido un error", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                System.getLogger(JDialogInterfazGerente.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_jButtonValidarRestauranteActionPerformed

    private void jButtonValidarEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarEncargadoActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldNombreEncargado.getText();
        String apellido1 = jTextFieldApellido1.getText();
        String apellido2 = jTextFieldApellido2.getText();
        String telefono = jTextFieldTelefonoEncargado.getText();
        String correo = jTextFieldCorreoEncargado.getText();
        String usuario = jTextFieldUsuario.getText();
        String contrasena = jTextFieldContrasena.getText();
        String confirmacion_contrasena = jTextFieldConfirmacionContrasena.getText();
        
        
        if(nombre.isEmpty() || apellido1.isEmpty() || telefono.isEmpty() || correo.isEmpty()
                || usuario.isEmpty() || contrasena.isEmpty() || apellido2.isEmpty()){
            JOptionPane.showConfirmDialog(rootPane,
                                                "No puede haber campos vacios", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
        }
        else if(!(contrasena.equals(confirmacion_contrasena))){
            JOptionPane.showConfirmDialog(rootPane,
                                                "Las contraseñas no coinciden", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                String sql = "INSERT INTO Usuario(nombre, apellido1, apellido2, telefono, correo, usuario_login, contrasenya_login, rol, fecha_creacion) "
                        + " VALUES (?,?,?,?,?,?,?,?, CURDATE())";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setString(1, nombre);
                ps.setString(2, apellido1);
                ps.setString(3, apellido2);
                ps.setString(4, telefono);
                ps.setString(5, correo);
                ps.setString(6, usuario);
                ps.setString(7, contrasena);
                ps.setString(8, "encargado");
                
                
                int filas = ps.executeUpdate();
                if(filas==1){
                   JOptionPane.showConfirmDialog(rootPane,
                                                "Encargado registrado", 
                                                "", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.INFORMATION_MESSAGE);
                   recargarTablaEncargados(); 
                   cc.cargaCombos(jComboBoxRestaurantes, jComboBoxEncargados);
                }
                else{
                    JOptionPane.showConfirmDialog(rootPane,
                                                "Ha habido un error", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                System.getLogger(JDialogInterfazGerente.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_jButtonValidarEncargadoActionPerformed

    private void jButtonEliminarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAsignacionActionPerformed
        // TODO add your handling code here:
        if(jTableAsignaciones.getSelectedRowCount()==1){//Si el usuario no ha seleccionado ninguna reserva en el JTable muestra un mensaje
            int fila = jTableAsignaciones.getSelectedRow();
            String nombre_apellidos_usuario = String.valueOf(jTableAsignaciones.getValueAt(fila, 0));
            String nombre_direccion_restaurante = String.valueOf(jTableAsignaciones.getValueAt(fila, 1));
            
             try {
                conexion.setAutoCommit(false);
                String sql = "DELETE FROM usuario_restaurante "
                        + "WHERE id_usuario = (SELECT id FROM usuario WHERE CONCAT(nombre, ' ', apellido1, ' ', apellido2) = ?) "
                        + "AND id_restaurante = (SELECT id_restaurante FROM restaurante WHERE CONCAT(nombre, ' | ', direccion) = ?)";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setString(1, nombre_apellidos_usuario);
                ps.setString(2, nombre_direccion_restaurante);
                int opcion = JOptionPane.showConfirmDialog(
                                                null,
                                                "¿Estas seguro de eliminar la asignacion seleccionada?",
                                                "Confirmación",
                                                JOptionPane.OK_CANCEL_OPTION,
                                                JOptionPane.QUESTION_MESSAGE
                );
                if (opcion == JOptionPane.OK_OPTION) {
                    int resultado=ps.executeUpdate();
                    if(resultado==1){
                        System.out.println("entra");
                        conexion.commit();
                        dtm3.removeRow(fila);
                        cc.cargaCombos(jComboBoxRestaurantes, jComboBoxEncargados);
                    }
                }
                
                
            } catch (SQLException ex) {
                try {
                    conexion.rollback();
                } catch (SQLException ex1) {
                    System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex1);
                }
                System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione una asignacion para eliminar.");
        }
    }//GEN-LAST:event_jButtonEliminarAsignacionActionPerformed

    private void jButtonEliminarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarRestauranteActionPerformed
        // TODO add your handling code here:
        if(jTableRestaurantes.getSelectedRowCount()==1){//Si el usuario no ha seleccionado ninguna reserva en el JTable muestra un mensaje
            int fila = jTableRestaurantes.getSelectedRow();
            Object id_restaurante_objeto = jTableRestaurantes.getValueAt(fila, 0);
            int id_restaurante = Integer.parseInt(id_restaurante_objeto.toString());
             try {
                conexion.setAutoCommit(false);
                String sql = "DELETE FROM restaurante WHERE id_restaurante=?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setInt(1, id_restaurante);
                int opcion = JOptionPane.showConfirmDialog(
                                                null,
                                                "¿Estas seguro de eliminar el restaurante seleccionado?",
                                                "Confirmación",
                                                JOptionPane.OK_CANCEL_OPTION,
                                                JOptionPane.QUESTION_MESSAGE
                );
                if (opcion == JOptionPane.OK_OPTION) {
                    int resultado=ps.executeUpdate();
                    if(resultado==1){
                        System.out.println("entra");
                        conexion.commit();
                        dtm.removeRow(fila);
                        cc.cargaCombos(jComboBoxRestaurantes, jComboBoxEncargados);
                    }
                }
                
                
            } catch (SQLException ex) {
                try {
                    conexion.rollback();
                } catch (SQLException ex1) {
                    System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex1);
                }
                System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione una reserva para anular.");
        }
    }//GEN-LAST:event_jButtonEliminarRestauranteActionPerformed

    private void jButtonEliminarEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarEncargadoActionPerformed
        // TODO add your handling code here:
        if(jTableEncargados.getSelectedRowCount()==1){//Si el usuario no ha seleccionado ninguna reserva en el JTable muestra un mensaje
            int fila = jTableEncargados.getSelectedRow();
            Object id_restaurante_objeto = jTableEncargados.getValueAt(fila, 0);
            int id_restaurante = Integer.parseInt(id_restaurante_objeto.toString());
             try {
                conexion.setAutoCommit(false);
                String sql = "DELETE FROM usuario WHERE id=? AND rol=?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setInt(1, id_restaurante);
                ps.setString(2, "encargado");
                int opcion = JOptionPane.showConfirmDialog(
                                                null,
                                                "¿Estas seguro de eliminar el encargado seleccionado?",
                                                "Confirmación",
                                                JOptionPane.OK_CANCEL_OPTION,
                                                JOptionPane.QUESTION_MESSAGE
                );
                if (opcion == JOptionPane.OK_OPTION) {
                    int resultado=ps.executeUpdate();
                    if(resultado==1){
                        System.out.println("entra");
                        conexion.commit();
                        dtm2.removeRow(fila);
                        cc.cargaCombos(jComboBoxRestaurantes, jComboBoxEncargados);
                    }
                }
                
                
            } catch (SQLException ex) {
                try {
                    conexion.rollback();
                } catch (SQLException ex1) {
                    System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex1);
                }
                System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione una reserva para anular.");
        }
    }//GEN-LAST:event_jButtonEliminarEncargadoActionPerformed

    private void jButtonEditarEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarEncargadoActionPerformed
        // TODO add your handling code here:
        if(jTableEncargados.getSelectedRowCount() == 1){

            int fila = jTableEncargados.getSelectedRow();
            
            int id_encargado = Integer.parseInt(jTableEncargados.getValueAt(fila, 0).toString());
            String nombreEncargado = jTableEncargados.getValueAt(fila, 1).toString();
            String apellido1 = jTableEncargados.getValueAt(fila, 2).toString();
            String apellido2   = jTableEncargados.getValueAt(fila, 3).toString();
            String telefonoEncargado = jTableEncargados.getValueAt(fila, 4).toString();
            String correoEncargado = jTableEncargados.getValueAt(fila, 5).toString();
            String usuario = jTableEncargados.getValueAt(fila, 6).toString();
            String contrasena = jTableEncargados.getValueAt(fila, 7).toString();
            
            this.setVisible(false);
            JDialogEditarEncargado jder = new JDialogEditarEncargado(padre, true, id_encargado, nombreEncargado, apellido1, apellido2, 
                                                                         telefonoEncargado, correoEncargado, usuario, contrasena);
            jder.setVisible(true);
            jTabbedPane.setSelectedIndex(1);
            recargarTablaEncargados();
            
            cc.cargaCombos(jComboBoxRestaurantes, jComboBoxEncargados);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Selecciona una fila", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditarEncargadoActionPerformed

    private void jButtonAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO usuario_restaurante(id_usuario, id_restaurante) "
                       + "SELECT u.id, r.id_restaurante "
                       + "FROM Usuario u, Restaurante r "
                       + "WHERE CONCAT(u.nombre, ' ', u.apellido1, ' ', u.apellido2) = ? "
                       + "AND CONCAT(r.nombre, ' | ', r.direccion ) = ?";

            PreparedStatement ps = conexion.prepareStatement(sql);

            ps.setString(1, jComboBoxEncargados.getSelectedItem().toString());
            ps.setString(2, jComboBoxRestaurantes.getSelectedItem().toString());

            int filas = ps.executeUpdate();

            if(filas == 1) {
                JOptionPane.showMessageDialog(rootPane, "Asignación confirmada");
                recargarTablaAsignaciones();
                cc.cargaCombos(jComboBoxRestaurantes, jComboBoxEncargados);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButtonAsignarActionPerformed

    private void jButtonEditarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarRestauranteActionPerformed
        // TODO add your handling code here:
        if(jTableRestaurantes.getSelectedRowCount() == 1){

            int fila = jTableRestaurantes.getSelectedRow();
            
            int id_restaurante = Integer.parseInt(jTableRestaurantes.getValueAt(fila, 0).toString());
            String nombreRestaurante = jTableRestaurantes.getValueAt(fila, 1).toString();
            String direccion = jTableRestaurantes.getValueAt(fila, 2).toString();
            String telefonoRestaurante   = jTableRestaurantes.getValueAt(fila, 3).toString();
            String correoRestaurante = jTableRestaurantes.getValueAt(fila, 4).toString();
            int capacidad = Integer.parseInt(jTableRestaurantes.getValueAt(fila, 5).toString());
            int apertura = Integer.parseInt(jTableRestaurantes.getValueAt(fila, 6).toString());
            int cierre = Integer.parseInt(jTableRestaurantes.getValueAt(fila, 7).toString());
                                            
            this.dispose();
            JDialogEditarRestaurante jder = new JDialogEditarRestaurante(padre, true, id_restaurante, nombreRestaurante, direccion, telefonoRestaurante, 
                                                                         correoRestaurante, capacidad, apertura, cierre);
            jder.setVisible(true);
            jTabbedPane.setSelectedIndex(0);
            recargarTablaEncargados();
            cc.cargaCombos(jComboBoxRestaurantes, jComboBoxEncargados);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Selecciona una fila", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditarRestauranteActionPerformed
    public void recargarTablaRestaurantes() {
        dtm.setRowCount(0);
        dtm.setColumnCount(0);
        cargaTablaRestaurantes();
    }
    public void recargarTablaEncargados() {
        dtm2.setRowCount(0);
        dtm2.setColumnCount(0);
        cargaTablaEncargados();
    }
    public void recargarTablaAsignaciones() {
        dtm3.setRowCount(0);
        dtm3.setColumnCount(0);
        cargaTablaAsignaciones();
    }
    public void cargaTablaRestaurantes(){
        try {
            PreparedStatement ps = conexion.prepareStatement(
                    "SELECT id_restaurante as Id, nombre as Nombre, direccion as Direccion, telefono as Telefono, correo as Correo, capacidad as Capacidad,"
                            + " apertura as Apertura, cierre as Cierre"
                            + " FROM restaurante"
            );
            nueva.selectSQL(ps, dtm);
        } catch (SQLException ex) {
            System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    private void cargaTablaEncargados() {
        try {
            PreparedStatement ps = conexion.prepareStatement(
                    "SELECT id as Id, nombre as Nombre, apellido1 as Primer_Apellido, apellido2 as Segundo_Apellido, telefono as Telefono, correo as Correo,"
                            + " usuario_login as Usuario, contrasenya_login as Contraseña"
                            + " FROM usuario WHERE rol=?"
            );
            ps.setString(1, "encargado");
            nueva.selectSQL(ps, dtm2);
        } catch (SQLException ex) {
            System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    private void cargaTablaAsignaciones() {
        try {
            String sql = "SELECT " +
                     "CONCAT(u.nombre, ' ', u.apellido1, ' ', u.apellido2) AS 'Encargado', " +
                     "CONCAT(r.nombre, ' | ', r.direccion) AS 'Restaurante' " +
                     "FROM usuario_restaurante ur " +
                     "INNER JOIN usuario u ON ur.id_usuario = u.id " +
                     "INNER JOIN restaurante r ON ur.id_restaurante = r.id_restaurante "
                    +" WHERE rol=?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, "encargado");
            nueva.selectSQL(ps, dtm3);
        } catch (SQLException ex) {
            System.getLogger(JDialogInterfazClientes.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    public void formatoTabla(){
        FormatoTablas.FormatoInteger formatoInt = new FormatoTablas.FormatoInteger();
        
        jTableRestaurantes.getColumnModel().getColumn(0).setCellRenderer(formatoInt);
        jTableRestaurantes.getColumnModel().getColumn(3).setCellRenderer(formatoInt);
        jTableRestaurantes.getColumnModel().getColumn(5).setCellRenderer(formatoInt);
        jTableRestaurantes.getColumnModel().getColumn(6).setCellRenderer(formatoInt);
        jTableRestaurantes.getColumnModel().getColumn(7).setCellRenderer(formatoInt);
        /*
        jTableRestaurantes.getColumnModel().getColumn(0).setPreferredWidth(150); // Fecha y Hora (más ancho)
        jTableRestaurantes.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableRestaurantes.getColumnModel().getColumn(2).setPreferredWidth(100);// Comensales
        */
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAsignar;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonCerrarSesion1;
    private javax.swing.JButton jButtonEditarEncargado;
    private javax.swing.JButton jButtonEditarRestaurante;
    private javax.swing.JButton jButtonEliminarAsignacion;
    private javax.swing.JButton jButtonEliminarEncargado;
    private javax.swing.JButton jButtonEliminarRestaurante;
    private javax.swing.JButton jButtonValidarEncargado;
    private javax.swing.JButton jButtonValidarRestaurante;
    private javax.swing.JComboBox<String> jComboBoxEncargados;
    private javax.swing.JComboBox<String> jComboBoxRestaurantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelEncargados;
    private javax.swing.JPanel jPanelNuevo;
    private javax.swing.JPanel jPanelRestaurantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerApertura;
    private javax.swing.JSpinner jSpinnerCapacidad;
    private javax.swing.JSpinner jSpinnerCierre;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableAsignaciones;
    private javax.swing.JTable jTableEncargados;
    private javax.swing.JTable jTableRestaurantes;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldConfirmacionContrasena;
    private javax.swing.JTextField jTextFieldContrasena;
    private javax.swing.JTextField jTextFieldCorreoEncargado;
    private javax.swing.JTextField jTextFieldCorreoRestaurante;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombreEncargado;
    private javax.swing.JTextField jTextFieldNombreRestaurante;
    private javax.swing.JTextField jTextFieldTelefonoEncargado;
    private javax.swing.JTextField jTextFieldTelefonoRestaurante;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

    
    
}
