/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Gerente;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import servix.ConexionBBDD;
import servix.JFrameServix;

/**
 *
 * @author usuario
 */
public class JDialogEditarRestaurante extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEditarRestaurante.class.getName());

    /**
     * Creates new form JDialogEditarRestaurante
     */
    JFrameServix padre;
    Connection conexion;
    
    int id;    
    String nombre;
    String direccion;
    String telefono;
    String correo;
    int capacidad;
    int apertura;
    int cierre;
    
    public JDialogEditarRestaurante(java.awt.Frame parent, boolean modal, int id, String nombre, String direccion, String telefono, String correo, 
                                    int capacidad, int apertura, int cierre) {
        super(parent, modal);
        
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        this.setTitle("Servix");
        this.padre = (JFrameServix) parent;
        
        this.id = id;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
        this.correo = correo;
        this.capacidad = capacidad;
        this.apertura = apertura;
        this.cierre = cierre;
        cargarCampos();
        
        ConexionBBDD nuevaConexion = new ConexionBBDD();
        this.conexion = nuevaConexion.getConnection();
    }
    
    public void cargarCampos(){
        jTextFieldNombreRestaurante.setText(nombre);
        jTextFieldDireccion.setText(direccion);
        jTextFieldCorreoRestaurante.setText(correo);
        jTextFieldTelefonoRestaurante.setText(telefono);
        jSpinnerCapacidad.setValue(capacidad);
        jSpinnerApertura.setValue(apertura);
        jSpinnerCierre.setValue(cierre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreRestaurante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTelefonoRestaurante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCorreoRestaurante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerCapacidad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerApertura = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerCierre = new javax.swing.JSpinner();
        jButtonCancelar = new javax.swing.JButton();
        jButtonValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jPanel1.add(jTextFieldNombreRestaurante);

        jLabel2.setText("Direccion");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldDireccion);

        jLabel3.setText("Telefono");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldTelefonoRestaurante);

        jLabel4.setText("Correo");
        jPanel1.add(jLabel4);
        jPanel1.add(jTextFieldCorreoRestaurante);

        jLabel5.setText("Capacidad");
        jPanel1.add(jLabel5);
        jPanel1.add(jSpinnerCapacidad);

        jLabel6.setText("Apertura");
        jPanel1.add(jLabel6);
        jPanel1.add(jSpinnerApertura);

        jLabel7.setText("Cierre");
        jPanel1.add(jLabel7);
        jPanel1.add(jSpinnerCierre);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JDialogInterfazGerente jdig = new JDialogInterfazGerente(padre, true);
        jdig.setVisible(true);
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        if(!(jTextFieldNombreRestaurante.getText().isEmpty() || jTextFieldDireccion.getText().isEmpty() ||
             Integer.parseInt(String.valueOf(jSpinnerCapacidad.getValue()))<=0 || jTextFieldCorreoRestaurante.getText().isEmpty() ||
             Integer.parseInt(String.valueOf(jSpinnerApertura.getValue()))<=0 || Integer.parseInt(String.valueOf(jSpinnerCierre.getValue()))<=0)){
            
            
            try {
                conexion.setAutoCommit(false);
                String sql = "UPDATE restaurante SET nombre=?, direccion=?, telefono=?, correo=?, capacidad=?, apertura=?, cierre=?"
                    + " WHERE id_restaurante=?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                
                ps.setString(1, jTextFieldNombreRestaurante.getText());
                ps.setString(2, jTextFieldDireccion.getText());
                ps.setString(3, jTextFieldTelefonoRestaurante.getText());
                ps.setString(4, jTextFieldCorreoRestaurante.getText());
                ps.setInt(5, Integer.parseInt(String.valueOf(jSpinnerCapacidad.getValue())));
                ps.setInt(6, Integer.parseInt(String.valueOf(jSpinnerApertura.getValue())));
                ps.setInt(7, Integer.parseInt(String.valueOf(jSpinnerCierre.getValue())));
                ps.setInt(8, id);
                
                int filas = ps.executeUpdate();
                
                if(filas==1){
                    conexion.commit();
                    JOptionPane.showMessageDialog(rootPane, "Restaurante actualizado", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    JDialogInterfazGerente jdig = new JDialogInterfazGerente(padre, true);
                    jdig.recargarTablaRestaurantes();
                    jdig.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Ha habido un error", "Error", JOptionPane.ERROR_MESSAGE);
                }
  
            } catch (SQLException ex) {
                System.getLogger(JDialogEditarEncargado.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            } 
        }
        else{
            JOptionPane.showConfirmDialog(rootPane,
                                                "No puede haber campos vacios", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerApertura;
    private javax.swing.JSpinner jSpinnerCapacidad;
    private javax.swing.JSpinner jSpinnerCierre;
    private javax.swing.JTextField jTextFieldCorreoRestaurante;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombreRestaurante;
    private javax.swing.JTextField jTextFieldTelefonoRestaurante;
    // End of variables declaration//GEN-END:variables
}
