/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Gerente;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import servix.ConexionBBDD;
import servix.JFrameServix;
import servix.Login_CRUD.Encargado.JTableEmpleados;

/**
 *
 * @author usuario
 */
public class JDialogEditarRestaurante extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEditarRestaurante.class.getName());

    /**
     * Creates new form JDialogEditarRestaurante
     */
    JFrameServix padre;
    Connection conexion;
    
    int id;    
    String nombre;
    String direccion;
    String telefono;
    String correo;
    int capacidad;
    String apertura;
    String cierre;
    
    public JDialogEditarRestaurante(java.awt.Frame parent, boolean modal, int id, String nombre, String direccion, String telefono, String correo, 
                                    int capacidad, String apertura, String cierre) {
        super(parent, modal);
        
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        this.setTitle("Servix");
        this.padre = (JFrameServix) parent;
        
        this.id = id;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
        this.correo = correo;
        this.capacidad = capacidad;
        this.apertura = apertura;
        this.cierre = cierre;
        cargarCampos();
        
        // Mover el JFrame fuera de la pantalla para que no sea visible aunque se restaure
        padre.setLocation(-10000, -10000);
        padre.setSize(0, 0);

        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); // Sirve para la confirmacion de cerrar la aplicacion
        // Al cerrar el dialog muestra confirmacion para cerrar, cierra tambien el padre
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                int opcion = JOptionPane.showConfirmDialog(
                    JDialogEditarRestaurante.this,
                    "¿Seguro que quieres cerrar la aplicación?",
                    "Confirmar cierre",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
                );
                if (opcion == JOptionPane.YES_OPTION) {
                    JFrameServix.cerrarYReiniciar(JDialogEditarRestaurante.this, padre);
                }
            }
        });
        
        ConexionBBDD nuevaConexion = new ConexionBBDD();
        this.conexion = nuevaConexion.getConnection();
        
        atajosTeclado();
        
    }
    
    private void atajosTeclado(){
        //Ayuda
        if (JFrameServix.hb != null) {
            JFrameServix.hb.enableHelpKey(this.getContentPane(), "ayuda_crud_restaurantes", JFrameServix.hs);
        }
        
        // Escape - Cerrar
        getRootPane().registerKeyboardAction(
            e -> jButtonCancelar.doClick(),
            KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0),
            javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
        );
        
        // Ctrl+G - Guardar/Validar
        getRootPane().registerKeyboardAction(
            e -> jButtonValidar.doClick(),
            KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK),
            javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
        );
    }
    
    public void cargarCampos(){
        jTextFieldNombreRestaurante.setText(nombre);
        jTextFieldDireccion.setText(direccion);
        jTextFieldCorreoRestaurante.setText(correo);
        jTextFieldTelefonoRestaurante.setText(telefono);
        jSpinnerCapacidad.setValue(capacidad);
        
        // Normalizar a HH:mm:ss independientemente del formato que llegue
        String aperturaCompleta = apertura.length() == 5 ? apertura + ":00" : apertura;
        String cierreCompleto   = cierre.length()   == 5 ? cierre   + ":00" : cierre;

        jSpinnerApertura.setValue(new java.util.Date(Time.valueOf(aperturaCompleta).getTime()));
        jSpinnerCierre.setValue(new java.util.Date(Time.valueOf(cierreCompleto).getTime()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombreRestaurante = new javax.swing.JTextField();
        jLabelApellido1 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabelApellido2 = new javax.swing.JLabel();
        jTextFieldTelefonoRestaurante = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldCorreoRestaurante = new javax.swing.JTextField();
        jLabelCorreo = new javax.swing.JLabel();
        jSpinnerCapacidad = new javax.swing.JSpinner();
        jLabelUsuario = new javax.swing.JLabel();
        jSpinnerApertura = new javax.swing.JSpinner();
        jLabelContrasena1 = new javax.swing.JLabel();
        jSpinnerCierre = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(14, 168, 219), 1, true));
        jPanel1.setForeground(new java.awt.Color(250, 250, 250));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 30, 10));

        jLabelNombre.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre");
        jPanel1.add(jLabelNombre);
        jPanel1.add(jTextFieldNombreRestaurante);

        jLabelApellido1.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelApellido1.setText("Direccion");
        jPanel1.add(jLabelApellido1);
        jPanel1.add(jTextFieldDireccion);

        jLabelApellido2.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelApellido2.setText("Telefono");
        jPanel1.add(jLabelApellido2);
        jPanel1.add(jTextFieldTelefonoRestaurante);

        jLabelTelefono.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelTelefono.setText("Correo");
        jPanel1.add(jLabelTelefono);
        jPanel1.add(jTextFieldCorreoRestaurante);

        jLabelCorreo.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelCorreo.setText("Capacidad");
        jPanel1.add(jLabelCorreo);
        jPanel1.add(jSpinnerCapacidad);

        jLabelUsuario.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelUsuario.setText("Apertura");
        jPanel1.add(jLabelUsuario);

        jSpinnerApertura.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerApertura.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerApertura, "HH:mm"));
        jPanel1.add(jSpinnerApertura);

        jLabelContrasena1.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelContrasena1.setText("Cierre");
        jPanel1.add(jLabelContrasena1);

        jSpinnerCierre.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerCierre.setEditor(new javax.swing.JSpinner.DateEditor(jSpinnerCierre, "HH:mm"));
        jPanel1.add(jSpinnerCierre);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar restaurante");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonValidar.setBackground(new java.awt.Color(19, 118, 148));
        jButtonValidar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonValidar.setForeground(new java.awt.Color(219, 219, 255));
        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(497, Short.MAX_VALUE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(88, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JDialogInterfazGerente jdig = new JDialogInterfazGerente(padre, true);
        jdig.setVisible(true);

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        Time aperturaTiempo = new Time(((java.util.Date) jSpinnerApertura.getValue()).getTime());
        Time cierreTiempo = new Time(((java.util.Date) jSpinnerCierre.getValue()).getTime());

        if(jTextFieldNombreRestaurante.getText().isEmpty() || jTextFieldDireccion.getText().isEmpty() ||
            Integer.parseInt(String.valueOf(jSpinnerCapacidad.getValue())) <= 0 || 
            jTextFieldCorreoRestaurante.getText().isEmpty()){

            JOptionPane.showConfirmDialog(rootPane,
                "No puede haber campos vacios",
                "Error",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.ERROR_MESSAGE);

        }
        else if(aperturaTiempo.getTime() >= cierreTiempo.getTime()){
            JOptionPane.showConfirmDialog(rootPane,
                "La hora de apertura no puede ser posterior a la de cierre",
                "Error",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                conexion.setAutoCommit(false);
                String sql = "UPDATE restaurante SET nombre=?, direccion=?, telefono=?, correo=?, capacidad=?, apertura=?, cierre=?"
                + " WHERE id_restaurante=?";
                PreparedStatement ps = conexion.prepareStatement(sql);

                ps.setString(1, jTextFieldNombreRestaurante.getText());
                ps.setString(2, jTextFieldDireccion.getText());
                ps.setString(3, jTextFieldTelefonoRestaurante.getText());
                ps.setString(4, jTextFieldCorreoRestaurante.getText());
                ps.setInt(5, Integer.parseInt(String.valueOf(jSpinnerCapacidad.getValue())));
                ps.setTime(6, aperturaTiempo);
                ps.setTime(7, cierreTiempo);
                ps.setInt(8, id);

                int filas = ps.executeUpdate();

                if(filas==1){
                    conexion.commit();
                    JOptionPane.showMessageDialog(rootPane, "Restaurante actualizado", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    JDialogInterfazGerente jdig = new JDialogInterfazGerente(padre, true);
                    jdig.recargarTablaRestaurantes();
                    jdig.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Ha habido un error", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(JDialogEditarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelContrasena1;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerApertura;
    private javax.swing.JSpinner jSpinnerCapacidad;
    private javax.swing.JSpinner jSpinnerCierre;
    private javax.swing.JTextField jTextFieldCorreoRestaurante;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombreRestaurante;
    private javax.swing.JTextField jTextFieldTelefonoRestaurante;
    // End of variables declaration//GEN-END:variables
}
