/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Gerente;

import javax.swing.ImageIcon;
import servix.ConexionBBDD;
import servix.JFrameServix;
import java.sql.*;
import javax.swing.JOptionPane;
import servix.Login_CRUD.Clientes.JDialogInterfazClientes;

/**
 *
 * @author usuario
 */
public class JDialogEditarEncargado extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEditarEncargado.class.getName());

    /**
     * Creates new form JDialogEditarEncargado
     */
    
    JFrameServix padre;
    Connection conexion;
    
    int id_encargado;
    String nombreEncargado;
    String apellido1;
    String apellido2;
    String telefonoEncargado;
    String correoEncargado;
    String usuario;
    String contrasena;
    
    public JDialogEditarEncargado(java.awt.Frame parent, boolean modal, int id_encargado, String nombreEncargado, String apellido1, String apellido2, String telefonoEncargado,
                                    String correoEncargado, String usuario, String contrasena) {
        
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        this.setTitle("Servix");
        this.padre = (JFrameServix) parent;
        
        this.id_encargado = id_encargado;
        this.nombreEncargado = nombreEncargado;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.telefonoEncargado = telefonoEncargado;
        this.correoEncargado = correoEncargado;
        this.usuario = usuario;
        this.contrasena = contrasena;
        cargarCampos();
        
        ConexionBBDD nuevaConexion = new ConexionBBDD();
        this.conexion = nuevaConexion.getConnection();
    }
    public void cargarCampos(){
        jTextFieldNombreEncargado.setText(nombreEncargado);
        jTextFieldApellido1.setText(apellido1);
        jTextFieldApellido2.setText(apellido2);
        jTextFieldCorreoEncargado.setText(correoEncargado);
        jTextFieldTelefonoEncargado.setText(telefonoEncargado);
        jTextFieldUsuario.setText(usuario);
        jTextFieldContrasena.setText(contrasena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreEncargado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTelefonoEncargado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCorreoEncargado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldContrasena = new javax.swing.JTextField();
        jButtonValidar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jPanel1.add(jTextFieldNombreEncargado);

        jLabel2.setText("Primer apellido");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldApellido1);

        jLabel3.setText("Segundo apellido");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldApellido2);

        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4);
        jPanel1.add(jTextFieldTelefonoEncargado);

        jLabel5.setText("Correo");
        jPanel1.add(jLabel5);
        jPanel1.add(jTextFieldCorreoEncargado);

        jLabel6.setText("Usuario");
        jPanel1.add(jLabel6);
        jPanel1.add(jTextFieldUsuario);

        jLabel7.setText("Contraseña");
        jPanel1.add(jLabel7);
        jPanel1.add(jTextFieldContrasena);

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 171, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(262, 262, 262))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonValidar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JDialogInterfazGerente jdig = new JDialogInterfazGerente(padre, true);
        jdig.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        if(!(jTextFieldNombreEncargado.getText().isEmpty() || jTextFieldApellido1.getText().isEmpty() ||
             jTextFieldApellido2.getText().isEmpty() || jTextFieldCorreoEncargado.getText().isEmpty() ||
             jTextFieldTelefonoEncargado.getText().isEmpty() || jTextFieldUsuario.getText().isEmpty() ||
             jTextFieldContrasena.getText().isEmpty())){
            
            try {
                conexion.setAutoCommit(false);
                String sql = "UPDATE usuario SET nombre=?, apellido1=?, apellido2=?, telefono=?, correo=?, usuario_login=?, contrasenya_login=?"
                    + " WHERE id=?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                
                ps.setString(1, jTextFieldNombreEncargado.getText());
                ps.setString(2, jTextFieldApellido1.getText());
                ps.setString(3, jTextFieldApellido2.getText());
                ps.setString(4, jTextFieldTelefonoEncargado.getText());
                ps.setString(5, jTextFieldCorreoEncargado.getText());
                ps.setString(6, jTextFieldUsuario.getText());
                ps.setString(7, jTextFieldContrasena.getText());
                ps.setInt(8, id_encargado);
                
                int filas = ps.executeUpdate();
                
                if(filas==1){
                    conexion.commit();
                    JOptionPane.showMessageDialog(rootPane, "Encargado actualizado", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    JDialogInterfazGerente jdig = new JDialogInterfazGerente(padre, true);
                    jdig.recargarTablaEncargados();
                    jdig.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Ha habido un error", "Error", JOptionPane.ERROR_MESSAGE);
                }
  
            } catch (SQLException ex) {
                System.getLogger(JDialogEditarEncargado.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            } 
        }
        else{
            JOptionPane.showConfirmDialog(rootPane,
                                                "No puede haber campos vacios", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldContrasena;
    private javax.swing.JTextField jTextFieldCorreoEncargado;
    private javax.swing.JTextField jTextFieldNombreEncargado;
    private javax.swing.JTextField jTextFieldTelefonoEncargado;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
