/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Empleado;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import servix.ConexionBBDD;
import servix.Seguridad;
import java.sql.Connection;
import servix.Login_CRUD.Encargado.JDialogLoginEncargado;

/**
 *
 * @author DAM2Alu11
 */
public class JDialogLoginEmpleados extends javax.swing.JDialog {
    
    ConexionBBDD nueva;
    Connection conexion;
    int id;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogLoginEmpleados.class.getName());

    /**
     * Creates new form JDialogLoginEmpleados
     */
    
    public JDialogLoginEmpleados(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        initComponents();
        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING)); // si se cierra otra pestaña se cierra esta

    }
    
    public JDialogLoginEmpleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        initComponents();
        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING)); // si se cierra otra pestaña se cierra esta

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFielduser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldContransena = new javax.swing.JPasswordField();
        jButtonEncargado = new javax.swing.JButton();
        jButtonIniciarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INICIAR SESION");
        jPanel1.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        jLabel3.setText("Usuario");
        jPanel2.add(jLabel3);
        jPanel2.add(jTextFielduser);

        jLabel4.setText("Contraseña*");
        jPanel2.add(jLabel4);
        jPanel2.add(jPasswordFieldContransena);

        jButtonEncargado.setText("Soy encargado");
        jButtonEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncargadoActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEncargado);

        jButtonIniciarSesion.setText("Iniciar sesion");
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonIniciarSesion);

        jLabel1.setText("* si es tu primera vez iniciando sesion la contraseña es 1234");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(228, 228, 228))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        char[] contrasena = jPasswordFieldContransena.getPassword();
         String stringContrasena = new String(contrasena);
        if(comprobarDatos(jTextFielduser.getText(), stringContrasena)){
            if(comprobarInicioSesion(jTextFielduser.getText())==false){
                this.setVisible(false);
                this.dispose();
                JDialogCambiarContrasena jdcc = new JDialogCambiarContrasena(this, true, jTextFielduser.getText());
                jdcc.setVisible(true);
            }else{
                this.setVisible(false);
                this.dispose();
                JTableInterfazEmpleados jtie = new JTableInterfazEmpleados(this, true);
                jtie.setVisible(true);
            } 
        }else{
        }
    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    private void jButtonEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncargadoActionPerformed
        this.setVisible(false);
        this.dispose();
        JDialogLoginEncargado jdle = new JDialogLoginEncargado(this, true);
        jdle.setVisible(true);
    }//GEN-LAST:event_jButtonEncargadoActionPerformed

    private boolean comprobarDatos(String user, String contrasena) {
        boolean correcto=false;
        try {
            if(user.isEmpty() || user.equals("")|| contrasena.isEmpty() || contrasena.equals("")){
           
                JOptionPane.showConfirmDialog(rootPane,
                                            "Porfavor rellene todos los campos", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
            }else{   
            
                nueva.conectar();
                String sql = "SELECT * FROM Camarero WHERE usuario_login = ?";
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setString(1, user);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    id = rs.getInt("id_camarero");
                    String contrasenaHash = rs.getString("contrasenya_login");
                    if (id != 0 && Seguridad.checkPassword(contrasena, contrasenaHash)) {
                        correcto= true;
                    }
                }else{
                     JOptionPane.showConfirmDialog(rootPane,
                                            "Usuario o contraseña incorrectos", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
                      correcto =  false;
                }

                rs.close();
                ps.close();
            }
        } catch (SQLException ex) {
             System.getLogger(JDialogLoginEmpleados.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } finally {
            nueva.cerrar();
        }
           return correcto;
    } //comprobar datos
    
    public boolean comprobarInicioSesion(String user){
        try {
            nueva.conectar();
            String sql = "SELECT haIniciadoSesion FROM Camarero WHERE usuario_login = ?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, user);
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                if(rs.getBoolean("haIniciadoSesion")==false){
                    return false;
                }
                return true;
            }
        } catch (SQLException ex) {
            System.getLogger(JDialogLoginEmpleados.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEncargado;
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldContransena;
    private javax.swing.JTextField jTextFielduser;
    // End of variables declaration//GEN-END:variables
}
