/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Empleado;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import servix.ConexionBBDD;
import servix.Reserva;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import servix.FormatoTablas;
import servix.JFrameServix;
import servix.Login_CRUD.Encargado.JDialogInterfazEncargado;

/**
 *
    * @author DAM2ALU11
 */
public class JTableInterfazEmpleado extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JTableInterfazEmpleado.class.getName());

    /**
     * Creates new form JDialogInterfazEmpleados
     */
    ConexionBBDD nueva;
    Connection conexion;
    DefaultTableModel dtm;
    ArrayList<Reserva> lista = new ArrayList<>();
    java.sql.Date fecha_sql;
    JFrameServix padre;
    String rol;
    
    public JTableInterfazEmpleado(String rol, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        this.setTitle("Servix");
        this.padre = (JFrameServix) parent;
        this.rol= rol;
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        dtm= new DefaultTableModel();
        jTableReservasDelDia.setModel(dtm);
        dtm.setColumnIdentifiers(Reserva.getColumnas());
        rellenarDiaHoy();
        jLabel1.setText("Bienvenido/a");
        aplicarFormato();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReservasDelDia = new javax.swing.JTable();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jButtonBuscarFecha = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido/a, consulta las reservas del día");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jTableReservasDelDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableReservasDelDia);

        jButtonBuscarFecha.setText("Buscar fecha");
        jButtonBuscarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarFechaActionPerformed(evt);
            }
        });

        jLabel2.setText("Alba Pallas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonBuscarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonBuscarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarFechaActionPerformed
        Date mfecha = jDateChooserFecha.getDate();
        if(mfecha != null) {
            LocalDate fecha = mfecha.toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();
            escribirReservas(fecha);
        }
    }//GEN-LAST:event_jButtonBuscarFechaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        if(rol.equalsIgnoreCase("encargado")){
            jButtonSalir.setText("Volver");
            this.setVisible(false);
            this.dispose();
            JDialogInterfazEncargado jdie = new JDialogInterfazEncargado(padre, true);
            jdie.setVisible(true);
        }else if(rol.equalsIgnoreCase("empleado")){
            this.setVisible(false);
            this.dispose();
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        }        
    }//GEN-LAST:event_jButtonSalirActionPerformed
    
    public void escribirReservas(LocalDate fecha){
        try {
            lista.clear();
            nueva.conectar();
            String sql = "SELECT * FROM Reserva WHERE DATE(fecha_hora) = ? ";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setObject(1, fecha);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                Reserva r = new Reserva(
                    rs.getInt("id_reserva"),
                    rs.getString("estado_reserva"),
                    rs.getInt("n_comensales"),
                    rs.getObject("fecha_hora", LocalDateTime.class),
                    rs.getInt("id_cliente"),
                    rs.getInt("id_mesa")
                );
                lista.add(r);
            }
            for (int i = 0; i < lista.size(); i++) {
                dtm.addRow(lista.get(i).devuelveFila());
            }
        } catch (SQLException ex) {
            System.getLogger(JTableInterfazEmpleado.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    public void rellenarDiaHoy(){
        escribirReservas(LocalDate.now());
    }
    
     public void aplicarFormato(){
        FormatoTablas.FormatoInteger formatoInt = new FormatoTablas.FormatoInteger();
        FormatoTablas.FormatoFecha formatoFecha = new FormatoTablas.FormatoFecha();
        
        jTableReservasDelDia.getColumnModel().getColumn(0).setCellRenderer(formatoInt); //ID Reserva
        jTableReservasDelDia.getColumnModel().getColumn(2).setCellRenderer(formatoInt); //Comensales
        jTableReservasDelDia.getColumnModel().getColumn(3).setCellRenderer(formatoFecha); //Fecha_hora
        jTableReservasDelDia.getColumnModel().getColumn(4).setCellRenderer(formatoInt); //ID Cliente
        jTableReservasDelDia.getColumnModel().getColumn(5).setCellRenderer(formatoInt); //ID Mesa
        
        jTableReservasDelDia.getColumnModel().getColumn(0).setPreferredWidth(80);  // ID Reserva
        jTableReservasDelDia.getColumnModel().getColumn(1).setPreferredWidth(120); // Estado
        jTableReservasDelDia.getColumnModel().getColumn(2).setPreferredWidth(100); // Comensales
        jTableReservasDelDia.getColumnModel().getColumn(3).setPreferredWidth(150); // Fecha_Hora
        jTableReservasDelDia.getColumnModel().getColumn(4).setPreferredWidth(90);  // ID Cliente
        jTableReservasDelDia.getColumnModel().getColumn(5).setPreferredWidth(80);  // ID Mesa
     }
     
    public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarFecha;
    private javax.swing.JButton jButtonSalir;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReservasDelDia;
    // End of variables declaration//GEN-END:variables
}
