/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.Login_CRUD.Usuario;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import servix.ConexionBBDD;
import servix.JFrameServix;
import servix.Login_CRUD.Encargado.JDialogEditarEncargado;
import servix.Seguridad;


/**
 *
 * @author DAM2Alu11
 */
public class JDialogEditarUsuario extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEditarUsuario.class.getName());

    /**
     * Creates new form JDialogEditarUsuario
     */
    ConexionBBDD nueva;
    Connection conexion;
    String id;
    
    public JDialogEditarUsuario(String id) {
        initComponents();
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        Provincia = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldContrasena1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFieldContrasena2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDITAR CUENTA");

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldNombre);

        jLabel3.setText("Primer apellido");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldApellido1);

        Provincia.setText("Segundo apellido");
        jPanel1.add(Provincia);
        jPanel1.add(jTextFieldApellido2);

        jLabel5.setText("Telefono");
        jPanel1.add(jLabel5);
        jPanel1.add(jTextFieldTelefono);

        jLabel4.setText("Correo");
        jPanel1.add(jLabel4);

        jTextFieldCorreo.setToolTipText("");
        jPanel1.add(jTextFieldCorreo);

        jLabel6.setText("Contraseña");
        jPanel1.add(jLabel6);
        jPanel1.add(jPasswordFieldContrasena1);

        jLabel8.setText("Introduzca de nuevo la contraseña");
        jPanel1.add(jLabel8);
        jPanel1.add(jPasswordFieldContrasena2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        String nombre = jTextFieldNombre.getText();
        String apellido1 = jTextFieldApellido1.getText();
        String apellido2 = jTextFieldApellido2.getText();
        String telefono = jTextFieldTelefono.getText();
        String correo = jTextFieldCorreo.getText();
        char[] contrasena = jPasswordFieldContrasena1.getPassword();
        char[] contrasena2 = jPasswordFieldContrasena2.getPassword();
        
        String stringContrasena1 = new String(contrasena);
        String stringContrasena2 = new String(contrasena2);
       
       if(nombre.isEmpty() || apellido1.isEmpty() || telefono.isEmpty() || correo.isEmpty() || contrasena.length == 0 || contrasena2.length == 0){
                JOptionPane.showConfirmDialog(rootPane,
                                            "Porfavor rellene todos los campos", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
        }else{
            if(nombre.length() > 30 || apellido1.length() > 30 || apellido2.length() > 30 ||  telefono.length() > 30 || correo.length() > 30){
             JOptionPane.showConfirmDialog(rootPane,
                                        "Ningun campo puede exceder los 30 caracteres", 
                                        "Error", 
                                        JOptionPane.OK_CANCEL_OPTION, 
                                        JOptionPane.ERROR_MESSAGE);
            }else{
                if(stringContrasena1.equals(stringContrasena2)){ // Se comprueba que las contraseñas sean iguales
                     String contrasenaEncriptada = Seguridad.hashPassword(stringContrasena1); // contraseña ya encriptada
                     this.setVisible(false);

                     try {
                         nueva.conectar();

                            String sql = "UPDATE Encargado SET nombre = ?, apellido1 = ?, apellido2 = ?, telefono = ?, correo = ?, contrasenya_login = ? WHERE usuario_login = ?";
                            PreparedStatement ps = conexion.prepareStatement(sql);
                            ps.setString(1, jTextFieldNombre.getText());
                            ps.setString(2, jTextFieldApellido1.getText());
                            ps.setString(3, jTextFieldApellido2.getText());
                            ps.setString(4, jTextFieldTelefono.getText());
                            ps.setString(5, jTextFieldCorreo.getText());
                            ps.setString(6, contrasenaEncriptada);
                            ps.setString(7, sql);

                            ps.executeUpdate();
                            ps.close();
                            
                            JFrameServix jfs = new JFrameServix();
                            jfs.setVisible(true);
                    } catch (SQLException ex) {
                         System.getLogger(JDialogEditarEncargado.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                }else{
                     JOptionPane.showConfirmDialog(rootPane,
                                             "Las contraseñas no coinciden", 
                                             "Error", 
                                             JOptionPane.OK_CANCEL_OPTION, 
                                             JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogEditarUsuario dialog = new JDialogEditarUsuario(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Provincia;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContrasena1;
    private javax.swing.JPasswordField jPasswordFieldContrasena2;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
