/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package servix.Login_CRUD.Usuario;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import servix.ConexionBBDD;
import servix.Seguridad;

/**
 *
 * @author DAM2Alu11
 */
public class JDialogAltaUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAltaUsuario.class.getName());

    /**
     * Creates new form JDialogAltaUsuario
     */
    
    ConexionBBDD nueva;
    Connection conexion;
    String rol;
    
    public JDialogAltaUsuario(String rol) {
        initComponents();
        this.setTitle("Servix");
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        this.rol = rol;
        comprobarLongitudTelefono();
        comprobarLongitudes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAlta = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        Provincia = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldContrasena1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFieldContrasena2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAlta.setText("Aceptar");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR CUENTA");

        jPanel1.setLayout(new java.awt.GridLayout(8, 2, 10, 10));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldNombre);

        jLabel3.setText("Primer apellido");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldApellido1);

        Provincia.setText("Segundo apellido");
        jPanel1.add(Provincia);
        jPanel1.add(jTextFieldApellido2);

        jLabel5.setText("Telefono");
        jPanel1.add(jLabel5);
        jPanel1.add(jTextFieldTelefono);

        jLabel6.setText("Correo");
        jPanel1.add(jLabel6);
        jPanel1.add(jTextFieldCorreo);

        jLabel7.setText("Usuario");
        jPanel1.add(jLabel7);
        jPanel1.add(jTextFieldUser);

        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4);
        jPanel1.add(jPasswordFieldContrasena1);

        jLabel8.setText("Introduzca de nuevo la contraseña");
        jPanel1.add(jLabel8);
        jPanel1.add(jPasswordFieldContrasena2);

        jLabel9.setText("Alba Pallas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        String nombre = jTextFieldNombre.getText();
        String apellido1 = jTextFieldApellido1.getText();
        String apellido2 = jTextFieldApellido2.getText();
        String telefono = jTextFieldTelefono.getText();
        String correo = jTextFieldCorreo.getText();
        String user =  jTextFieldUser.getText();
        char[] contrasena = jPasswordFieldContrasena1.getPassword();
        char[] contrasena2 = jPasswordFieldContrasena2.getPassword();
        
        String stringContrasena1 = new String(contrasena);
        String stringContrasena2 = new String(contrasena2);
       
        if(!existeUsuario(user)){
            if(nombre.isEmpty() || apellido1.isEmpty() || telefono.isEmpty() || correo.isEmpty() || user.isEmpty() || contrasena.length == 0 || contrasena2.length == 0){
                if(nombre.isEmpty()) resaltarCampo(jTextFieldNombre); else resetearCampo(jTextFieldNombre);
                if(apellido1.isEmpty()) resaltarCampo(jTextFieldApellido1); else resetearCampo(jTextFieldApellido1);
                if(apellido2.isEmpty()) resaltarCampo(jTextFieldApellido2); else resetearCampo(jTextFieldApellido2);
                if(telefono.isEmpty()) resaltarCampo(jTextFieldTelefono); else resetearCampo(jTextFieldTelefono);
                if(correo.isEmpty()) resaltarCampo(jTextFieldCorreo); else resetearCampo(jTextFieldCorreo);
                if(user.isEmpty()) resaltarCampo(jTextFieldUser); else resetearCampo(jTextFieldUser);
                if(contrasena.length == 0) resaltarCampo(jPasswordFieldContrasena1); else resetearPassword(jPasswordFieldContrasena1);
                if(contrasena2.length == 0) resaltarCampo(jPasswordFieldContrasena2); else resetearCampo(jPasswordFieldContrasena2);
                
                JOptionPane.showConfirmDialog(rootPane,
                                            "Porfavor rellene todos los campos", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
           }else{
                if(nombre.length() > 30 || apellido1.length() > 30 || apellido2.length() > 30 ||  telefono.length() > 30 || correo.length() > 30 || user.length() > 30){
                    if(nombre.length() > 30) resaltarCampo(jTextFieldNombre); else resetearCampo(jTextFieldNombre);
                    if(apellido1.length() > 30) resaltarCampo(jTextFieldApellido1);  else resetearCampo(jTextFieldApellido1);
                    if(apellido2.length() > 30) resaltarCampo(jTextFieldApellido2); else resetearCampo(jTextFieldApellido2);
                    if(telefono.length() > 30) resaltarCampo(jTextFieldTelefono); else resetearCampo(jTextFieldTelefono);
                    if(correo.length() > 30) resaltarCampo(jTextFieldCorreo); else resetearCampo(jTextFieldCorreo);
                    if(user.length() > 30) resaltarCampo(jTextFieldUser); else resetearCampo(jTextFieldUser);

                    JOptionPane.showConfirmDialog(rootPane,
                                            "Ningun campo puede exceder los 30 caracteres", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
                }else{
                    if(validarTelefono(telefono)){ //Comprobamos si el formato de telefono es valido
                        if(validarEmail(correo)){ //Comprobamos si el formato de correo es valido
                            if(stringContrasena1.equals(stringContrasena2)){ // Se comprueba que las contraseñas sean iguales
                                 String contrasenaEncriptada = Seguridad.hashPassword(stringContrasena1); // contraseña ya encriptada
                                 this.setVisible(false);

                                 try {
                                     nueva.conectar();
                                     String sql= "INSERT INTO Cliente(nombre, apellido1, apellido2, telefono, correo, usuario_login, contrasenya_login) VALUES (?,?,?,?,?,?,?)";
                                     PreparedStatement ps= conexion.prepareStatement(sql);
                                     ps.setString(1, jTextFieldNombre.getText());
                                     ps.setString(2, jTextFieldApellido1.getText());
                                     ps.setString(3, jTextFieldApellido2.getText());
                                     ps.setString(4, jTextFieldTelefono.getText());
                                     ps.setString(5, jTextFieldCorreo.getText());
                                     ps.setString(6, jTextFieldUser.getText());
                                     ps.setString(7, contrasenaEncriptada);

                                     ps.executeUpdate();
                                     ps.close();
                                     conexion.close();
                                 } catch (SQLException ex) {
                                     System.getLogger(JDialogAltaUsuario.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                                 }
                            }else{
                                resaltarPassword(jPasswordFieldContrasena1);
                                resaltarPassword(jPasswordFieldContrasena2);
                                JOptionPane.showConfirmDialog(rootPane,
                                                        "Las contraseñas no coinciden", 
                                                        "Error", 
                                                        JOptionPane.OK_CANCEL_OPTION, 
                                                        JOptionPane.ERROR_MESSAGE);
                            }
                        }else{
                            resaltarCampo(jTextFieldCorreo);
                            JOptionPane.showConfirmDialog(rootPane,
                                                    "Formato de correo no valido", 
                                                    "Error", 
                                                    JOptionPane.OK_CANCEL_OPTION, 
                                                    JOptionPane.ERROR_MESSAGE);
                       }
                    }else{
                        resaltarCampo(jTextFieldTelefono);
                        JOptionPane.showConfirmDialog(rootPane,
                                                "Formato de telefono no valido", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
                   }
                } 
 
            }
        }else{
            resaltarCampo(jTextFieldUser);
            JOptionPane.showConfirmDialog(rootPane,
                                                "El usuario " + user + " ya existe", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    public boolean existeUsuario(String usuario){
        boolean existe= false;
        try {    
            nueva.conectar();
            String sql = "SELECT * FROM Usuario WHERE usuario_login = ?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, usuario);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) 
                existe = true;
                        
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            System.getLogger(JDialogAltaUsuario.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        return existe;
    }
    
    public void comprobarLongitudTelefono(){
        jTextFieldTelefono.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
        
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                comprobarLongitud();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                 comprobarLongitud();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                 comprobarLongitud();
            }
            
            private void comprobarLongitud(){
                if(jTextFieldTelefono.getText().length() < 9){
                    jTextFieldTelefono.setBackground(new java.awt.Color(255, 200, 200));
                    jTextFieldTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
                }else{
                    jTextFieldTelefono.setBackground(java.awt.Color.WHITE);
                    jTextFieldTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 1));
                }
            }
            
        });
    }
    
    public void comprobarLongitudes(){
        javax.swing.event.DocumentListener listener = new javax.swing.event.DocumentListener(){
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                validarLongitud(e);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                validarLongitud(e);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                validarLongitud(e);
            }

            private void validarLongitud(javax.swing.event.DocumentEvent e){
                javax.swing.text.Document doc = e.getDocument();
                javax.swing.JTextField campo = null;

                // Identificar qué campo se está editando
                if (doc == jTextFieldNombre.getDocument()) campo = jTextFieldNombre;
                else if (doc == jTextFieldApellido1.getDocument()) campo = jTextFieldApellido1;
                else if (doc == jTextFieldApellido2.getDocument()) campo = jTextFieldApellido2;
                else if (doc == jTextFieldCorreo.getDocument()) campo = jTextFieldCorreo;
                else if (doc == jTextFieldUser.getDocument()) campo = jTextFieldUser;

                if(campo != null){
                    if(campo.getText().length() > 30){
                        campo.setBackground(new java.awt.Color(255, 200, 200));
                        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
                    }else{
                        campo.setBackground(java.awt.Color.WHITE);
                        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 1));
                    }
                }
            }
        };

        // Aplicar el listener a todos los campos con límite de 30 caracteres
        jTextFieldNombre.getDocument().addDocumentListener(listener);
        jTextFieldApellido1.getDocument().addDocumentListener(listener);
        jTextFieldApellido2.getDocument().addDocumentListener(listener);
        jTextFieldCorreo.getDocument().addDocumentListener(listener);
        jTextFieldUser.getDocument().addDocumentListener(listener);
    }
    
    private static final Pattern PATTERN_EMAIL = Pattern.compile( //Patron para validar el email
        "^[A-Za-z0-9_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$" // se permiten letras, simbolos, tiene que haber un @
                                                          // y un . , el dominio tiene que tener 2 letras
    );
    
    private static final Pattern PATTERN_TELEFONO = Pattern.compile( //Patron para validar el telefono
        "^[0-9]{9}$" // 9 Numeros del 0-9
    );

     public static boolean validarEmail(String correo) { //Compobamos que el correo cumpla el patron
        if (!PATTERN_EMAIL.matcher(correo).matches()) { 
            return false;
        }
        return true;
    }
     
    public static boolean validarTelefono(String telefono) { //Comprobamos que el telefono cumpla el patron
        if (!PATTERN_TELEFONO.matcher(telefono).matches()) {
            return false;
        }
        return true;
    }
    
    private void resaltarCampo(javax.swing.JTextField campo) {
        campo.setBackground(new java.awt.Color(255, 200, 200));
        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));    
    }
    
    private void resetearCampo(javax.swing.JTextField campo) {
        campo.setBackground(java.awt.Color.WHITE);
        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 1));
    }
    
    private void resaltarPassword(javax.swing.JPasswordField campo) {
        campo.setBackground(new java.awt.Color(255, 200, 200));
        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));    
    }
    
     private void resetearPassword(javax.swing.JPasswordField campo) {
        campo.setBackground(java.awt.Color.WHITE);
        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 1));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JDialogAltaUsuario(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Provincia;
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContrasena1;
    private javax.swing.JPasswordField jPasswordFieldContrasena2;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
