/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package servix.Login_CRUD.Usuario;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import servix.ConexionBBDD;
import servix.JFrameServix;
import servix.Seguridad;

/**
 *
 * @author DAM2Alu11
 */
public class JDialogAltaUsuario extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAltaUsuario.class.getName());

    /**
     * Creates new form JDialogAltaUsuario
     */
    
    ConexionBBDD nueva;
    Connection conexion;
    String rol;
    JFrameServix padre;
    boolean editar;
    String sql;
    int id;
    
    public JDialogAltaUsuario(String rol, int id, java.awt.Frame parent, boolean modal, boolean editar) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        this.setTitle("Servix");
        this.getContentPane().setBackground(Color.decode("#EFF7FB"));
        jPanel1.setBackground(Color.decode("#FAFAFA"));
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        this.rol = rol;
        this.padre=(JFrameServix) parent;
        this.editar = editar;
        this.id= id;
        comprobarLongitudTelefono();
        comprobarLongitudes();
        enterEnFormulario();
        camposObligatorios();
        if(editar){
            jLabel1.setText("Editar usuario");
            cargarDatosUsuario(id);
            jTextFieldUser.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAlta = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido1 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jLabelApellido2 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelCorreo = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabelContrasena1 = new javax.swing.JLabel();
        jPasswordFieldContrasena1 = new javax.swing.JPasswordField();
        jLabelContrasena2 = new javax.swing.JLabel();
        jPasswordFieldContrasena2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(239, 247, 251));

        jButtonAlta.setBackground(new java.awt.Color(19, 118, 148));
        jButtonAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAlta.setForeground(new java.awt.Color(219, 219, 255));
        jButtonAlta.setText("Aceptar");
        jButtonAlta.setBorderPainted(false);
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrarse");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(14, 168, 219), 1, true));
        jPanel1.setForeground(new java.awt.Color(250, 250, 250));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.GridLayout(8, 2, 30, 10));

        jLabelNombre.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre");
        jPanel1.add(jLabelNombre);
        jPanel1.add(jTextFieldNombre);

        jLabelApellido1.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelApellido1.setText("Primer apellido");
        jPanel1.add(jLabelApellido1);
        jPanel1.add(jTextFieldApellido1);

        jLabelApellido2.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelApellido2.setText("Segundo apellido");
        jPanel1.add(jLabelApellido2);
        jPanel1.add(jTextFieldApellido2);

        jLabelTelefono.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelTelefono.setText("Telefono");
        jPanel1.add(jLabelTelefono);
        jPanel1.add(jTextFieldTelefono);

        jLabelCorreo.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelCorreo.setText("Correo");
        jPanel1.add(jLabelCorreo);
        jPanel1.add(jTextFieldCorreo);

        jLabelUsuario.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelUsuario.setText("Usuario");
        jPanel1.add(jLabelUsuario);
        jPanel1.add(jTextFieldUser);

        jLabelContrasena1.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelContrasena1.setText("Contraseña");
        jPanel1.add(jLabelContrasena1);
        jPanel1.add(jPasswordFieldContrasena1);

        jLabelContrasena2.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabelContrasena2.setText("Introduzca de nuevo la contraseña");
        jPanel1.add(jLabelContrasena2);
        jPanel1.add(jPasswordFieldContrasena2);

        jLabel9.setText("Alba Pallas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        String nombre = jTextFieldNombre.getText();
        String apellido1 = jTextFieldApellido1.getText();
        String apellido2 = jTextFieldApellido2.getText();
        String telefono = jTextFieldTelefono.getText();
        String correo = jTextFieldCorreo.getText();
        String user =  jTextFieldUser.getText();
        char[] contrasena = jPasswordFieldContrasena1.getPassword();
        char[] contrasena2 = jPasswordFieldContrasena2.getPassword();
        
        String stringContrasena1 = new String(contrasena);
        String stringContrasena2 = new String(contrasena2);
       
        if(!existeUsuario(user)){
            if(nombre.isEmpty() || apellido1.isEmpty() || telefono.isEmpty() || correo.isEmpty() || user.isEmpty() || contrasena.length == 0 || contrasena2.length == 0){
                if(nombre.isEmpty()) resaltarCampo(jTextFieldNombre); else resetearCampo(jTextFieldNombre);
                if(apellido1.isEmpty()) resaltarCampo(jTextFieldApellido1); else resetearCampo(jTextFieldApellido1);
                if(apellido2.isEmpty()) resaltarCampo(jTextFieldApellido2); else resetearCampo(jTextFieldApellido2);
                if(telefono.isEmpty()) resaltarCampo(jTextFieldTelefono); else resetearCampo(jTextFieldTelefono);
                if(correo.isEmpty()) resaltarCampo(jTextFieldCorreo); else resetearCampo(jTextFieldCorreo);
                if(user.isEmpty()) resaltarCampo(jTextFieldUser); else resetearCampo(jTextFieldUser);
                if(contrasena.length == 0) resaltarCampo(jPasswordFieldContrasena1); else resetearPassword(jPasswordFieldContrasena1);
                if(contrasena2.length == 0) resaltarCampo(jPasswordFieldContrasena2); else resetearCampo(jPasswordFieldContrasena2);
                
                JOptionPane.showConfirmDialog(rootPane,
                                            "Porfavor rellene todos los campos", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
           }else{
                if(nombre.length() > 30 || apellido1.length() > 30 || apellido2.length() > 30 ||  telefono.length() > 30 || correo.length() > 30 || user.length() > 30){
                    if(nombre.length() > 30) resaltarCampo(jTextFieldNombre); else resetearCampo(jTextFieldNombre);
                    if(apellido1.length() > 30) resaltarCampo(jTextFieldApellido1);  else resetearCampo(jTextFieldApellido1);
                    if(apellido2.length() > 30) resaltarCampo(jTextFieldApellido2); else resetearCampo(jTextFieldApellido2);
                    if(telefono.length() > 30) resaltarCampo(jTextFieldTelefono); else resetearCampo(jTextFieldTelefono);
                    if(correo.length() > 30) resaltarCampo(jTextFieldCorreo); else resetearCampo(jTextFieldCorreo);
                    if(user.length() > 30) resaltarCampo(jTextFieldUser); else resetearCampo(jTextFieldUser);

                    JOptionPane.showConfirmDialog(rootPane,
                                            "Ningun campo puede exceder los 30 caracteres", 
                                            "Error", 
                                            JOptionPane.OK_CANCEL_OPTION, 
                                            JOptionPane.ERROR_MESSAGE);
                }else{
                    if(validarTelefono(telefono)){ //Comprobamos si el formato de telefono es valido
                        if(validarEmail(correo)){ //Comprobamos si el formato de correo es valido
                            if(stringContrasena1.equals(stringContrasena2)){ // Se comprueba que las contraseñas sean iguales
                                 String contrasenaEncriptada = Seguridad.hashPassword(stringContrasena1); // contraseña ya encriptada
                                 this.setVisible(false);

                                 try {
                                     nueva.conectar();
                                     if(editar){
                                        sql = "UPDATE Usuario SET nombre = ?, apellido1 = ?, apellido2 = ?, telefono = ?, correo = ?, contrasenya_login = ? WHERE usuario_login = ?";
                                        PreparedStatement ps = conexion.prepareStatement(sql);
                                        ps.setString(1, jTextFieldNombre.getText());
                                        ps.setString(2, jTextFieldApellido1.getText());
                                        ps.setString(3, jTextFieldApellido2.getText());
                                        ps.setString(4, jTextFieldTelefono.getText());
                                        ps.setString(5, jTextFieldCorreo.getText());
                                        ps.setString(6, contrasenaEncriptada);
                                        ps.setInt(7, id);

                                        ps.executeUpdate();
                                        ps.close();

                                     }else{
                                        sql= "INSERT INTO Usuario(nombre, apellido1, apellido2, telefono, correo, usuario_login, contrasenya_login, rol) VALUES (?,?,?,?,?,?,?,?)";
                                        PreparedStatement ps= conexion.prepareStatement(sql);
                                        ps.setString(1, jTextFieldNombre.getText());
                                        ps.setString(2, jTextFieldApellido1.getText());
                                        ps.setString(3, jTextFieldApellido2.getText());
                                        ps.setString(4, jTextFieldTelefono.getText());
                                        ps.setString(5, jTextFieldCorreo.getText());
                                        ps.setString(6, jTextFieldUser.getText());
                                        ps.setString(7, contrasenaEncriptada);
                                        ps.setString(8, rol);
                                        ps.executeUpdate();
                                        ps.close();
                                     }
                                     
                                     conexion.close();
                                 } catch (SQLException ex) {
                                     System.getLogger(JDialogAltaUsuario.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                                 }
                            }else{
                                resaltarPassword(jPasswordFieldContrasena1);
                                resaltarPassword(jPasswordFieldContrasena2);
                                JOptionPane.showConfirmDialog(rootPane,
                                                        "Las contraseñas no coinciden", 
                                                        "Error", 
                                                        JOptionPane.OK_CANCEL_OPTION, 
                                                        JOptionPane.ERROR_MESSAGE);
                                jPasswordFieldContrasena1.requestFocus();
                            }
                        }else{
                            resaltarCampo(jTextFieldCorreo);
                            JOptionPane.showConfirmDialog(rootPane,
                                                    "Formato de correo no valido", 
                                                    "Error", 
                                                    JOptionPane.OK_CANCEL_OPTION, 
                                                    JOptionPane.ERROR_MESSAGE);
                       }
                    }else{
                        resaltarCampo(jTextFieldTelefono);
                        JOptionPane.showConfirmDialog(rootPane,
                                                "Formato de telefono no valido", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
                   }
                } 
            }
        }else{
            resaltarCampo(jTextFieldUser);
            JOptionPane.showConfirmDialog(rootPane,
                                                "El usuario " + user + " ya existe", 
                                                "Error", 
                                                JOptionPane.OK_CANCEL_OPTION, 
                                                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    public boolean existeUsuario(String usuario){
        boolean existe= false;
        try {    
            nueva.conectar();
            String sql = "SELECT * FROM Usuario WHERE usuario_login = ?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setString(1, usuario);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) 
                existe = true;
                        
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            System.getLogger(JDialogAltaUsuario.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        return existe;
    }
    
    public void comprobarLongitudTelefono(){
        jTextFieldTelefono.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
        
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                comprobarLongitud();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                 comprobarLongitud();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                 comprobarLongitud();
            }
            
            private void comprobarLongitud(){
                if(jTextFieldTelefono.getText().length() < 9){
                    jTextFieldTelefono.setBackground(new java.awt.Color(255, 200, 200));
                    jTextFieldTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
                }else{
                    jTextFieldTelefono.setBackground(java.awt.Color.WHITE);
                    jTextFieldTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 1));
                }
            }
            
        });
    }
    
    public void comprobarLongitudes(){
        javax.swing.event.DocumentListener listener = new javax.swing.event.DocumentListener(){
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                validarLongitud(e);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                validarLongitud(e);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                validarLongitud(e);
            }

            private void validarLongitud(javax.swing.event.DocumentEvent e){
                javax.swing.text.Document doc = e.getDocument();
                javax.swing.JTextField campo = null;

                // Identificar qué campo se está editando
                if (doc == jTextFieldNombre.getDocument()) campo = jTextFieldNombre;
                else if (doc == jTextFieldApellido1.getDocument()) campo = jTextFieldApellido1;
                else if (doc == jTextFieldApellido2.getDocument()) campo = jTextFieldApellido2;
                else if (doc == jTextFieldCorreo.getDocument()) campo = jTextFieldCorreo;
                else if (doc == jTextFieldUser.getDocument()) campo = jTextFieldUser;

                if(campo != null){
                    if(campo.getText().length() > 30){
                        campo.setBackground(new java.awt.Color(255, 200, 200));
                        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));
                    }else{
                        campo.setBackground(java.awt.Color.WHITE);
                        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 1));
                    }
                }
            }
        };

        // Aplicar el listener a todos los campos con límite de 30 caracteres
        jTextFieldNombre.getDocument().addDocumentListener(listener);
        jTextFieldApellido1.getDocument().addDocumentListener(listener);
        jTextFieldApellido2.getDocument().addDocumentListener(listener);
        jTextFieldCorreo.getDocument().addDocumentListener(listener);
        jTextFieldUser.getDocument().addDocumentListener(listener);
    }
    
    private static final Pattern PATTERN_EMAIL = Pattern.compile( //Patron para validar el email
        "^[A-Za-z0-9_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$" // se permiten letras, simbolos, tiene que haber un @
                                                          // y un . , el dominio tiene que tener 2 letras
    );
    
    private static final Pattern PATTERN_TELEFONO = Pattern.compile( //Patron para validar el telefono
        "^[0-9]{9}$" // 9 Numeros del 0-9
    );

     public static boolean validarEmail(String correo) { //Compobamos que el correo cumpla el patron
        if (!PATTERN_EMAIL.matcher(correo).matches()) { 
            return false;
        }
        return true;
    }
     
    public static boolean validarTelefono(String telefono) { //Comprobamos que el telefono cumpla el patron
        if (!PATTERN_TELEFONO.matcher(telefono).matches()) {
            return false;
        }
        return true;
    }
    
    private void resaltarCampo(javax.swing.JTextField campo) {
        campo.setBackground(new java.awt.Color(255, 200, 200));
        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2));  
        campo.requestFocus();
        campo.setText("");
    }
    
    private void resetearCampo(javax.swing.JTextField campo) {
        campo.setBackground(java.awt.Color.WHITE);
        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 1));
    }
    
    private void resaltarPassword(javax.swing.JPasswordField campo) {
        campo.setBackground(new java.awt.Color(255, 200, 200));
        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2)); 
        campo.requestFocus();
    }
    
     private void resetearPassword(javax.swing.JPasswordField campo) {
        campo.setBackground(java.awt.Color.WHITE);
        campo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 1));
    }
    
    private void enterEnFormulario(){
        
        //Nombre -> Apellido1
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    jTextFieldApellido1.requestFocus();
                }
            }
        });

        //Apellido1 -> Apellido2 - Apellido1 ->Nombre
        jTextFieldApellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    jTextFieldApellido2.requestFocus();
                }
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP) {
                    jTextFieldNombre.requestFocus();
                }
            }
        });

        // Apellido2 -> Teléfono - Apellido2 -> Apellido1
        jTextFieldApellido2.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    jTextFieldTelefono.requestFocus();
                }
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP) {
                    jTextFieldApellido1.requestFocus();
                }
            }
        });

        // Teléfono -> Correo - Telefono -> Apellido 2
        jTextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    jTextFieldCorreo.requestFocus();
                }
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP) {
                    jTextFieldApellido2.requestFocus();
                }
            }
        });

        // Correo -> Usuario - Correo -> Telefono
        jTextFieldCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    jTextFieldUser.requestFocus();
                }
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP) {
                    jTextFieldTelefono.requestFocus();
                }
            }
        });

        // User -> Contraseña1 - User -> Correo
        jTextFieldUser.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    jPasswordFieldContrasena1.requestFocus();
                }
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP) {
                    jTextFieldCorreo.requestFocus();
                }
            }
        });

        // Contraseña1 -> Contraseña2 - Contraseña1 -> User
        jPasswordFieldContrasena1.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    jPasswordFieldContrasena2.requestFocus();
                }
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP) {
                    jTextFieldUser.requestFocus();
                }
            }
        });

        // Contraseña2 -> Botón Aceptar - Contraseña2 -> Contraseña1
        jPasswordFieldContrasena2.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    jButtonAlta.requestFocus(); 
                }
                if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP){
                     jPasswordFieldContrasena1.requestFocus();
                }
            }
        });
        
        //Aceptar -> Cancelar - Aceptar -> Contraseña2
        jButtonAlta.addKeyListener(new java.awt.event.KeyAdapter(){
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt){
                if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_LEFT){
                    jButtonCancelar.requestFocus();
                }   
                if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP){
                    jPasswordFieldContrasena2.requestFocus();
                }
            }
        });
        
        //Cancelar -> Aceptar - Cancelar -> Contraeña2
        jButtonCancelar.addKeyListener(new java.awt.event.KeyAdapter(){
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt){
                if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_LEFT){
                    jButtonAlta.requestFocus();
                }   
                if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP){
                    jPasswordFieldContrasena2.requestFocus();
                }
            }
        });
    }
    
    private void camposObligatorios(){
    jLabelNombre.setText("<html>Nombre <font color='red'>*</font></html>");
    jLabelApellido1.setText("<html>Primer apellido <font color='red'>*</font></html>");
    jLabelTelefono.setText("<html>Telefono <font color='red'>*</font></html>");
    jLabelCorreo.setText("<html>Correo <font color='red'>*</font></html>");
    jLabelUsuario.setText("<html>Usuario <font color='red'>*</font></html>");
    jLabelContrasena1.setText("<html>Contraseña <font color='red'>*</font></html>");
    jLabelContrasena2.setText("<html>Introduzca de nuevo la contraseña <font color='red'>*</font></html>");
    }
    
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }

   public void cargarDatosUsuario(int id) {
        try {
            nueva.conectar();
            String sql = "SELECT * FROM Usuario WHERE id = ?";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                jTextFieldNombre.setText(rs.getString("nombre"));
                jTextFieldApellido1.setText(rs.getString("apellido1"));
                jTextFieldApellido2.setText(rs.getString("apellido2"));
                jTextFieldTelefono.setText(rs.getString("telefono"));
                jTextFieldCorreo.setText(rs.getString("correo"));
                jTextFieldUser.setText(rs.getString("usuario_login"));
                // No cargamos la contraseña por seguridad
            }

            rs.close();
            ps.close();
            conexion.close();
        } catch (SQLException ex) {
            
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelContrasena1;
    private javax.swing.JLabel jLabelContrasena2;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContrasena1;
    private javax.swing.JPasswordField jPasswordFieldContrasena2;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
