/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package servix.mesas;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import servix.ConexionBBDD;
import servix.JFrameServix;
import servix.Login_CRUD.Encargado.JDialogInterfazEncargado;
import servix.Mesa;

/**
 *
 * @author DAM2ALU11
 */
public class JTableAdministrarMesas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JTableAdministrarMesas.class.getName());

    /**
     * Creates new form JTableAdministrarMesas
     */
    
    ConexionBBDD nueva;
    Connection conexion;
    DefaultTableModel dtm;
    ArrayList<Mesa> lista = new ArrayList<>();
    String user;
    EliminarMesa eliminar = new EliminarMesa();
    JFrameServix padre;
    public JTableAdministrarMesas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/icon.png"));
        this.setIconImage(icon.getImage());
        this.setTitle("Servix");
        this.user=user;
        this.padre=(JFrameServix) parent;
        nueva = new ConexionBBDD();
        conexion=nueva.getConnection();
        dtm= new DefaultTableModel();
        jTableMesas.setModel(dtm);
        dtm.setColumnIdentifiers(Mesa.getColumnas());
        cargarMesas();
        
        if (JFrameServix.hb != null) {
            JFrameServix.hb.enableHelpKey(this.getContentPane(), "ayuda_mesas", JFrameServix.hs);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMesas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonAnadirMesa = new javax.swing.JButton();
        jButtonEliminarMesa = new javax.swing.JButton();
        jButtonEditarMesa = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrar las mesas");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jTableMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMesas);

        jButtonAnadirMesa.setText("Añadir mesa");
        jButtonAnadirMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirMesaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAnadirMesa);

        jButtonEliminarMesa.setText("Eliminar mesa");
        jButtonEliminarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarMesaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEliminarMesa);

        jButtonEditarMesa.setText("Editar mesa");
        jButtonEditarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarMesaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditarMesa);

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVolver);

        jLabel2.setText("Alba Pallás");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarMesas(){
        try {
            lista.clear();
            nueva.conectar();
            String sql = "SELECT * FROM Mesa";
            PreparedStatement ps = conexion.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                Mesa m = new Mesa(
                    rs.getInt("id_mesa"),
                    rs.getInt("capacidad"),
                    rs.getBoolean("estado")
                );
                
                lista.add(m);
            }
            
            for(int i=0; i<lista.size(); i++){
                dtm.addRow(lista.get(i).devuelveFila());
            }
        } catch (SQLException ex) {
            System.getLogger(JTableAdministrarMesas.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }
        
    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.setVisible(false);
        this.dispose();
        JDialogInterfazEncargado jdie = new JDialogInterfazEncargado(padre, true);
        jdie.setVisible(true);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonAnadirMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirMesaActionPerformed
        JDialogAnadirMesa jdam = new JDialogAnadirMesa(padre, true);
        jdam.setVisible(true);
        recargarTabla();
    }//GEN-LAST:event_jButtonAnadirMesaActionPerformed

    private void jButtonEditarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarMesaActionPerformed
        int fila = jTableMesas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una mesa para editar.");
        }else{
            String id = dtm.getValueAt(fila, 0).toString();
            JDialogEditarMesa jdem= new JDialogEditarMesa(id, padre, true);
            jdem.setVisible(true);
            recargarTabla();
        }      
    }//GEN-LAST:event_jButtonEditarMesaActionPerformed

    private void jButtonEliminarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarMesaActionPerformed
         int fila = jTableMesas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una mesa para editar.");
        }else{
            eliminar.eliminarMesa((int) dtm.getValueAt(fila, 0));
            recargarTabla();
        }
    }//GEN-LAST:event_jButtonEliminarMesaActionPerformed

    public void recargarTabla() {
        dtm.setRowCount(0);
        cargarMesas();
    }
    
    public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(new FlatCyanLightIJTheme());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrameServix jfs = new JFrameServix();
            jfs.setVisible(true);
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadirMesa;
    private javax.swing.JButton jButtonEditarMesa;
    private javax.swing.JButton jButtonEliminarMesa;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMesas;
    // End of variables declaration//GEN-END:variables
}
